### ISSUE TITLE
The fs.cache node.size property is not updated when file size is 0

### ISSUE THREAD

**Issue by andrewfaulring** [c9/core#101]
The fs.cache does not update the node.size property when the file size is or becomes 0. If the file size is 0 when the fs.cache first loads the node, the node.size property is never set (undefined). If the file size is changed from a non-zero value to 0, the node.size property is not updated. That is, it remains set to the previous non-zero value.

The bug is caused by "if (stat.size)" instead of "if (stat.size !== undefined)" at

https://github.com/c9/core/blob/master/plugins/c9.fs/fs.cache.xml.js#L560

Note that the "if (stat.mtime)" on L562 is also incorrect. Although, having mtime set to 0 is unlikely.

A similar bug causes the tooltips to not include the file size when the size is 0: "(size && ..." should be "(size !== undefined && ...".

https://github.com/c9/core/blob/master/plugins/c9.ide.tree/tree.js#L250

**Comment by nightwing** [comment]
The fix you suggested is implemented now, thank you for reporting this issue.

**Comment by andrewfaulring** [comment]
@nightwing That commit fixed the problem as reported. The tooltips show the correct size (including now "0 bytes" for an empty file) when the workspace loads. There appears to be a separate issue in which the workspace tree does not update the file size after a file is edited. This affects files of all sizes, so I'll open a separate issue for that bug.
