### ISSUE TITLE
Can't mount FTP-server

### ISSUE THREAD

**Issue by chasedev** [c9/core#102]
Hello,

I can't mount any ftp-server in my local environment, which dependencies do i have to install? I have opened port 21.

Kind regards,
Nick

**Comment by nightwing** [comment]
I think you'll need curlftpfs, sshfs-fuse, fuse
code for mounting is at https://github.com/c9/c9.ide.mount/blob/master/ftp.js#L20

**Comment by chasedev** [comment]
Thanks nightwing! If i had a closer look in the code i could have found it myself :)
