### ISSUE TITLE
Uncaught Error: Unexpected metadata

### ISSUE THREAD

**Issue by asinyagin** [c9/core#103]
Hey,

I'm receiving the exception from time to time: `fs.xhr.js:45 Uncaught Error: Unexpected metadata`. Looks like, it's the same error as in https://github.com/c9/core/issues/71. It's hard to reproduce this bug, I use incognito window in Chrome for this. In new incognito window just after IDE's been loaded, I hit the button that reads files and sometimes (pretty often) I see this error.

**Comment by nightwing** [comment]
Interesting, so metadata is added on the server, not requested by mistake.
I'll change https://github.com/c9/newclient/commit/6a29745d#diff-7b33fdbdaf13ce6067b27c1a074c3583R45 to remove metadata instead of throwing an error.

**Comment by nightwing** [comment]
done in https://github.com/c9/core/commit/32bb19365ed140582472bb5e108f4e35d8321857
please let me know what it prints to console when the error happens

**Comment by asinyagin** [comment]
@nightwing thanks!
