### ISSUE TITLE
[enhancement] Save/Load tabsets

### ISSUE THREAD

**Issue by aelana** [c9/core#104]
Suggestion here, sometimes I have several file tabs open with various files I am working on for an issue and have to temporarily drop that issue and work on something more critical.   It would be really useful to be able to save a list of files/tabs I have open and re-load those at a later date.  Especially if you could have more than one "saved set" for things like config files/etc.

**Comment by nightwing** [comment]
Prompted by this issue, and feature request for multimonitor support,
we have added `window>saved layouts` menu for saving and loading tabsets.
And also `?state=...` flag in the url, which allows to have two separate ide in parallel
Sorry for not updating this issue earlier, and please let us know if you have any other feature requests!
