### ISSUE TITLE
run_output not visible in runner

### ISSUE THREAD

**Issue by SteFletcher** [c9/core#106]
I'm using master branch.

Running locally on OSX tried with node v0.10.35 and v0.12.4

Start an express based app in the runner and it appears to hang in the c9 runner console.   Checking for the process I can 3 new processes:
```
node      18977 me   17u  IPv4 0x1c80269e9b0eca15      0t0  TCP localhost:8181 (LISTEN)
node      19138 me   11u  IPv4 0x1c80269e9c889875      0t0  TCP localhost:15455 (LISTEN)
node      19187 me   16u  IPv6 0x1c80269e8b696dc5      0t0  TCP *:15454 (LISTEN)
node      19187 me   31u  IPv6 0x1c80269e8b6972c5      0t0  TCP *:http-alt (LISTEN)
```
The server responds to requests as expected but i see no output in the c9 console.

![screen shot 2015-06-21 at 09 44 40](https://cloud.githubusercontent.com/assets/1644137/8271046/32e207f4-17fa-11e5-86d7-cc8481ea3871.png)

The file: .run_output874300.watch is present in the .c9 folder but with no content.  

Stopping the process via the runner UI I get this message:
![screen shot 2015-06-21 at 09 52 07](https://cloud.githubusercontent.com/assets/1644137/8271078/4e63e51e-17fb-11e5-9821-8dc84b9b7427.png)

**Comment by nightwing** [comment]
are you using tmux 2.0? If yes this should be fixed by https://github.com/c9/core/commit/0c2d81350ed4446519e09884a9ff0f3d2fbbe5e9

**Comment by nightwing** [comment]
Another related issue was fixed by https://github.com/c9/core/commit/fa7496364c9639ff779eb4d7bd623c2d8e5a799a#diff-e7179894d8b4883655a1e6c8b33df495R1615. Please comment if you still see this issue with the latest version
