### ISSUE TITLE
Problem with installing pty.js

### ISSUE THREAD

**Issue by zaozaool** [c9/core#109]
When I do "scripts/install-sdk.sh" it's stopped, the console log is stopped at the ":Installing pty.js", no anymore logs. Anyone know why?

**Comment by nightwing** [comment]
which os do you use?

**Comment by zaozaool** [comment]
Vagrant on Windows, detail is "
Linux version 3.2.0-23-generic-pae (buildd@palmer) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu4) ) #36-Ubuntu SMP Tue Apr 10 22:19:09 UTC 2012"
And now, the error log is below:

:Installing pty.js
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/home/vagrant/.c9/node/bin/node" "/home/vagrant/.c9/node/bin/npm" "install" "node-gyp"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for /home/vagrant/.c9/tmp/npm-15943-8625ca95/registry.npmjs.org/node-gyp/-/node-gyp-2.0.1.tgz
npm ERR! Expected: 38e9c5b54df7115cd0953cee67863f839d0c7888
npm ERR! Actual:   38f18d63aa19c67b1b976a112f79f78356362687
npm ERR! From:     https://registry.npmjs.org/node-gyp/-/node-gyp-2.0.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/.c9/tmux-1.9/npm-debug.log

**Comment by nightwing** [comment]
Strange, could you try deleting ~/.c9 folder and running installer again,
Looks like there was an error while npm was downloading the archive for node-gyp-2.0.1.tgz

Note that if you install tmux globally via apt-get, running install-sdk.sh will be faster.

**Comment by zaozaool** [comment]
Yes, it's strange, follow your steps to install, the error happened again, actually the "node-gyp-2.0.1.tgz" is existing in folder ' /home/vagrant/.c9/tmp/npm-15943-8625ca95/registry.npmjs.org/node-gyp/-".

Is the "node-gyp-2.0.1.tgz" not correct?

**Comment by zaozaool** [comment]
What's that mean about this? Is it means the node version too high?

>vagrant@precise32:~/.c9$ sudo npm install pty.js@0.2.7-1
> pty.js@0.2.7-1 install /home/vagrant/.c9/node_modules/pty.js
> node-gyp rebuild
>
>gyp WARN install got an error, rolling back install
>gyp ERR! configure error 
>gyp ERR! stack Error: node-v0.12.5.tar.gz local checksum f91fb2cf14b3887458d27ab0c1dc1cb53edd5a12f09702609b953b9f86ba04cd >not match remote 4bc1e25f4c62ac65324d3cf4aa9de2d801cd708757c3567b6ad2ced7df30cdd2
>gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
>gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
>gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
>gyp ERR! stack     at _stream_readable.js:908:16
>gyp ERR! stack     at process._tickCallback (node.js:355:11)
>gyp ERR! System Linux 3.2.0-23-generic-pae
>gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
>gyp ERR! cwd /home/vagrant/.c9/node_modules/pty.js
>gyp ERR! node -v v0.12.5
>gyp ERR! node-gyp -v v2.0.1
>gyp ERR! not ok 
>npm ERR! Linux 3.2.0-23-generic-pae
>npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pty.js@0.2.7-1"
>npm ERR! node v0.12.5
>npm ERR! npm  v2.11.2
>npm ERR! code ELIFECYCLE
>
>npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
>npm ERR! This is most likely a problem with the pty.js package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node-gyp rebuild
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls pty.js
>npm ERR! There is likely additional logging output above.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     /home/vagrant/.c9/npm-debug.log

**Comment by nightwing** [comment]
this seems to be related http://stackoverflow.com/questions/28385574/error-while-installing-socket-io-by-npm
could you try `npm cache clean --force` if that works `npm cache ls`  should print only `~/.npm` after that.

**Comment by zaozaool** [comment]
I had try, and ```npm cache ls``` print ```~/.npm``` only after ```npm cache clean --force```. 
Then I had ran ```install-sdk.sh```, the error happened again, same message.

**Comment by nightwing** [comment]
could you please try version from https://github.com/c9/install/pull/51
```sh
curl -L https://raw.githubusercontent.com/c9/install/update-node/install.sh | bash
```

**Comment by zaozaool** [comment]
@nightwing , Now, the node version is ```v0.12.6```, but when I ran 
```curl -L https://raw.githubusercontent.com/c9/install/update-node/install.sh | bash```

the new error occured:
```
:Installing pty.js

> pty.js@0.2.8 install /home/vagrant/.c9/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/home/vagrant/.c9/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function 'void PtyFork(const v8::FunctionCallbackInfo<v8::Value>&)':
../src/unix/pty.cc:185:34: warning: ignoring return value of 'int chdir(const char*)', declared with attribute warn_unused_result [-Wunused-result]
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory `/home/vagrant/.c9/node_modules/pty.js/build'
pty.js@0.2.8 node_modules/pty.js
鈹溾攢鈹€ extend@1.2.1
鈹斺攢鈹€ nan@1.8.4

real    0m20.750s
user    0m1.444s
sys     0m3.852s
:Installing Collab Dependencies
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/home/vagrant/.c9/node/bin/node" "/home/vagrant/.c9/node/bin/npm" "install" "sqlite3@3.0.5"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2

npm ERR! shasum check failed for /home/vagrant/.c9/tmp/npm-16896-6cd78f6b/registry.npmjs.org/sqlite3/-/sqlite3-3.0.5.tgz
npm ERR! Expected: 27adf608575e847f847961bf4a90a9c60f26fd57
npm ERR! Actual:   990183354db5f3645efa34ecc3d28c451f704579
npm ERR! From:     https://registry.npmjs.org/sqlite3/-/sqlite3-3.0.5.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/.c9/npm-debug.log
```
please help, thanks.

**Comment by nightwing** [comment]
Looks like npm is unable to download some modules.
What do you get when running
```js
curl -O https://registry.npmjs.org/sqlite3/-/sqlite3-3.0.5.tgz
sha1sum sqlite3-3.0.5.tgz
```

you can skip collab by running 
```
curl -LO https://raw.githubusercontent.com/c9/install/update-node/install.sh
bash ./install.sh install node tmux_install nak ptyjs
```
after that install-sdk.sh should work

**Comment by zaozaool** [comment]
It's very slow and it closed when ran 
```curl -O https://registry.npmjs.org/sqlite3/-/sqlite3-3.0.5.tgz```

log showed
```
vagrant@precise32:~$ curl -O https://registry.npmjs.org/sqlite3/-/sqlite3-3.0.5.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 23 2867k   23  687k    0     0   5721      0  0:08:33  0:02:03  0:06:30     0
curl: (18) transfer closed with 2232835 bytes remaining to read
```

When I ran 
```curl -LO https://raw.githubusercontent.com/c9/install/update-node/install.sh```
the log stopped at 
```
:Installing TMUX
:Existing tmux version is up-to-date

real    0m0.577s
user    0m0.016s
sys     0m0.492s
:Installing Nak
```

Is it because my network is too slow?

Շնորհակալություն

**Comment by nightwing** [comment]
> Is it because my network is too slow?

it might be, or there may be something else interrupting the download.
Do you get the same when running curl from git bash shell on windows without vagrant?

**Comment by zaozaool** [comment]
I ran
```
curl -LO https://raw.githubusercontent.com/c9/install/update-node/install.sh
bash ./install.sh install node tmux_install nak ptyjs
```
the log showed
```
:Installing Nak
npm WARN excluding symbolic link tests/filelist_fixtures/symlink-to-1.txt -> 1.txt
npm WARN excluding symbolic link tests/filelist_fixtures/symlink-to-nowhere.txt -> nowhere.txt
npm WARN excluding symbolic link tests/search_fixtures/symlink-to-file1.txt -> file1.txt
npm WARN excluding symbolic link tests/filelist_fixtures/symlink-to-1.txt -> 1.txt
npm WARN excluding symbolic link tests/filelist_fixtures/symlink-to-nowhere.txt -> nowhere.txt
npm WARN excluding symbolic link tests/search_fixtures/symlink-to-file1.txt -> file1.txt
npm WARN engine simplefunc@0.0.2: wanted: {"node":">= 0.6.0 && < 0.9.0"} (current: {"node":"0.12.6","npm":"2.11.2"})
nak@0.3.3 node_modules/nak
鈹溾攢鈹€ simplefunc@0.0.2
鈹溾攢鈹€ colors@0.6.2
鈹斺攢鈹€ isbinaryfile@2.0.0

real    0m12.344s
user    0m0.596s
sys     0m2.272s
:Installing pty.js

> pty.js@0.2.8 install /home/vagrant/.c9/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/home/vagrant/.c9/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function 'void PtyFork(const v8::FunctionCallbackInfo<v8::Value>&)':
../src/unix/pty.cc:185:34: warning: ignoring return value of 'int chdir(const char*)', declared with attribute warn_unused_result [-Wunused-result]
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory `/home/vagrant/.c9/node_modules/pty.js/build'
pty.js@0.2.8 node_modules/pty.js
鈹溾攢鈹€ extend@1.2.1
鈹斺攢鈹€ nan@1.8.4

real    0m18.006s
user    0m1.316s
sys     0m4.348s
~/.c9/node_modules/.bin ~/.c9
~/.c9
:Done.
vagrant@precise32:~/cloud9/c9sdk$ 
```

Now, should I to run ```install-sdk.sh```?

**Comment by zaozaool** [comment]
>Do you get the same when running curl from git bash shell on windows without vagrant?

Download success. It may be a network problem.

**Comment by nightwing** [comment]
> Now, should I to run install-sdk.sh?

yes, if ~/.c9/installed file exists install-sdk.sh won't try to run install.sh again

**Comment by zaozaool** [comment]
Where can I download the ```connect/lib/utils```? 
```
vagrant@precise32:~/cloud9/c9sdk$ sudo node server.js -p 8181 -l 0.0.0.0 -a :
Starting standalone
{ [Error: Cannot find module 'connect/lib/utils'] code: 'MODULE_NOT_FOUND' }
```

```npm install connect``` can't download:

```
root@precise32:/home/vagrant/cloud9/c9sdk#  sudo npm install connect
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "connect"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2

npm ERR! shasum check failed for /tmp/npm-19964-6ff918d3/registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
npm ERR! Expected: a567c2af000ad22dc8f2a653d91978ae1f5316f4
npm ERR! Actual:   1fb8f115947a6cff0f1ed187e268c75957ab1efe
npm ERR! From:     https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/cloud9/c9sdk/npm-debug.log
```

What's going on?

**Comment by nightwing** [comment]
> What's going on?

The network issue breaks npm.

You can try to install sdk on your windows machine and then copy node_modules into vm, or try to fix network issue in some other way.

**Comment by zaozaool** [comment]
OK, I'm done. Thank you so much.Good night.

**Comment by pRoy24** [comment]
This happened to me on a GCP instance when I used the default OS Debian GNU/Linux 9....should go away if you use vanilla Ubuntu LTS
