### ISSUE TITLE
FTP "workpaces" count "undefined"

### ISSUE THREAD

**Issue by cjbrowne** [c9/core#111]
![cloud9-bug](https://cloud.githubusercontent.com/assets/375847/8592663/872f55c4-2631-11e5-8103-6f4262018aae.png)

Two separate bugs here I guess, the first is the typo in "workspaces" and the second is the number of FTP workspaces I have available is "undefined".

I'm guessing it's something wrong with the API, because the response to this request:
https://api.c9.io/user/quota?access_token=####################

Comes back as:
{"total":{"ram":512,"disk":1024,"ssh":1},"used":{"ram":512,"disk":1024,"ssh":0,"ftp":0,"free":4,"premium":2},"name":"Free","price":0,"version":2}

Which is to say, there is no total for FTP in the response.

**Comment by nightwing** [comment]
Ftp workspaces are going to be deprecated https://c9.io/blog/announcing-deprecation-of-ftp-workspaces/
