### ISSUE TITLE
Question about elasticsearch

### ISSUE THREAD

**Issue by Man-Fai** [c9/core#112]
Hi, 
  I am beginner of web-development. I love c9 very much. It saves a a lot of trouble. 
I am following a ruby on rails tutorial. It requires elasticsearch to perform the search function. But I don't know is it possible to install or use elasticsearch on c9.  Thank you in advance.

**Comment by nightwing** [comment]
try `gem install elasticsearch`
Installing software on c9 vm is same as installing it on any ubuntu vm. Stackoverflow or c9 support is a better place for this kind of questions.
