### ISSUE TITLE
api.setPersistentData issue

### ISSUE THREAD

**Issue by jarodium** [c9/core#114]
Hello all

In my c9.io account, I have started hacking around with a new plugin.
I have come to the part to create some entries in the Preferences Panel and i'm about to start to save persistent data into the project context but, when I try to apply the following:

```javscript
settings.on("project/mysql_server/@db_hname", function(value){
    api.setPersistentData("project", { db_hname: value }, function(err){
        if (err) console.error("Error occurer while saving db_hname");
    });
}, plugin);
```
Debug mode issues the following error:

Error: Unsupported context: project: workspace-php.js (line 24410)

The docs at https://cloud9-sdk.readme.io/docs/storing-persistent-data say I can use project as context, so I think this is a bug.

**Comment by nightwing** [comment]
This is an error on docs.c9.io 
It should say `"workspace"` instead of `"project"`

**Comment by jarodium** [comment]
Thanks xD
