### ISSUE TITLE
Password field css failing.

### ISSUE THREAD

**Issue by jarodium** [c9/core#115]
Hello there

When developing a new plugin i have the following:

```javascript
"Password": {
    type: "password",
    setting: "project/mysql_server/@the_pass",
    position: 500
}
```
In debug mode, the password field loses the css style for the field. See atached image:
![captura de ecra 2015-07-31 as 23 06 31](https://cloud.githubusercontent.com/assets/1470446/9018668/2ae3243a-37d9-11e5-8a98-e32881c5e4af.png)

**Comment by nightwing** [comment]
Hi, could you share your plugin code, or give me access to your cloud9 workspace, that would make it much easier for me to debug the issue.

**Comment by jarodium** [comment]
define(function(require, exports, module) {
    main.consumes = [
        "Plugin", "ui", "commands", "tabManager", "preferences", "settings","menus","PreferencePanel","ext","c9",
    ];
    main.provides = ["mysql.admin"];
    return main;

    function main(options, imports, register) {
        var Plugin = imports.Plugin;
        var ui = imports.ui;
        var menus = imports.menus;
        var commands = imports.commands;
        var settings = imports.settings;
        var prefs = imports.preferences;
        var tabs = imports.tabManager;
        var ext = imports.ext;
        var c9 = imports.c9;


        /***** Initialization *****/
        var remote;
        var plugin = new Plugin("Ajax.org", main.consumes);
        var emit = plugin.getEmitter();
        var api  = plugin.setAPIKey(options.apikey);
        
        var showing;
        
        /**
         * Remote loading remote plugin for interaction.
         */
        function loadService() {
            //atempt to load plugin and use mysql npm module
            ext.loadRemotePlugin("servico_mysql", {
                code: require("text!./servico_mysql.js")
                //file: c9.home + "/.c9/lib/servico_mysql.js"
            }, function(err, api) {
                //why api is undefined?
                api.connect(9000, function(err, meta){
                    var stream = meta.stream;
                    stream.on("data", function(chunk){
                        console.log(chunk);
                    });
                    if (err) return console.error(err);
                });
                
                if (err) return console.error(err);
                remote = api;
                
            });
        }
        
        function load() {
            commands.addCommand({
                name: "mysql_admin_format",
                bindKey: { 
                    mac: "Command-J", 
                    win: "Ctrl-J" 
                },
                exec: function(){ 
                    alert("Success!");
                },
                isAvailable: function(editor) {
                    if (editor && editor.ace)
                        return !editor.ace.selection.isEmpty();
                    return false;
                }
            }, plugin);
        
            /*menus.addItemByPath("Tools/My Menu Item", new ui.item({
                command: "mysql_admin_format"
            }), 300, plugin);*/
            
            settings.on("read", function(e){
                settings.setDefaults("project/mysql_server", [
                    ["db_hname", "localhost"],
                    ["db_uname", ""],
                    ["db_pass", ""],
                    ["db_name", ""],
                    ["db_hport","3306"],
                    ["db_hsocket",""]
                ]);
            });
            
            settings.on("project/mysql_server/@db_hname", function(value){
                api.setPersistentData("project", { db_hname: value }, function(err){
                    if (err) console.error("Error occurer while saving db_hname");
                });
            }, plugin);
            
            prefs.add({
                "Project" : {
                    position: 450,
                    "MySQL Server" : {
                        position: 100,
                        "Hostname/IP": {
                            type: "textbox",
                            setting: "project/mysql_server/@db_hname",
                            position: 100
                        },
                        "Port": {
                            type: "textbox",
                            setting: "project/mysql_server/@db_hport",
                            position: 200
                        },
                        "Database name": {
                            type: "textbox",
                            setting: "project/mysql_server/@db_name",
                            position: 300
                        },
                        "Database user": {
                            type: "textbox",
                            setting: "project/mysql_server/@db_uname",
                            position: 400
                        },
                        "Database password": {
                            type: "password",
                            setting: "project/mysql_server/@db_pass",
                            position: 500
                        },
                        "Unix Socket": {
                            type: "textbox",
                            setting: "project/mysql_server/@db_hsocket",
                            position: 600
                        }
                    }
                }
            }, plugin);
            
            loadService();
            c9.on("connect", loadService);
            c9.on("disconnect", function(){ remote = null });
        }
        
        var drawn = false;
        function draw() {
            if (drawn) return;
            drawn = true;
            
            // Insert HTML
            var markup = require("text!./plugin.html");
            ui.insertHtml(document.body, markup, plugin);
            
            // Insert CSS
            ui.insertCss(require("text!./style.css"), options.staticPrefix, plugin);
        
            emit("draw");
        }
        
        /***** Methods *****/
        
        function show() {
            draw();
            
            var div = document.querySelector(".helloworld");
            div.style.display = "block";
            div.innerHTML = settings.get("user/my-plugin/@second");
            
            emit("show");
            showing = true;
        }
        
        function hide() {
            if (!drawn) return;
            
            document.querySelector(".helloworld").style.display = "none";
            
            emit("hide");
            showing = false;
        }
        
        /***** Lifecycle *****/
        
        plugin.on("load", function() {
            load();
        });
        plugin.on("unload", function() {
            drawn = false;
            showing = false;
        });
        
        /***** Register and define API *****/
        
        /**
         * This is an example of an implementation of a plugin.
         * @singleton
         */
        plugin.freezePublicAPI({
            /**
             * @property showing whether this plugin is being shown
             */
            get showing(){ return showing; },
            
            _events: [
                /**
                 * @event show The plugin is shown
                 */
                "show",
                
                /**
                 * @event hide The plugin is hidden
                 */
                "hide"
            ],
            
            /**
             * Show the plugin
             */
            show: show,
            
            /**
             * Hide the plugin
             */
            hide: hide,
        });
        
        register(null, {
            "mysql.admin": plugin
        });
    }
});

**Comment by jarodium** [comment]
issue #114 is also present in the code.

**Comment by nightwing** [comment]
Fixed in https://github.com/c9/core/commit/4d2e52229071a7a642ad6281c2a2cc69ca11062f. Thanks for the example code!
