### ISSUE TITLE
Working with remote plugins

### ISSUE THREAD

**Issue by jarodium** [c9/core#121]
Hello all

I am trying to develop a client/server plugin pair, as stated in https://cloud9-sdk.readme.io/docs/remote-plugins.
Bellow is part of the code:

Client snippet:
```javascript
remote.init(function(meta) {
    console.log(meta);
});
```

Server snippet
```javascript
callback({stream:COLLATIONS.join("\n")});
//variants
//callback(COLLATIONS.join("\n"));
//callback({api:COLLATIONS.join("\n")}); //this one is issuing Segfault in the debug mode
```
The Collations var is a simple array, and it is stated on the docs that I cannot send any functions or recursive options, so I just make the Collations into a string.

The return meta in remote.init always gets me a object {stack:'NUMBER undefined'} when I was expecting a quite large string.

**Comment by nightwing** [comment]
first argument is the error, stream is supposed to be a node.js Stream, try

```js
callback(null, {value : COLLATIONS.join("\n")});
```

however if the string is really large, it would block socket for noticeable amount of time, and it is better to send it via actual stream.

**Comment by jarodium** [comment]
Great.
It worked... I have made some minor adjustments to the callback, but it is working as expected :D

Thanks @nightwing
