### ISSUE TITLE
Persistency timing out

### ISSUE THREAD

**Issue by jarodium** [c9/core#123]
Hello all

This is giving me timeouts in my debug mode:

```
api.getPersistentData("workspace",function(err,data) {
                    if (err) console.info(err);
```

I check the requests from my firebug console and I find that
https://api.c9.dev/projects/0/persistent/0000000000000000000000000000=?access_token=token

is taking 60s and then it times out.

Best regards

**Comment by nightwing** [comment]
Sorry for a late reply.
The `getPersistentData` api is broken on master, and fixing it seems to take longer than we expected.

until it is fixed please use the following snippet instead of `plugin.setAPIKey`

```js
var fs = imports.fs
function setAPIKey(apikey){
    function getPersistentData(apiKey, type, callback){
        fs.readFile("~/.c9/persistent/" + type + "/" + apiKey, function(err, data){
            if (err) return callback(err);
            try { callback(null, JSON.parse(data)); }
            catch(e){ return callback(e); }
        });
    }
    
    function setPersistentData(apiKey, type, data, callback){
        fs.writeFile("~/.c9/persistent/" + type + "/" + apiKey, JSON.stringify(data), {
             parents:true
        }, callback);
    }
    
    return {
        getPersistentData: getPersistentData.bind(this, apikey),
        setPersistentData: setPersistentData.bind(this, apikey)
    };
}
```

it can be used exactly same way as the real setAPIKey

```js
api = setAPIKey(...);
api.setPersistentData("workspace", {xxa: 1}, function() {    
})

api.getPersistentData("workspace", function(e,r) {
    console.log(e,r)
})
```

**Comment by jarodium** [comment]
Thanks :) 
I will try that snippet and report back.
For now I'll close this comment.

**Comment by jarodium** [comment]
Hello 
After applying the function, I get this message:

Error: ENOENT, open '/home/ubuntu/.c9/persistent/workspace/0000000000000000000000000000='

Does this mean apiKey is invalid?

**Comment by nightwing** [comment]
we ended up removing this api, since it was not providing any additional security compared to user settings
