### ISSUE TITLE
New editor feature is breaking workflow

### ISSUE THREAD

**Issue by jarodium** [c9/core#126]
Hello all

When I type ```<form>``` there appears a context menu given a little time, but what if I type ```<form>``` and press enter without giving it time to appear? I get ```<form><a href="mailto:"></a></form>```. This happens with some other tags.

I have to say I don't like this feature and was wondering where I can disable it.

Regards

**Comment by pegasussan** [comment]
Yeah, that'd be good... When you write code fast, the thing keeps making unwanted tags!

**Comment by jarodium** [comment]
You can solve this quicky if the first option on this context menu is a blank option and not the a href=

**Comment by Dactyllo** [comment]
+1

**Comment by nightwing** [comment]
This was a regression in completer plugin, it should be fixed now.
