### ISSUE TITLE
how can I change the tab name of the terminal?

### ISSUE THREAD

**Issue by narychen** [c9/core#131]
Some terminal tab name happened to change when I started a new process. The name is renamed to the execuatable name. But some not. How can I do it manully?

**Comment by nightwing** [comment]
you can add the following function to your bashrc

```bash
setTitle() {
    # configure tmux to allow xterm set title sequence
    tmux set-window-option automatic-rename off
    tmux set-option allow-rename off 
    tmux set-option set-titles-string "#T"
    tmux set-option set-titles on
    # set terminal title
    echo -ne "\033]0;$@\007"
}
```
and then run setTitle "my terminal name".

Sometimes bash prompt (PS1) contains `\033]0;...\007` as well, in that case you need to modify it to not allow overriding the title set by setTitle function
Also you may need to remove the old version of tmux from `/usr/bin` by running `sudo apt-get remove tmux`, to not allow it interfering with the version from `/mnt/shared/sbin`
