### ISSUE TITLE
Missing module `sinon`.

### ISSUE THREAD

**Issue by ggoodman** [c9/core#133]
I cloned c9sdk this morning and did a `./scripts/install-sdk.sh` and the IDE failed to start up. The console indicated that the bootstrap process was in an infinite loop, failing to `require('sinon')` in the `raygun_mock` file.

Quick fix: `npm install sinon` at the c9sdk root dir.

**Comment by NNM11** [comment]
I had the same problem as ggoodman.  The quick fix "npm install sinon" did not work for me.
the error log:
--------------------------------------------------------------------
Success!
run 'node server.js -p 8080 -a :' to launch Cloud9

admin@DESKTOP-GB87UJR MINGW64 /c/cloud9/c9sdk (master)
$ node server.js -p 8080 -a :
Starting standalone
Connect server listening at http://127.0.0.1:8080
Trace: Error while starting 'C:\cloud9\c9sdk\configs\standalone':
    at C:\cloud9\c9sdk\server.js:161:25
    at Architect.done (C:\cloud9\c9sdk\node_modules\architect\architect.js:590:9)
    at Architect.emit (events.js:107:17)
    at startPlugins (C:\cloud9\c9sdk\node_modules\architect\architect.js:471:21)
    at startPlugins (C:\cloud9\c9sdk\node_modules\architect\architect.js:476:21)
    at register (C:\cloud9\c9sdk\node_modules\architect\architect.js:507:13)
    at Server.<anonymous> (C:\cloud9\c9sdk\node_modules\connect-architect\connect\connect-plugin.js:135:13)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:104:17)
    at net.js:1171:12
{ [Error: Cannot find module 'sinon']
  code: 'MODULE_NOT_FOUND',
  plugin:
   { packagePath: 'C:\\cloud9\\c9sdk\\plugins\\c9.error\\logger.raygun_mock.js',
     provides: [ 'error.logger' ],
     consumes: [],
     setup: { [Function: plugin] consumes: [], provides: [Object] } } } 'Error: Cannot find module \'sinon\'\n    at Module._resolveFilename (module.js:336:15)\n    at Function.modules._resolveFilename (C:\\cloud9\\c9sdk\\node_modules\\c9\\setup_paths.js:20:12)\n    at Function.Module._load (module.js:278:25)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at Object.plugin [as setup] (C:\\cloud9\\c9sdk\\plugins\\c9.error\\logger.raygun_mock.js:9:17)\n    at startPlugins (C:\\cloud9\\c9sdk\\node_modules\\architect\\architect.js:468:24)\n    at startPlugins (C:\\cloud9\\c9sdk\\node_modules\\architect\\architect.js:476:21)\n    at register (C:\\cloud9\\c9sdk\\node_modules\\architect\\architect.js:507:13)\n    at Server.<anonymous> (C:\\cloud9\\c9sdk\\node_modules\\connect-architect\\connect\\connect-plugin.js:135:13)'

---

**Comment by NNM11** [comment]
@lennartcl - Is this bug fixed?

**Comment by Pike** [comment]
Yep, revision 7a78fa8b4c47200b3bb27e808aab697e65f2d495 fixed it
