### ISSUE TITLE
Add ability to override defaults

### ISSUE THREAD

**Issue by thegecko** [c9/core#138]
Could it be made possible to override default setting values in plugins?

Specifically I want to modify the default value for the hidden file pattern 'user/projecttree/@hiddenFilePattern' while still allowing the user to set a value themselves.

From @javruben 

I'm thinking that you might want to set this only for your workspace, not for all workspaces of this user. So rather than overwriting the global use setting. Why not create a new setting in the `project` config and use that to set: `fsCache.hiddenFilePattern = pattern`.

**Comment by thegecko** [comment]
This could be implemented by having a 'last one set, wins' mentality. So If a plugin wants to override the defaults set in another, it would add the initial plugin as a 'consumes' to guarantee the load order and call 'setDefaults' again.

Technically, the current implementation relies on the fact that an unset user setting is filled in by the defaults. Therefore, this approach would require a way of determining if a value comes from the user or a default setting so an overriding 'setDefaults' only gets set if the setting hasn't already been set by the user.

This could be undertaken by adding a 'default' or 'user' flag to the existing json map as it is initially loaded or by maintaining an in-memory map of the default settings as well as the user settings for comparison.

**Comment by javruben** [comment]
I like the in memory approach. Settings can simply look up the default
value if it's not set. This would make serializing the settings file for
editing a bit more complex. Im willing to accept a PR for this if you have
time. Otherwise please add a feature request for this to the core. Thanks!

**Comment by javruben** [comment]
Just saw this is already on github :)

**Comment by nightwing** [comment]
this have been implemented some time ago https://github.com/c9/core/blob/eb710ca024a492043dab19a6535dc2348eef7bf4/plugins/c9.core/settings.js#L397
