### ISSUE TITLE
Can't launch from zip download

### ISSUE THREAD

**Issue by imatmati** [c9/core#144]
Hi,

After downloading the zip file and running the install-sdk.sh on Windows, I wasn't able to start the server because of this error :
Starting standalone
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\Users\xxxx\core-master.git\HEAD'

Is it runnable without a git installation ?
Have a nice day.

**Comment by nightwing** [comment]
It's not runnable without git, since install-sdk.sh uses git to download subplugins
