### ISSUE TITLE
JS-file is not included in packed mode

### ISSUE THREAD

**Issue by asinyagin** [c9/core#145]
Hey,

C9 in packed mode doesn't include a js-file which is loaded with such code:
```javascript
define(
    ['./b.js'],
    function(b) {
        return b;
    }
);
```
With that code it works as expected:
```javascript
define(['./b.js'], function(b) {
    return b;
});
```
Here's a full example https://github.com/asinyagin/plugin.simple

**Comment by nightwing** [comment]
fixed by https://github.com/c9/core/commit/1de84e810d14d046f260be9eb07c774ca1673f62
