### ISSUE TITLE
NodeJS 4 seg fault when running

### ISSUE THREAD

**Issue by cadorn** [c9/core#147]
I get a segmentation fault when starting latest clone using nodejs 4. install goes fine but will not run.

**Comment by nightwing** [comment]
Does this happen on on mac? If yes it might be because of loading old binary extensions with the new node version
Try `rm -rf node_modules ; git checkout -- node_modules; npm install`

**Comment by cadorn** [comment]
This was on a mac with a fresh install. I Did have --packed specified as well. If it is working for you I can try again.

**Comment by nightwing** [comment]
Confirmed, this is caused by binary modules from ws the command above or simply `find node_modules/ -name *.node -exec echo {} \; -exec rm {} \;` should fix it

**Comment by cadorn** [comment]
Confirmed working with clean install.
