### ISSUE TITLE
File tree view duplicates some files seemingly randomly

### ISSUE THREAD

**Issue by maritz** [c9/core#15]
Disclaimer: Actual files are not duplicated, just visually in the file tree. (as can be seen from the console output in the screenshot)

http://i.imgur.com/lmG2wde.png

I have no idea what causes this or how to trigger it, it seems rather random. Selecting one of those duplicated items even highlights all of them. Refreshing the file tree does not remove the problem, neither does refreshing the browser tab or even restarting the node process.

I removed my .c9 folder and deleted all cookies. Now it seems fine again for now. 

Also, this was under Favorites, not the normal file tree.

Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

c9/core: be54b38a9c
OS: Linux debian-virt 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux   ( not the browser though, that is running on win7)
Node.js: v0.10.36

Any other info I can provide?

**Comment by javruben** [comment]
Interesting. We have never seen this before. What was the path of your favorite? What did you do prior to seeing this?

**Comment by maritz** [comment]
The path was to dev/isommo (and another favorite was to another dir in dev/)

The first time I noticed that happening I was usint CTRL+Z to undo a bunch of changes. Everytime I pressed CTRL+Z a bunch of files appeared in the file tree. But since then it was happening on all kinds of actions and some went away at some points. Not sure really, it was extremely bizarre.

**Comment by javruben** [comment]
What was the *full path* of the favorite?

Can you recall which other actions triggered this behavior?

**Comment by maritz** [comment]
Full path was /home/maritz/dev/isommo/

No, sorry. I was trying to save my work before nuking the .c9 folder to try and fix this. :/

Next time this happens (if ever) I'll make sure to get some more information for you.

**Comment by nightwing** [comment]
this was fixed by https://github.com/c9/core/commit/aa2eaf0ff447617dbc1e34489aef186cd809bc98
