### ISSUE TITLE
can't install sdk ! 

### ISSUE THREAD

**Issue by soitun** [c9/core#150]
[root@host-10-6-132-2 c9sdk]# ./scripts/install-sdk.sh
Already up-to-date.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11193  100 11193    0     0   9658      0  0:00:01  0:00:01 --:--:-- 41609
Error: please install glibc-static to proceed
To do so, log into your machine and type 'yum install glibc-static'

centos 6 64bit

**Comment by nightwing** [comment]
did you try to do what the message asked? `sudo yum install glibc-static`
> please install glibc-static to proceed
> To do so, log into your machine and type 'yum install glibc-static'

**Comment by soitun** [comment]
[root@host-10-6-132-2 c9sdk]# sudo yum install glibc-static
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   No module named yum

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.4 (default, Sep 12 2015, 07:05:45)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

If you cannot solve this problem yourself, please go to
the yum faq at:
  http://yum.baseurl.org/wiki/Faq

**Comment by soitun** [comment]
thanks 
i had installed glibc-static
then reinstall sdk, 

:Installing Nak
npm WARN excluding symbolic link tests/filelist_fixtures/symlink-to-1.txt -> 1.txt
npm WARN excluding symbolic link tests/filelist_fixtures/symlink-to-nowhere.txt -> nowhere.txt
npm WARN excluding symbolic link tests/search_fixtures/symlink-to-file1.txt -> file1.txt
npm WARN excluding symbolic link tests/filelist_fixtures/symlink-to-1.txt -> 1.txt
npm WARN excluding symbolic link tests/filelist_fixtures/symlink-to-nowhere.txt -> nowhere.txt
npm WARN excluding symbolic link tests/search_fixtures/symlink-to-file1.txt -> file1.txt
npm WARN engine simplefunc@0.0.2: wanted: {"node":">= 0.6.0 && < 0.9.0"} (current: {"node":"0.12.6","npm":"2.11.2"})
nak@0.3.3 node_modules/nak
â”œâ”€â”€ simplefunc@0.0.2
â”œâ”€â”€ colors@0.6.2
â””â”€â”€ isbinaryfile@2.0.0

real    0m9.794s
user    0m1.962s
sys     0m0.360s
:Installing pty.js

> pty.js@0.2.8 install /root/.c9/node_modules/pty.js
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCP.onread (net.js:559:26)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/root/.c9/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.c9/node_modules/pty.js
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/root/.c9/node/bin/node" "/root/.c9/node/bin/npm" "install" "pty.js@0.2.8"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.c9/npm-debug.log

**Comment by ho0406** [comment]
I also has error while install c9sdk during Installing pty.js

:Installing pty.js
npm http GET https://registry.npmjs.org/pty.js
npm http 304 https://registry.npmjs.org/pty.js
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/nan

> pty.js@0.2.8 install /root/.c9/node_modules/pty.js
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at errnoException (child_process.js:1000:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:791:34)
gyp ERR! System Linux 3.16.0-4-armmp-lpae
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/.c9/node_modules/pty.js
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! pty.js@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.8 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-armmp-lpae
npm ERR! command "/root/.c9/node/bin/node" "/root/.c9/node/bin/npm" "install" "pty.js@0.2.8"
npm ERR! cwd /root/.c9
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/.c9/npm-debug.log
npm ERR! not ok code 0

**Comment by nightwing** [comment]
Ah, i see you are trying to install it as  root, could you try workaround suggested in https://github.com/c9/core/issues/143#issuecomment-138743539?

**Comment by nightwing** [comment]
fixed by https://github.com/c9/install/pull/60
