### ISSUE TITLE
Aws install path issues

### ISSUE THREAD

**Issue by prstockton** [c9/core#153]
Setup: Aws, Ubuntu 14.04, latest c9 sdk, Node 0.12

Everything installs as expected. 

With: 'node server.js -p 8080 -a :' Plugins can be created.

However launching with 'node server.js -w ~/workspace/ -l 0.0.0.0 --collab -p 8080 -a :' a workspace is created as expected, with a .c9 folder (i can create settings local to the projects which is useful and use the live preview without issues). 

However I cannot create plugins from the file -> new -> menu.

I assume that this is either a path or permissions issue?

I can work around by launching in either of the two ways mentioned above and working on either projects or plugins but his seems odd and I would rather just set the server running and forget about it.

A possibly related workaround: is it possible to create a  workspace from the cli or only at launch - I mean a workspace with a .c9 folder not just a directory. 

Also what dictates the path that the live preview starts from? Is that also dependent on the '- w' flag or is it configurable?

I want to work on plugins and snippets for React but first I want to establish a stable predictable environment. Any help or background would be really appreciated.

Thanks in advance.

**Comment by nightwing** [comment]
plugins are always created in ~/.c9, do you see any errors when creating plugin?

>  I mean a workspace with a .c9 folder not just a directory.

.c9 folder is created automatically when ide is opened, why do you want to create it from cli?

>  Also what dictates the path that the live preview starts from? Is that also dependent on the '- w' flag or is it configurable?

preview path is same as workspace root https://github.com/c9/core/blob/master/plugins/c9.vfs.standalone/standalone.js#L140.

**Comment by prstockton** [comment]
...plugins are always created in ~/.c9, do you see any errors when creating plugin?

Yes, a red dialog box is launched in top right of the workspace with the message 'Cannot create plugin'

**Comment by nightwing** [comment]
Are there related errors in browser devtools or the console from which you run node server.js ?
this most likely can happen if ~/.c9 is not writable

**Comment by prstockton** [comment]
Ok that was my initial assumption either a path or permissions issue. I say this because when i start the server like this 'node server.js -p 8080 -a :'  the plugin folder is created as expected.

When i start like this: 'node server.js -w ~/workspace/ -l 0.0.0.0 --collab -p 8080 -a :' , I get the error as detailed above.

If I am understanding you correctly are permissions dictated by how I launch? In other words I can create plugins only by this 'node server.js -p 8080 -a :' and not this: 'node server.js -w ~/workspace/ -l 0.0.0.0 --collab -p 8080 -a :' 

On the other hand how can I create a workspace directory if I launch like this 'node server.js -p 8080 -a:' ?

Hope that I am making sense. 

Apologies if I am missing something very obvious!

**Comment by prstockton** [comment]
Sorry I didn't answer your response fully:

A plugins folder is created with the _ diectory with a plugin.simple.tar.gz file in it.

There are errors in the dev tools window for example: 

HTTP error 404: 24836: Error: ENOENT, stat '/home/ubuntu/.c9/plugins/'
    at Error (native)

And in the terminal running the server for example:

24836: Error: ENOENT, stat '/home/ubuntu/.c9/plugins/'
    at Error (native)

Hope this helps.

**Comment by prstockton** [comment]
And permissions:

drwxrwxr-x   8 ubuntu ubuntu  4096 Sep 14 12:48 .c9/

**Comment by prstockton** [comment]
Ok my screw up or at least it seems to work now :)
