### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by 6api** [c9/core#156]
i clone from master, in finaly, got error, how can i fix this?

From https://github.com/c9/c9.ide.welcome
- [new branch]      master     -> origin/master
  HEAD is now at 08bca78 don't make help depend on welcome plugin
  /usr/local/cloud9
  --- Running npm install --------------------------------------------
  npm ERR! Linux 3.2.0-4-amd64
  npm ERR! argv "/root/.c9/node/bin/node" "/root/.c9/node/bin/npm" "install"
  npm ERR! node v0.12.6
  npm ERR! npm  v2.11.2
  npm ERR! path /root/.c9/tmp/.npm/registry.npmjs.org/base64id/.cache.json.e97d1c238356d6adcedda8bb5be3ea90
  npm ERR! code ENOENT
  npm ERR! errno -2

npm ERR! enoent ENOENT, chown '/root/.c9/tmp/.npm/registry.npmjs.org/base64id/.cache.json.e97d1c238356d6adcedda8bb5be3ea90'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/cloud9/npm-debug.log
acorn
## acorn@2.4.0 node_modules/acorn

Success!
run 'node server.js -p 8080 -a :' to launch Cloud9

**Comment by nightwing** [comment]
try running npm install from comman dline
