### ISSUE TITLE
Cloud9 running as Ubuntu instance in AWS

### ISSUE THREAD

**Issue by praneethkumarpidugu** [c9/core#159]
Hi Everyone, 
I have cloud9 application running in the Ubuntu instance at AWS. Platform is running successfully but I have an issue using a nodejs application in a preview GUI of cloud9. Here is a problem explained as below:

Cloud9:
root@blahblahinstance:/projectdirectory# node example.js
Example app listening at http://0.0.0.0:3000

But when I try to hover and click on the localhost above mentioned I get as following:-
![browser problem for nodejs](https://cloud.githubusercontent.com/assets/10872354/10001494/00b465ec-6070-11e5-819a-49e353bec844.PNG)

Does Cloud9 running in Ubuntu Instance at AWS has GUI accessibility ?

**Comment by nightwing** [comment]
Change 0.0.0.0 to the hostname of your AWS server.
