### ISSUE TITLE
Problem with terminal on nodejs v0.12.0

### ISSUE THREAD

**Issue by alessioguglielmo** [c9/core#16]
I've updated nodejs 0.12.0 from latest official packages. I cleaned up install directory and replaced it running a new installation from scratch.
Installation succeeded, but now terminal isn't loaded and shows only a square char.

**Comment by alessioguglielmo** [comment]
ok, I've read the support is limited to v. 0.10
However, any news about 0.12 ?

**Comment by javruben** [comment]
We are working on 0.12 support. As a policy we don't make promises on release dates.

**Comment by alessioguglielmo** [comment]
ok, for now the version 0.10.8 may be fine?
I've 0.10.25 and I had problems with plugin implementation and SDK said to me that version had to be updated

**Comment by javruben** [comment]
I am using v0.10.28. I would recommend that version.

**Comment by alessioguglielmo** [comment]
Ok, I took note of this.

**Comment by BTBlueSkies** [comment]
I am going to be actively setting this up in the near term. I also was able to get this running on the same version of nodejs, 0.10.28 on a rasp pi, arm 6, and it is mostly behaving, but not completely. I have comments but mostly this is a hello message. Love your project.

**Comment by javruben** [comment]
@BTBlueSkies Hi!

@alessioguglielmo Colleagues have been using the latest Node 0.10 with success.

**Comment by javruben** [comment]
Related: https://github.com/chjj/pty.js/issues/103

**Comment by nightwing** [comment]
node  0.12 should work fine starting from https://github.com/c9/core/commit/e45d34e881434723bb7167ffdafac0838547af85 commit

**Comment by isc30** [comment]
I use 0.10.28 and terminal (pty.js) isnt compiling :(
Is the only thing crashing, the rest is perfect

**Comment by isc30** [comment]
With v0.10.36 it works 100%

**Comment by alessioguglielmo** [comment]
I'm working on node 0.12 and seems it works very well.

2015-03-20 0:03 GMT+01:00 isc30 <notifications@github.com>:

**Comment by isc30** [comment]
Wow, really? they said they were worjing in 0.12.x support

**Comment by alessioguglielmo** [comment]
```
root@bf451ba7281c:~/c9sdk# node -v
v0.12.0
root@bf451ba7281c:~/c9sdk#
```

terminal is quite stable


2015-03-20 11:08 GMT+01:00 isc30 <notifications@github.com>:

**Comment by nightwing** [comment]
@isc30 see https://github.com/c9/core/issues/16#issuecomment-80442117
@alessioguglielmo thanks for testing it with 0.12
