### ISSUE TITLE
Upstart on Raspberry Pi gives error "arguments to path.join must be strings"

### ISSUE THREAD

**Issue by chintanp** [c9/core#165]
Question also here; http://askubuntu.com/questions/679345/debugging-upstart-script-for-nodejs-process 

Cloud9 starts with 'forever' but errors from inside Upstart. 

Specific line in upstart script: 

```
exec forever start /home/pi/c9sdk/server.js -l 0.0.0.0 -w / -a :
```

gives an error "arguments to path.join must be strings".

**Comment by nightwing** [comment]
This happened because $HOME environment variable wasn't set, i'll add an assert for that to make debugging issues like this easier
