### ISSUE TITLE
Navigate shows "No files found" 

### ISSUE THREAD

**Issue by jmarbutt** [c9/core#170]
I am running c9 with the following command on OS X v10.10.5.

build/Cloud9-dev.app/Contents/MacOS/node-webkit -w /Users/jonathan/documents/myproject --packed --no-devtools

It also does not show the files from the path. I have tried also just running:

build/Cloud9-dev.app/Contents/MacOS/node-webkit

And just dragging the folder in and it still doesn't show the files in the Navigate tab. Any ideas why?

**Comment by nightwing** [comment]
-w isn't really supported in local version
run without -w and add myproject folder to favorites

**Comment by jmarbutt** [comment]
Yeah I tried it by adding it to the favorites and still doesn't work. That is how i did it the second half of the question

**Comment by nightwing** [comment]
Sorry i misunderstood second half of your question.

Do you see any failed requests in network tab of devtools? List of files for navigate comes from a request to file.listing url which should be something like `http://localhost:2222/vfs/2/<...>/home/.c9/file.listing?pathToNakignore=<...>`

**Comment by nightwing** [comment]
This issue should be fixed by https://github.com/c9/core/commit/ee7678045beaf2739c3e9678096fd4d450eab9a4, please let me know if you still see the error with the latest master
