### ISSUE TITLE
Any trick to speed up installation?

### ISSUE THREAD

**Issue by Ventajou** [c9/core#18]
I tried installing on an Ubuntu 14.04 VM the other day, the install script worked well and I was able to get everything working. But it was painfully slow... is there something I could do to speed things up? Any plan to have Docker images maybe?

**Comment by eazel7** [comment]
git pull eazel7/c9-v3
map the guest /workspace folder =)

**Comment by eazel7** [comment]
I haven't set up any hook to all github.com/c9/* repository, I will do soon

**Comment by javruben** [comment]
You might want to check out https://github.com/mingfang/docker-cloud9. 

Please make sure you are aware of our licenses: http://cloud9-sdk.readme.io/v0.1/docs/the-licenses-for-cloud9-sdk-and-packages and contact support@c9.io if you want to deploy to multiple users.

**Comment by poliveira89** [comment]
@javruben Hello, thanks for the protip :+1: Why C9 team didn't push a image of their own to Docker Hub? 

For me that, I was looking for one (now). It would be more reliable to pull one of yours! I have already saw the one you shared, but isn't on Docker Hub.
