### ISSUE TITLE
[plugin dev] `c9 --verbose publish 0.0.1 --force` Not working

### ISSUE THREAD

**Issue by cadorn** [c9/core#182]
````
$ c9 --verbose publish 0.0.1 --force
WARNING: The name property in package.json is not equal to the directory name, which is cloud9
WARNING: README.md is missing.
````

Then it stops. What is supposed to happen? I don't see the plugin in the list of published plugins.

**Comment by cadorn** [comment]
$feature https://github.com/devcomp/0.devcomp-for-cloud9/issues/1

**Comment by nightwing** [comment]
Looks like it doesn't handle missing Readme.md in https://github.com/c9/core/blob/master/plugins/c9.cli.publish/publish.js#L280, add readme.md to publish

**Comment by nightwing** [comment]
Fixed in https://github.com/c9/core/commit/fac2e66d39e9005ed4f52092ba6399046819d033
