### ISSUE TITLE
Ignore file to trim files from filetree

### ISSUE THREAD

**Issue by cadorn** [c9/core#183]
$feature https://github.com/devcomp/0.devcomp-for-cloud9/issues/1

It would be very handy to be able to add a file (like `.gitignore`) to the root of a workspace to ignore files/paths from showing up in the file tree.

It could be called something like `.editignore`.

Assuming there is interest, how would I go about adding a filter to the filetree loading code? Do you have an existing ignore file scanner I an use? I have a recursive one (supports ignore files in sub-directories) if not.

**Comment by nightwing** [comment]
We have hiddenFilePattern setting for this https://github.com/c9/core/blob/master/plugins/c9.ide.tree/tree.js#L124.

**Comment by cadorn** [comment]
Alright. I can feed that from the ignore file.
