### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by magne4000** [c9/core#185]
Is there a way with current version to choose explicitelly Python 3 as python interpreter/syntax checker instead of Python 2 ?

**Comment by Pike** [comment]
For inspiration: https://github.com/AtomLinter/linter-pylint/pull/24

The code in question is actually in https://github.com/c9/c9.ide.language.jsonalyzer/blob/master/server/handlers/jsonalyzer_py_server.js, and doesn't offer a switch yet.
