### ISSUE TITLE
configure: error: "curses not found"

### ISSUE THREAD

**Issue by clemenko** [c9/core#19]
configure: error: "curses not found" when installing on centos 7. Is this a known issue?

[root@play c9sdk]# rpm -qa|grep curse
ncurses-libs-5.9-13.20130511.el7.x86_64
ncurses-5.9-13.20130511.el7.x86_64
ncurses-devel-5.9-13.20130511.el7.x86_64
ocaml-curses-1.0.3-17.el7.x86_64
ncurses-base-5.9-13.20130511.el7.noarch
ocaml-curses-devel-1.0.3-17.el7.x86_64
is installed.

**Comment by javruben** [comment]
This is not a known issue.
This issue would be best placed in this repo: https://github.com/c9/install/issues

Curses is used to compile tmux. If tmux is installed via a package it is not compiled. May I suggest to install tmux via rpm to prevent this error?

**Comment by javruben** [comment]
This is now fixed. See https://github.com/c9/install/issues/24#issuecomment-77268744

**Comment by joshuatam** [comment]
Just tried to install, seems I have to install glibc-static too

**Comment by wadeziegler** [comment]
This is not fixed or is broken again.

**Comment by ajaygh** [comment]
simply install ncurses-dev on ubuntu by sudo apt-get install ncurses-dev

**Comment by ordinaryparksee** [comment]
I solved by installing glibc-static

**Comment by mengdodo** [comment]
楼上的完美解决了我的问题，thanks，我的环境是centos6.5

**Comment by xluohome** [comment]
yum install glibc-static

**Comment by ygeo** [comment]
# if you are on GentOs or RH
sudo yum install ncurses-devel

**Comment by MyKings** [comment]
sudo yum install ncurses-devel glibc-static

**Comment by leipzig** [comment]
`sudo yum install tmux.x86_64` on rhel7

**Comment by pjbrunet** [comment]
CentOS 6 here, thanks @MyKings that's what I needed.

**Comment by sammysosa12** [comment]
have anyone tried this on kali linux im having a hard time getting ncurses on there . has anyone have this problem?

**Comment by jppgks** [comment]
Or, build ncurses from source when you don't have root access (using `--prefix` to specify an install directory other than `/usr/local/bin`)

1) Install [ncurses](https://ftp.gnu.org/pub/gnu/ncurses/)
```shell
# Download & extract source (anywhere)
wget https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.1.tar.gz
tar -xvf ncurses-6.1.tar.gz
cd ncurses-6.1
# Install
./configure --prefix=$WORKSPACE
make
make install
```

2) Set CFLAGS to include ncurses directory when building another program.
```shell
./configure --prefix=$WORKSPACE \
  CFLAGS="-I$WORKSPACE/include -I$WORKSPACE/include/ncurses" \
  LDFLAGS="-L$WORKSPACE/lib"
```
