### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by daedalus28** [c9/core#195]
The readme mentions that c9 requires node 0.10 or 0.12 - is that just out of date, or are there known issues on node 4?

**Comment by nightwing** [comment]
no knows issues. 0.10.28+ works

**Comment by daedalus28** [comment]
Awesome - can we update the readme file (and then close this)?

Happy to submit a pull request for it but it seems pretty trivial :)

**Comment by nightwing** [comment]
Updated the readme in https://github.com/c9/core/commit/69dc5d0ee730a308d6e62daf171de26727498753
