### ISSUE TITLE
User specific settings?

### ISSUE THREAD

**Issue by dubcanada** [c9/core#2]
Hello,

I understand if I install it on my server if I have 5 people using it, at least as far as C9 is concerned all 5 of those people are the same user.

I'm wondering if there is a way to have one install, but 5 users?

**Comment by javruben** [comment]
Hi,

Please read http://cloud9-sdk.readme.io/v0.1/docs/the-licenses-for-cloud9-sdk-and-packages.

The SDK is intended for developing plugins and for your own use. It is not made for multiple people using it. For that I recommend using c9.io. Alternatively, each user can set up the SDK themselves and use their running instance for themselves.
