### ISSUE TITLE
Missing and incorrect properties for the Workspace ace_tree nodes

### ISSUE THREAD

**Issue by andrewfaulring** [c9/core#200]
The nodes that represent files, folders, and headings in the Workspace sometimes are missing properties or have properties with incorrect values. Most of the relevant Cloud9 IDE code is

* plugins/c9.fs/fs.cache.xml.js
* node_modules/ace_tree/lib/ace_tree/data_provider.js

As best I can tell there is no class or module implementing the ace_tree nodes. Instead, the above files create the node objects with different and inconsistent properties.

Open the Workspace context menu and select "New File". The node for the newly created file contains the following properties:

	{
	  "$depth": 1,
	  "children": null,
	  "isOpen": true,
	  "isSelected": true,
	  "label": "Untitled",
	  "parent": "[object] ...",
	  "path": "/Untitled",
	  "status": "loaded"
	}

Reload the Cloud9 IDE. The same node now has these properties:

	{
	  "$depth": 1,
	  "children": null,
	  "contenttype": "application/octet-stream",
	  "isFolder": false,
	  "isSelected": true,
	  "label": "Untitled",
	  "mtime": 1446156336643,
	  "parent": "[object] ...",
	  "path": "/Untitled",
	  "size": 0,
	  "status": "loaded"
	}

Before reloading the IDE, the node was missing the "contenttype", "isFolder", "mtime", and "size" properties. Also the pre-reloading node has unnecessary "isOpen" property set to true, which is wrong for files.

The same issue occurs when the user creates a new document and then saves it. Although in this case, the node does not have the invalid "isOpen" property.

The problem appears to be in part caused by the addSingleNode() function (fs.cache.xml.js#L203), which calls createNode() with a null "stat" parameter. The "isOpen" property is set when the expand() function (data_provider.js#L52), called with the new "Untitled" node, calls setOpen() on L77.

A similar problem occurs when creating a new folder: the "mtime" property is missing. The "size" property is also missing; although that's not a really meaningful property for folders.

Additionally, the "workspace" (path = "/") node is initially missing the mtime and size properties. The fsCache is also missing these properties. By initially missing, I mean shortly after the tree's "ready" event is emitted. A few milliseconds later the properties are loaded and the tree.tree.provider.on("change", ...) listeners are called. Note that the workspace tree node.status property is "loaded".

**Comment by javruben** [comment]
@andrewfaulring What would you like to see?
