### ISSUE TITLE
undefined preview url on localhost standalone instance

### ISSUE THREAD

**Issue by chetanameta** [c9/core#201]
I configured Cloud9 at Ubuntu 14.04. Its running perfectly. But when I am clicking on "Preview Running Application" its opening an iframe with https://undefined/

I tried to change domains from config file, but still no success.

Can any one help me where I need to set preview URL or what i did wrong, while editor working perfectly with all programming languages.

While debugging it i got to know e.url is undefined at line number 275 in plugins/c9.ide.preview.browser/browser.js file.

Here is code of plugin: 

    plugin.on("navigate", function navigate(e) {
            var tab = plugin.activeDocument.tab;
            var session = plugin.activeSession;
            var iframe = session.iframe;
            if (!iframe) // happens when save is called from collab see also previewer navigate
                return;

            var nurl = e.url.replace(/^~/, c9.home);
            var url = nurl.match(/^[a-z]\w{1,4}\:\/\//)
                ? nurl
                : BASEPATH + nurl;

            var base = (session.url || "").split("#")[0];
            if (url.indexOf(base + "#") == -1 && url != base)
                tab.classList.add("loading");
            session.url = url;

here value of e.url is "https://undefined"

Can you help me to resolve this issue, is there any settings in config file to get rid of this issue?

**Comment by nightwing** [comment]
The code for starting the preview is at https://github.com/c9/c9.ide.preview/blob/master/preview.js#L195
and it is configured by
https://github.com/c9/core/blob/master/configs/client-default.js#L561 and
https://github.com/c9/core/blob/master/settings/standalone.js#L34

Preview running app menu is useful when running on c9.io, but isn't very useful for standalone version, which url do you expect it open?

An easy solution is to change line https://github.com/c9/c9.ide.preview/blob/master/preview.js#L195 to `var hostname = c9.hostname || "localhost:8080";`

**Comment by chetanameta** [comment]
@nightwing thank you for your response. It solves my problem. It is working fine now.

**Comment by juanitomint** [comment]
@nightwing is there a way for overriding c9.hostname via project.settings or somewhere in the .c9 folder?

**Comment by nightwing** [comment]
there is no way to change c9.hostname, but we can add one, how do you want to use it?
