### ISSUE TITLE
How execute two and more wokspaces?

### ISSUE THREAD

**Issue by khusamov** [c9/core#206]
Or switch between different workspaces through the GUI cloud9?

**Comment by khusamov** [comment]
found his solution to the issue https://cloud9-sdk.readme.io/docs/running-cloud9-desktop

**Comment by orditeck** [comment]
I created a little web app for this. You can [access it here: orditeck/c9ui on github](https://github.com/orditeck/c9ui)

![c9ui](http://i.imgur.com/BSbwbfh.jpg)

**Comment by ALiangLiang** [comment]
I also create a nodejs version of [c9ui](https://github.com/orditeck/c9ui). Named [cloud9 launcher](https://github.com/ALiangLiang/cloud9-launcher/). Everyone can try my version if you are not familiar with PHP environment. It's similar to @orditeck 's c9ui. :)
