### ISSUE TITLE
How to translate the c9 

### ISSUE THREAD

**Issue by soitun** [c9/core#209]
hello ,How to translate the c9 ui to other language,

**Comment by nightwing** [comment]
There is no support for this yet.

For buttons and menus we can add a hook in caption handler, and use an object mapping english name to a translated name.

**Comment by Pike** [comment]
I'd suggest to go for a full-fledged l10n infrastructure, though apf doesn't make that easy.

Replacing English strings by a text match sadly has it's downsides, with English being as ambiguous as it is "View" being both noun ad verb, with many others.

In addition, there are a lot of pixel numbers throughout the c9 code base, not sure how many of those are matching particular string lengths. Panel widths come to mind, at least.

@soltun, are there particular languages and use cases you have in mind?
