### ISSUE TITLE
when will v3 support the arm platform？

### ISSUE THREAD

**Issue by silverPanda** [c9/core#21]
I am expecting it can be installed on my Raspberry Pi

**Comment by javruben** [comment]
There have been some recent changes to the [installation script](https://github.com/c9/install) that should have made it work for multiple ARM architectures. If you have any problems, I suggest to open a ticket in the linked repo to find a solution.

**Comment by silverPanda** [comment]
I will try it, thx :+1:

**Comment by portokallidis** [comment]
I confirm that it runs on a raspberry pi 2. I run the ubuntu 14 image, i had some problems with the language but once you reset the locales they are ok.
