### ISSUE TITLE
IDE becomes unresponsive after 'Find in Directory'

### ISSUE THREAD

**Issue by ggoodman** [c9/core#211]
Installed `./scripts/install-sdk.sh` (and running using `./scripts/setup-local-dev.sh` from a2076315117b2a2c0e729c8a271fb69ac55d7862.

Initiating a 'find files in directory' results in the following symptoms:
* Find spinner spins without finding anything
* Attempting to open files from the sidebar results in blank code tabs with spinning load indicators

Exiting and killing node processes resolves the inability to open files.

**Comment by nightwing** [comment]
Does this depend on size of the directory or the pattern searched? Could you test with `node server.js`?

**Comment by ggoodman** [comment]
The issue is not reproduced when running the server. I tested on `c9sdk/node_modules` by searching for require.

Also worth noting that whereas the find hyperlinks in the _server_ mode result in navigating to the right line of the right file, the same thing in the _local_ mode results in the finder sidebar being shown with the absolute path having my home dir replaced by ~: `/~/Projects` instead of `/home/ggoodman/Projects` (note the leading `/`). Obviously the ide fails to navigate to these (incorrect) paths.

**Comment by ggoodman** [comment]
Update: Saving some files just takes around 40 seconds. The close button becomes the orange circle and I need to wait for `vfs` or whatever to catch up.

**Comment by ggoodman** [comment]
I'm getting tons of messages like this: `Failed to write to '<span title='/Users/ggoodman/.c9/windows/1-state.settings'>1-state.settings</span>'. Timeout.`

**Comment by ggoodman** [comment]
Maybe these screen captures can help:

Network tab:
![image](https://cloud.githubusercontent.com/assets/50030/11094961/c1107296-8860-11e5-8177-a0cfd073d1cf.png)

Console:
![image](https://cloud.githubusercontent.com/assets/50030/11094987/dc9e40f6-8860-11e5-868d-f8b485b18c6d.png)

**Comment by nightwing** [comment]
what is using port 2222? maybe there is another instance of cloud9 server stuck?

**Comment by ggoodman** [comment]
I seem to have been able to fix this by nuking a bunch of my config files. Perhaps it was the fact that I was forcing `zsh` as `TERM`?

**Comment by nightwing** [comment]
I remember there were reports about the old version of pty.js using 100% cpu in some cases, perhaps forsing zsh triggered something similar. Whic version of pty js is installed in ~/.c9/node_modules/ ?
