### ISSUE TITLE
In the terminal, it is impossible to gain line with Russian letters, bug?

### ISSUE THREAD

**Issue by khusamov** [c9/core#212]
![1](https://cloud.githubusercontent.com/assets/4146998/11097796/4592be9c-88b2-11e5-83bd-8b8d92176dba.PNG)

But on the site c9.io terminal Russian letters work. As well?

![2](https://cloud.githubusercontent.com/assets/4146998/11097803/4cede414-88b2-11e5-98a1-22036ad38f9a.PNG)

**Comment by nightwing** [comment]
LOCALE setting might be misconfigured on the first machine.
Is the first  image taken on windows?

**Comment by khusamov** [comment]
OS = Windows

**Comment by khusamov** [comment]
Local settings of the operating system or c9core?

**Comment by nightwing** [comment]
LOCALE of msys1 used by c9core https://github.com/cloud9ide/sdk-deps-win32/tree/master/msys
This is taken from old git version where utf8 wasn't supported, i think it was fixed in the new version.

**Comment by khusamov** [comment]
Can I fix this myself? Or should I wait for some updates?

**Comment by nightwing** [comment]
Do you have another working installation of msys? If yes you can add it to the path before launching server.js to make c9 use that instead.

**Comment by khusamov** [comment]
I installed msys

`curl -L https://raw.githubusercontent.com/cloud9ide/sdk-deps-win32/master/install.sh | bash`

But how to set the path to it I did not understand.  
In what file is stored path to msys?

**Comment by khusamov** [comment]
In Mac OS the same mistakes with the Cyrillic alphabet

![2015-11-17 22 29 37](https://cloud.githubusercontent.com/assets/4146998/11222295/b8a25506-8d7a-11e5-9ae5-3c5ab9f4e801.png)

**Comment by nightwing** [comment]
msys from sdk-deps-win32 doesn't support utf8, i still didn't find how to fix it.

Mac issue is not related to this.
Does Cyrillic work in terminal.app on mac?

**Comment by khusamov** [comment]
> Does Cyrillic work in terminal.app on mac?
Yes!

**Comment by nightwing** [comment]
This should be fixed now  since we use msys2 on windows, and for tmux into unicode mode by passing -u flag, please let us know if you still experience issues with unicode support.
