### ISSUE TITLE
Jump to definition not working

### ISSUE THREAD

**Issue by orditeck** [c9/core#215]
Hi,

Is it normal that I can't "Jump to definition" using c9/core installed on my VPS? I tried with different projects (workspaces) / languages. Is it deactivated because I'm on the "opensource" version? Or do I need to add/activate a plugin? Or maybe I need to add an argument while starting `server.js`?

![](http://i.imgur.com/aYhOO5i.jpg)

Thanks for any help!

**Comment by nightwing** [comment]
"Jump to definition" works the same way on c9.io and the sdk.
Probably the definition is somewhere that language analysis couldn't find, or the language is not supported.

**Comment by orditeck** [comment]
PHP wouldn't be supported? Even on c9/core itself 'Jump to definition' doesn't work.

**Comment by nightwing** [comment]
Yes php is not supported, but it should work for javascript.
If it doesn't work for something simple like

```js
var a
a
```

then there must have been an error while installing the sdk.

**Comment by orditeck** [comment]
Yes you're right, my bad. Any ETA when PHP will be supported?

Awesome work btw!

**Comment by orditeck** [comment]
ping @nightwing

**Comment by nightwing** [comment]
@orditeck i don't have any ETA for PHP jump to definition support. Work on that is not planned for next few months.

**Comment by orditeck** [comment]
Thanks @nightwing, I'll keep looking around until PHP is supported!
