### ISSUE TITLE
Option does not work «--packed»

### ISSUE THREAD

**Issue by khusamov** [c9/core#217]
#### Option does not work `--packed`

Blockquote from page: https://cloud9-sdk.readme.io/docs/running-cloud9-desktop

> Pass --packed and --no-devtools arguments to cloud9 executable to load client in packed mode and not open devtools on startup.

OS Windows 10.

Command line:

`C:\Users\khusamov\cloud9sdk\build\win32-dev\bin\Cloud9.exe --packed --no-devtools`
#### Screenshot:

![default](https://cloud.githubusercontent.com/assets/4146998/11210031/31dd7f26-8d36-11e5-9db1-c8369842c24f.PNG)

**Comment by nightwing** [comment]
This have been fixed some time ago, please comment if you still see a bug with --packed mode.
