### ISSUE TITLE
TMUX 2.1 (now default in homebrew) breaks Run pane.

### ISSUE THREAD

**Issue by ggoodman** [c9/core#219]
See c9/install#56 for more details.

**Comment by nightwing** [comment]
Thanks for reporting this regression.

Workaround until we have a proper solution:
comment out "c0-change-trigger" line at https://github.com/c9/core/blob/master/node_modules/vfs-local/localfs.js#L1844

**Comment by ggoodman** [comment]
@nightwing I continue to have this manual change in `vfs-local`. Are you likely to incorporate the fix anytime soon?

**Comment by nightwing** [comment]
The fix is in a pull request now.
