### ISSUE TITLE
Workspace not loading

### ISSUE THREAD

**Issue by primableatom** [c9/core#22]
I did
git clone git@github.com:c9/core.git c9sdk
cd c9sdk
scripts/install-sdk.sh

on visiting http://0.0.0.0:8181 the workspace isn't loading
I get an error:

{ [Error: ENOENT, no such file or directory '/home/anupbiswal/.c9/user.settings']
  errno: 34,
  code: 'ENOENT',
  path: '/home/anupbiswal/.c9/user.settings',
  syscall: 'open' }
{ [Error: ENOENT, no such file or directory '/home/anupbiswal/Projects/open_source/c9sdk/.c9/project.settings']
  errno: 34,
  code: 'ENOENT',
  path: '/home/anupbiswal/Projects/open_source/c9sdk/.c9/project.settings',
  syscall: 'open' }
{ [Error: ENOENT, no such file or directory '/home/anupbiswal/Projects/open_source/c9sdk/.c9/state.settings']
  errno: 34,
  code: 'ENOENT',
  path: '/home/anupbiswal/Projects/open_source/c9sdk/.c9/state.settings',
  syscall: 'open' }

Having no clue I created those settings file manually in the desired locations now the error is gone BUT I am still not able to see my workspace loaded

I think I am missing something. Can somebody help here.

**Comment by javruben** [comment]
Those errors always happen the first time you start. They are not fatal. Note that you cannot visit 0.0.0.0. That address means "all addresses bound to any network interface". Try localhost:8181.

**Comment by primableatom** [comment]
yeah... I re ran the install-sdk.sh again and it worked. Thanks

**Comment by 00christian00** [comment]
I have the same error and cannot make it to load.
I tried using node version 0.10.36 and 0.12. Tried upgrading libc from 2.13 (that was the only error) to 2.21.
All I see is the loading screen and the same error as above no matter how many times I reinstall it or restart it.

**Comment by nightwing** [comment]
Sorry there was a regression which is fixed now, please try again.

**Comment by 00christian00** [comment]
It works now thanks!
