### ISSUE TITLE
Add a new extension for an existing language

### ISSUE THREAD

**Issue by etopian** [c9/core#220]
Is it possible to add a new extension for an existing language. For instance Drupal uses .module extension for what is essentially a PHP file. So is there a way to get a PHP file with a .module extension to syntax highlight properly?

**Comment by nightwing** [comment]
Changing language mode from the statusbar for unknown file extension permanently associates it with the selected language.

But `module` doesn't seem to conflict with extensions used by other languages so i can add it to the default list of file extensions is at https://github.com/c9/core/blob/master/node_modules/ace/lib/ace/ext/modelist.js#L128.

**Comment by etopian** [comment]
Thanks.
