### ISSUE TITLE
frontdoor is not a dependency in package.json

### ISSUE THREAD

**Issue by elopio** [c9/core#222]
frontdoor is not listed as a dependency in the package.json file. I see it's required in multiple files, so I think this is a bug and it should be added.

**Comment by nightwing** [comment]
It is included in the repo instead, see https://github.com/c9/core/tree/master/node_modules/frontdoor.

**Comment by elopio** [comment]
Right, got it. For some reason my scripts are not finding the c9/node_modules. /me digs more.
Thanks.

**Comment by nightwing** [comment]
Did you run https://github.com/c9/core/blob/master/scripts/install-sdk.sh?

**Comment by elopio** [comment]
I did, but now I don't want anything to end in ~/.c9. I want to make a self-contained dir with all the required bins and libs. So like install-sdk, but specifying the install dir.
