### ISSUE TITLE
Cant open file with name Banner.php

### ISSUE THREAD

**Issue by belovanton** [c9/core#225]
c9ide cant open file with name Banner.php, I use Version 3.1.724 (0721237981) please tell me what logs u need to check this?

**Comment by nightwing** [comment]
Any logs with errors (either from browser console and from server.js)
Also a description of what you are doing, cliking on file name in the tree, using navigate, using c9 open etc.

**Comment by belovanton** [comment]
https://dpaste.de/59ec - log
https://dpaste.de/dvXe - errors
I make file in / with name Banner.php after trying to open it and get http://joxi.ru/eAOBQps4xZyw2o
If I rename file its open normal.

**Comment by nightwing** [comment]
Something rewrites request to `http://ide.tvoe.kt-team.de/vfs/1/<token>/workspace/Banner.php` before cloud9 server receives it.

**Comment by belovanton** [comment]
xD, it was AdBlock extension.
