### ISSUE TITLE
HTTPS support for C9

### ISSUE THREAD

**Issue by adithyau** [c9/core#229]
Hello 

First of all thanks to for the superb cloud IDE :)

I want to enable HTTPS support for the IDE. i.e, load the C9 IDE in HTTPS mode
I tried a lot searching for options/settings to do so but I am not able to find any such option :(
I did find some crt/key settings in one of node modules but no sure how to pass the values to them.

Is there any way to enable HTTPS for c9 IDE ? I have the .crt and .key files ready but don't know how to configure the server.js/standalone config file to use HTTPS.

**Comment by flackr** [comment]
I'm not sure what the proper way to pass the options through is (i.e. it seems like you should be able to set these in config.secure in settings/standalone.js but I was unable to get this working), but I was able to hack this in by adding the following to `node_modules/connect-architect/connect/connect-plugin.js`:

At the top of the file add the following includes:
```javascript
var fs = require("fs");
var constants = require("constants");
```

Immediately before the check `if (options.secure) {` add the following to set this setting:
```javascript
options.secure = {
    ca: fs.readFileSync('/path/to/ca.crt'),
    key: fs.readFileSync('/path/to/secret.key'),
    cert: fs.readFileSync('/path/to/cert.crt'),
    dhparam: fs.readFileSync('/path/to/dh2048.pem'),
    ciphers: 'AESGCM:ECDH:HIGH:!DH:!RSA+AESGCM:!kSRP:!kPSK:!DSS:!RC4:!eNULL:!ADH:!AECDH:!EXPORT:!MD5:@STRENGTH',
    secureProtocol: 'SSLv23_method',
    secureOptions: constants.SSL_OP_NO_SSLv3 | constants.SSL_OP_NO_SSLv2,};
```

**Comment by rmp135** [comment]
I realise this is a fairly old issue but I figured others could benefit from a solution.

You can add https support by modifying the /configs/standalone.js file.

First, import the `fs` module.

Then, find the `plugins` array and add the following to where the `packagepath` is "connect-architect/connect".

```javascript
secure: {
  key: fs.readFileSync('/path/to/key.pem'),
  cert: fs.readFileSync('/path/to/cert.pem')
}
```

**Comment by nightwing** [comment]
added in https://github.com/c9/core/commit/2c70bda49819a23a67426342744a8e9614852201
