### ISSUE TITLE
Require(node module) for plugin development

### ISSUE THREAD

**Issue by FAGundum** [c9/core#23]
I am currently developing a plugin which reads in code and perform some customized syntax analysis.

I was trying to use 'esprima' and 'escope' for my plugin to convert code to AST and then perform scope analysis. Just wondering is there any ways that I could require external node modules like 'esprima' or 'escope' in my plugin? Because currently, it seems the plugin only have access to all sorts modules provided by other plugins.

**Comment by FAGundum** [comment]
Some of the codes for reference

```javascript
define(function(require, exports, module) {
    
    main.consumes = ["Plugin", "commands", "tabManager", "run"];
    main.provides = ["rating"];
    return main;

    function main(options, imports, register) {
        
        //var opt = "/home/derek/nvm/v0.10.28/lib/node_modules";
        
        var Plugin = imports.Plugin;
        var commands = imports.commands;
        var tabs = imports.tabManager;
        var run = imports.run;
        var settings = imports.settings;
        var save = imports.save;
        var esprima = require("./esprima.js");
        //var estraverse = require('estraverse');
        var escope = require('./escope.js');
```

**Comment by FAGundum** [comment]
The require statement will cause error because those modules are not provided in defined.

**Comment by lennartcl** [comment]
You can use require() for normal client-side dependencies, but for node-style modules, you need something like browserify to wrap then in a way they can be imported in the client. Note that escope appears to already have a gulp command for this at https://github.com/estools/escope/blob/548ba8b390215a29dea065fe096e20665ff98444/gulpfile.js#L82. It should be possible to do something similar with esprima. Another thing you could have a look at is our eslint plugin, which includes a browserified version of eslint (https://github.com/c9/c9.ide.language.javascript.eslint/blob/master/worker/eslint_browserified.js). eslint includes esprima and estraverse. I'm not sure you can directly use them from there, but it's worth taking a look at anyway as it shows some patterns for doing syntax analysis. The docs at https://docs.c9.io/api/#!/api/language provide some more background on this topic.

**Comment by javruben** [comment]
@FAGundum Did @lennartcl's answer help you? Can this issue be closed?

**Comment by FAGundum** [comment]
Hi @javruben and @lennartcl , thanks for the answer. The issue can be closed.

**Comment by FAGundum** [comment]
Hi, @lennartcl , actually I have one more issue related to browserify.

Once I have browserified, say for example, https://github.com/estools/escodegen. I use the escodegen.browser.js provided by them. It basically bundled a couple of scripts together, including esutils, estraverse, escodegen etc....

When I require this browserified script in my plugin, 

```javascript
var escodegen = require('./escodegen.browser');
```

The rendered escodegen variable is not a escodegen object, in fact, it is rendered to be a estraverse object. My guess is that the require function is not able to recognize escodgen object in escodegen.browser.js, instead it takes the last defined object in the file. (in this case, it happened to be estraverse)

This also happened to escope once I browserified it.

One screenshot of my debug window.

![screenshot from 2015-03-16 00 32 56](https://cloud.githubusercontent.com/assets/2240381/6656908/27744d28-cb74-11e4-9360-58c6268ac109.png)

Just wondering, how can I resolve this issue. Should I require this script with some other configurations?

**Comment by nightwing** [comment]
@FAGundum by default browserify exports only one module to the global scope.
As a workaround you can create a module like

```js
exports.esutils = require('esutils')
exports.estraverse = require('estraverse')
```

and browserify it instead

but that's not very nice.
I'll look if it's possible to get architect-build to work for node modules without requiring browserify step.

**Comment by FAGundum** [comment]
Great, thanks for the answer. I will look into it. I am going to close this issue.
