### ISSUE TITLE
Websocket and apache reverse = 400 bad request

### ISSUE THREAD

**Issue by slashafk** [c9/core#231]
Hello,
I have configured C9 to run behind my apache server  (for https and certificate authentication).

My configuration is the following : 

 ProxyRequests Off
 ProxyPassMatch ^/vfs/(.*transport=websocket.*)$ ws://ls2:8181/vfs/$1
 ProxyPass / http://ls2:8181/
 ProxyPassReverse /vfs/ ws://ls2:8181/vfs/
 ProxyPassReverse / http://ls2:8181/

When the browser wants to open the websocket session throught the url :

https://myserver.com/vfs/1/9cPc3vGL3PB0wbg3/socket/?access_token=token&EIO=3&transport=websocket&sid=fUCHFIb452qfBV5VAAAN

I get an error 400 Bad Request with an empty response.

Is there a way to get a working websocket connection with apache as a reverse proxy ?
Or is it normal that websocket are unavailable behind apache ?

Thanks.

**Comment by slashafk** [comment]
Hello, 
I've fixed the problem, it was the authentication headers that weren't forwarded to the c9 server, thus blocking the use of websocket.

Removing the authentication (-a : ) and using a ssl certificate for authentification fixed the problem.

**Comment by lordloh** [comment]
@slashafk : I am facing the same problem. not using `-a` will cause Cloud9 to bind only to 127.0.0.1 even if i specify `-l 0.0.0.0` And I absolute must have the authentication. What did you have to change? Are you authenticating the browser using the SSL certificate?
