### ISSUE TITLE
Any way to make custom runner to listen 9000 port?

### ISSUE THREAD

**Issue by belovanton** [c9/core#236]
I want make runner to listen 9000 port for external xdebug. Any way to do this?

**Comment by nightwing** [comment]
Use `debugport`.
A runner that uses xdebug would look something like
```json
{
    "cmd": [
        "php",
        "${debug?-d}", "${debug?xdebug.remote_enable=1}",
        "$file",
        "$args"
    ],
    "selector": "^.*\\.(php|phar)$",
    "info": "Running PHP script $file",
    "working_dir": "$project_path",
    "debugger": "xdebug",
    "debugport": 9000,
    "env": {
        "XDEBUG_CONFIG": "\"idekey=cloud9ide remote_host=localhost remote_port=9000 remote_mode=req\""
    }
}
```

if you don't need to start the process, you can replace   "cmd" with [ "sleep", 20000 ] or ["cat"]

But the debugger itself listens on `"127.0.0.1"` which might be a problem https://github.com/c9/c9.ide.run.debug.xdebug/blob/master/netproxy.js#L24

**Comment by belovanton** [comment]
Any way to make * instead 127.0.0.1?

**Comment by nightwing** [comment]
I'll add support for `"debughost": "....",` similar to debugport

**Comment by belovanton** [comment]
Ok, thank u I checked your trick with runner and only way I can make it work was php file with sleep(20000). For some reason sleep in cmd doesnt work.

**Comment by nightwing** [comment]
added in https://github.com/c9/c9.ide.run.debug.xdebug/commit/a1b39e0ac41763cd0574f65ab293e70ff8831507

strange that cmd didn't work

```
{
    "cmd" : ["sleep", "1000"],
```
works both on windows and linux
