### ISSUE TITLE
c9 publish breaks on 'something-js' directory in plugin

### ISSUE THREAD

**Issue by Pike** [c9/core#24]
https://github.com/c9/core/blob/master/plugins/c9.cli.publish/publish.js#L346 tests for .js, and not \.js$, which makes it pick up all kinds of things that aren't js files.

In my case, sax-js directory, which breaks once it tries to readFileSync that entry.

Given how many things call itself .js these days, it's probably a good idea to actually statSync to check if it's a file, too.

**Comment by nightwing** [comment]
Good find! This should be fixed by https://github.com/c9/core/commit/657fe113d254f5351962578166f8b12b70714a76
