### ISSUE TITLE
Error on startup (plugin c9.ide.ace)

### ISSUE THREAD

**Issue by Stiveknx** [c9/core#243]
When c9 is loading, it throws me an error, here:
https://github.com/c9/core/blob/master/plugins/c9.ide.ace/ace.js#L2034

I fixed by replacing that mentioned line by:
```
html.style.boxShadow = (skin.indexOf("flat") == -1) ?
     "0 1px 0 0 rgba(255, 255, 255, .3) inset" :
     "";
``` 
I guessed that it should be an ternary operation missing..

**Comment by nightwing** [comment]
Good find!
On which browser do you see this error? Chrome doesn't throw one when doing `html.style.boxShadow  = false`

**Comment by Stiveknx** [comment]
I'm using chrome, build 47.0.2526.111.

I throws only when I use the theme Classic  (Dark) .

**Comment by nightwing** [comment]
this was fixed some time ago https://github.com/c9/core/blob/d01f866bbae492da32e213443b2e66195bfa6bb0/plugins/c9.ide.ace/ace.js#L2060
