### ISSUE TITLE
setting-path only partial setting, user.settings doesn't persist

### ISSUE THREAD

**Issue by siliconalchemy** [c9/core#245]
Hi

I'm trying to set setting-path with the standard sdk install to change the default .c9 directory to something else.  Through trial and error i see that it's a path relative to the workspace, so if I set it to .c9-test and then restart the sdk I get a user.settings created in .c9-test.
- However, everything else seems to save to .c9 including metadata saved tabs.
- And I can save user settings (eg. theme, syntax theme etc) and I see the values update in user.settings but as soon as I restart the browser session it resets everything in user.settings to default.

**Comment by nightwing** [comment]
Hi, setting path was only for user-settings, it was added for tests, but tests do not use it now,  so may be buggy.
May I ask why do you want to change the name of .c9 folder?

**Comment by siliconalchemy** [comment]
To isolate sdk usage from commercial ide, and to use multiple users/instances for the same workspace. If this setting works even just for user settings, it would be good.

**Comment by nightwing** [comment]
should be fixed by https://github.com/c9/core/commit/600f4584c0af668aabbd305ebe32ca7adba307db
