### ISSUE TITLE
Javascript error on loading: SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by flackr** [c9/core#246]
Full stack trace:
`
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.main [as setup] (http://localhost:8001/static/plugins/c9.ide.language.javascript.tern/tern.js:14:32)
    at startPlugins (http://localhost:8001/static/lib/architect/architect.js:470:24)
    at startPlugins (http://localhost:8001/static/lib/architect/architect.js:478:21)
    at register (http://localhost:8001/static/lib/architect/architect.js:509:13)
    at http://localhost:8001/static/plugins/c9.ide.layout.classic/preload.js:77:13
    at http://localhost:8001/static/plugins/c9.ide.layout.classic/preload.js:58:21
    at _require (http://localhost:8001/static/mini_require.js:231:41)
    at http://localhost:8001/static/mini_require.js:131:13
    at Array.forEach (native)
`
This is likely due to the failure to load __list.json:
`GET http://localhost:8001/static/lib/tern_from_ts/defs/__list.json 404 (Not Found)`

As the failing plugin is `plugins/c9.ide.language.javascript.tern/tern`

**Comment by flackr** [comment]
I also did a bisect to try to find the first bad commit, however it seems that there was an invalid git hash on some of the plugins for a while, so it only bisected down to the following range:
# possible first bad commit: [7b68a58a8719a1526fe3ecb7d1067da1d0c73052] Merge pull request +11065 from c9/language-library-ui
# possible first bad commit: [fff75febb8366987b69220dfd878741a52e672ed] Update for new tern
# possible first bad commit: [6e13110fac1446655442f6fff41417cf5956d14a] Optimize getting current file
# possible first bad commit: [35a556fa087c3f35d78c367a0f62bf01d2695f03] Fix new tern file resolving
# possible first bad commit: [165cc12343c1d676ed62e9aec7d57af93f6ea264] More test config
# possible first bad commit: [4052f8584e4b3e99ee8b0c7db4dfd0abb04fc313] Update test suite
# possible first bad commit: [ca0114ae5595c1cfff165da8f1c6f827b1034ce0] Fix silly comparison
# possible first bad commit: [cb2117f41e6dfa1758d095f05d42affd85cfad66] Fix null showing up in docs
# possible first bad commit: [75087a3e242fac0a3dcd8238e05ffb04b243bccc] Merge remote-tracking branch 'origin/master' into language-library-ui
# possible first bad commit: [4fc8c267661aee818a1fc27955d2c6456caaab28] Merge remote-tracking branch 'origin/master' into language-library-ui
# possible first bad commit: [884762488d6c3c9c158c939ccc84957b1b33a3a2] Don't trust bootstrap docs yet
# possible first bad commit: [6ab35edef155e9729bb9de9e8fcbab27451e15fe] Remove silly docs
# possible first bad commit: [6b8e6cd63a31bf35609b95decfd3cc59326e8395] Enable completions for Meteor in meteor workspaces by default
# possible first bad commit: [71a72c51f1103fbe34595f7ef0607477f68dffb4] Future-proof settings format with enabled property
# possible first bad commit: [98409ab883643b787064875d2672c91deb194b97] Fix initial enabling
# possible first bad commit: [9ab27b2a9137a22b97bb46eaadb57beb46495bbc] Cleanup broken/redundant/iffy defs
# possible first bad commit: [1b1cff5ba6f870327098becd6cc0d4dbf868b9bf] Update tern_from_ts
# possible first bad commit: [de1070137dd0bf8f766e5348daad6536eea98e6e] Change icons for libraries
# possible first bad commit: [62c5f75f965f8e995c041238593f1cb2a3ac3001] Load configured defs at startup
# possible first bad commit: [80f520b9dbdbcba10287b3e63b73c85833d86e62] Fix chai
# possible first bad commit: [946cddc772aaf96746c171508cf3dc8471e5b0af] Fix saving settings
# possible first bad commit: [5ff9446d5dc0798ea368594b0ce90141d4a50517] Remove plugins from settings for now
# possible first bad commit: [8959856b27106d30b51e536b64977a7441d756cb] Tweak tern completions
# possible first bad commit: [15334b4fc08de1e8e8f3a2da5c794896bfb16c13] Fix first-class definitions
# possible first bad commit: [58f96d0812d9b2aebb25b920dfd782a43e15ad57] Persist settings
# possible first bad commit: [138f92aeaf4a37fc02524eeca75a8976f37cac1f] Rename sigs to defs
# possible first bad commit: [4b766d7d70dd5a98c0f2f7f9ddb63a1dbc57b926] Merge remote-tracking branch 'origin/master' into language-library-ui
# possible first bad commit: [2c21409a4abbdc16f0ce4e6d202d1079e3e357b8] Refactor settings handling
# possible first bad commit: [93d7929dd01daf6fd6bba1e52ce9139aa670d895] Fold firstClass into options
# possible first bad commit: [7bc33a0b7bdfe43a164d803400176aa46e208883] Improve settings UI
# possible first bad commit: [72343e46372b0dff27dac26af197e024899e43da] Don't make the whole language library UI feature experimental
# possible first bad commit: [9a43c471a4e8ad1932146af8dca6f5f03808a421] Split libraries into main and experimental
# possible first bad commit: [e3704d67edf177da3db83dec075ebc53be76899f] Update tern_from_ts
# possible first bad commit: [151da031dbbdb3f5d2881f58b56ff78f3198272a] Fix architect resolver
# possible first bad commit: [683170501b2a8defbc8a61746bb5557efe7d0f5a] Optimize load order for onlinedev
# possible first bad commit: [01335783107461b8a8b84d0ab570c2ed32347e00] Avoid warning on non-architect files
# possible first bad commit: [a182cc559ae91a311abb28dfcd90e4f42406ce33] Fix compatibility with new tern
# possible first bad commit: [77f54a2689cf568ac67a6db646d5516b7e03efb7] Disable common.js plugins
# possible first bad commit: [912d6112ed7ac1d2d9b0f70affee238dfe822107] Remove strange, unused API
# possible first bad commit: [fdd121dacd28a1949c39c7cc8998238d703dbf42] Rename function
# possible first bad commit: [88f3d51b5c6bbc3f5b5d2a083a2c4ed0e9bf7215] Cleanup
# possible first bad commit: [e1d218be9ee6ed47fcb4970be017b8f716c7f978] Cleanup
# possible first bad commit: [66ea93c303112497b3d486e71d33af5929d6940d] Cleanup
# possible first bad commit: [65992d5025814ffba16329854ff5c58c95c592ae] Enable additional plugins by default
# possible first bad commit: [c72651fa23283dbc1373abcd092b826f4c225114] Update list of tern plugins
# possible first bad commit: [76678606d7d817aa441dba2863ab4f5bbb8598b3] Turn tern UI into experimental feature
# possible first bad commit: [bf06a83535ac52d7b403a1d4a83937a2289d027c] Load tern_from_ts plugin list names
# possible first bad commit: [c8073f3252ea2954d725f02e48eea7189a591a0a] Update tern, tern_from_ts
# possible first bad commit: [c3bf4d46fca58efd33c7fb040ca59d5a7ad863fd] Fix fetching builtins
# possible first bad commit: [82b69e71e0ecbeedb367f50a2ba7583d62f94e20] Add note
# possible first bad commit: [973f86e31dab6cd8e1de8e3c9baebe520ab17bdd] Add tern_from_ts contents to settings
# possible first bad commit: [12e5198015eb24b5ae95db4c460c513e1e323c18] Get tern defs in parallel
# possible first bad commit: [465781716f56bcb4c0b16a7bf5a556fe82b6f74c] Add simple asynchronous fetchText()
# possible first bad commit: [e825636341e835016c84ff7323b4b5b43430de14] Cleanup
# possible first bad commit: [611155b8478b31f560beacaee3fd180ef1d43107] Fix Datagrid
# possible first bad commit: [56ee31efe9703766bef7d9ea99e907db655c9307] Show language settings at bottom of project preferences
# possible first bad commit: [aacba2a773f16e5f81a00b4f0442c40cb6ae59a7] Fix reference
# possible first bad commit: [1f75ef8e2efcdca824e4f75e7f0c25e9f6981c1b] Add tern UI stub

**Comment by flackr** [comment]
Actually looks like I was able to track this down to the commit in plugins/c9.ide.language.javascript.tern on which this broke: 6b5933e99169eca07407134eaf625e4c947efdf4
This was pulled in by the packages update 58f96d0812d9b2aebb25b920dfd782a43e15ad57

**Comment by Pike** [comment]
Can you check that your node_modules/tern_from_ts/defs/__list.json exists?

https://github.com/c9/core/commit/1b1cff5ba6f870327098becd6cc0d4dbf868b9bf should have updated that to a version that has that.

**Comment by flackr** [comment]
Hmm, looks like this exists and it's now working. Unfortunately I'm not sure why it wasn't working last night. Sorry about the noise.
