### ISSUE TITLE
Error: Cannot find module 'optimist'

### ISSUE THREAD

**Issue by xvinc** [c9/core#250]
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/xvinc/c9sdk/server.js:11:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by xvinc** [comment]
> pty.js@0.2.8 install /root/.c9/node_modules/pty.js
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.12.6.tar.gz local checksum b7dbe51810897e7aa0a5a1a0ef179029f7c093ef3be955d8e5cf1adad62d88dd not match remote 7a3b5ac351973a9dee8edbf0684bc8d0dea44b231e42274ffb008141ffa19ad2
gyp ERR! stack     at deref (/root/.c9/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/root/.c9/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/root/.c9/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.c9/node_modules/pty.js
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/root/.c9/node/bin/node" "/root/.c9/node/bin/npm" "install" "pty.js@0.2.8"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.c9/npm-debug.log

**Comment by nightwing** [comment]
the error means node-gyp couldn't compile pty.js.
On which OS are you trying to install this?
Could you try running install.sh from https://github.com/c9/install separately

**Comment by the4tress** [comment]
I had this issue as well when doing a fresh install tonight. I had to revert to an older version to get it working.

    cd <your c9 install path>
    git reset --hard c471ab0e4c7cb983e1e4c40675b3fd63916c9394
    scripts/install-sdk.sh

**Comment by the4tress** [comment]
Actually I just tried it again on another fresh install to make sure it worked and it didn't. Something I did previously in troubleshooting fixed it, but I don't know what.

Would be nice to have a resolution to this.

Running a fresh install of CentOS 7.

**Comment by nightwing** [comment]
@the4tress probably there is an error while compiling pty.js 
try running `yum install tmux glibc-static make g++ gcc-c++`
