### ISSUE TITLE
packagePath overwritten in package.json when publishing

### ISSUE THREAD

**Issue by alanhamlett** [c9/core#252]
Before publishing a package using c9 cli, `package.json` looks like:

```
...
  "plugins": {
    "wakatime": {}
  },
...
```

After publishing, `package.json` looks like:

```
...
  "plugins": {
    "wakatime": {
      "packagePath": "plugins/wakatime/wakatime"
    }
  },
...
```

[Line 602](https://github.com/c9/core/blob/8f7f129a1e7c74508a3bb844aa5392eb09924793/plugins/c9.cli.publish/publish.js#L602) is why.

Related to https://groups.google.com/d/msg/cloud9-sdk/d7w5KaPEXI0/DZsPoQx_EwAJ

**Comment by nightwing** [comment]
this is fixed in the latest version of the cli
