### ISSUE TITLE
Website email is down

### ISSUE THREAD

**Issue by asdf23** [c9/core#253]
When trying to report a bug I was unable to use your website to contact you. I really want to like this software...
![c9bugs](https://cloud.githubusercontent.com/assets/4165735/13259020/7a712e06-da0a-11e5-8f54-6b9a8eac4286.png)

**Comment by nightwing** [comment]
Thanks for reporting about this!
We are updating that page to point to https://community.c9.io/ (the fix will be online with the next deploy in a day or two)
Note there is also a link to the https://community.c9.io/ in the support menu inside the ide.

**Comment by asdf23** [comment]
Could you tell me where that link is? I do not see it. Thanks

**Comment by nightwing** [comment]
see the image
![image](https://cloud.githubusercontent.com/assets/341801/13269514/84f290d0-daa1-11e5-92a0-9c40c1e8d69d.png)
It opens https://community.c9.io/

**Comment by asdf23** [comment]
My bad!
