### ISSUE TITLE
Windows 10 install fails

### ISSUE THREAD

**Issue by dr3x** [c9/core#257]
scripts\install-sdk.sh

I have the prerequisites listed here:
https://www.youtube.com/watch?v=Bhy0vZYElbE
git/node/python 2.7/cygwin

first error:
C:\src\repos\c9sdk\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
C:\src\repos\c9sdk\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'ThrowException': is not a member of 'v8'
[C:\src\repos\c9sdk\node_modules\ws\build\bufferutil.vcxproj]
  C:\Users\myname\.node-gyp\5.7.0\include\node\v8.h(66): note: see declaration of 'v8'

when the script completes (with errors) and I run it, can't find runners_list (but probably because of all the errors with the install script)

C:\src\repos\c9sdk>node server.js
Starting standalone
module.js:341
    throw err;
    ^

Error: Cannot find module '../plugins/c9.ide.run/runners_list'

**Comment by nightwing** [comment]
the tutorial above is wrong.
you need only git and node. 
Run install-sdk.sh from git prompt, and it will download required files from https://github.com/cloud9ide/sdk-deps-win32

**Comment by dr3x** [comment]
ok that fixed the script errors, but I'm still getting the unexpected token error in runners_list.js:9:25

for anyone following along, here are the steps to run in a git prompt:
1) invoke git bash
2) change to the directory with weird git syntax (cd /c/src/repos/c9sdk/)
3) invoke the script: 
user@MACHINE /c/src/repos/c9sdk (master)
$ /c/src/repos/c9sdk/scripts/install-sdk.sh

**Comment by dr3x** [comment]
ok finally got it the ide to run, looks like it was the bad file names, my hacky fix to runners_list.js is attached, basically just putting the file name in double quotes and then ignoring the errors for the files that still don't load. don't know what the side effects would be or I'd put in a pull request.

[runners_list.zip](https://github.com/c9/core/files/147321/runners_list.zip)

**Comment by nightwing** [comment]
Used a bit modified version of this in https://github.com/c9/c9.ide.run/commit/4f0257bc0bc2ce6577398bfc4886b96e262af4a8. Thank you!
