### ISSUE TITLE
Installing on xubuntu 15.10

### ISSUE THREAD

**Issue by cycl0ne** [c9/core#260]
Hi,

running install script comes to following error:
/home/poweros/.c9/local/include/ncurses -O2 --param max-inline-insns-single=1200 -c ../ncurses/lib_gen.c -o ../objects/lib_gen.o
In file included from ../ncurses/curses.priv.h:283:0,
                 from ../ncurses/lib_gen.c:19:
_42660.c:835:15: error: expected ‘)’ before ‘int’
../include/curses.h:1594:56: note: in definition of macro ‘mouse_trafo’
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
Makefile:785: recipe for target '../objects/lib_gen.o' failed
make[1]: *** [../objects/lib_gen.o] Error 1
make[1]: Leaving directory '/home/poweros/.c9/ncurses-5.9/ncurses'
Makefile:109: recipe for target 'all' failed

**Comment by nightwing** [comment]
could you try installing tmux with apt-get, before running install-sdk.sh

**Comment by cycl0ne** [comment]
Hi,
thanks. Worked now :)
