### ISSUE TITLE
plugin.setAPIkey is broken

### ISSUE THREAD

**Issue by mimibar** [c9/core#264]
When calling plugin.setAPIKey(options.apikey) from an installed plugin, the options key is null. This is called by the Architect in startPlugins(additional)

See https://groups.google.com/d/topic/cloud9-sdk/1wWn1R-RiIo/discussion

**Comment by nightwing** [comment]
This should be fixed now

**Comment by mimibar** [comment]
I am getting again "setAPIKey is not a function" , is it down again?
