### ISSUE TITLE
npm install -g c9 broken, architect-build disappeared from npmjs.com

### ISSUE THREAD

**Issue by Pike** [c9/core#267]
https://www.npmjs.com/package/c9 depends on https://www.npmjs.com/package/architect-build, and that's gone.

what's the right way to get a local c9 these days?

**Comment by nightwing** [comment]
architect-build is bundled in c9 package, with which version of npm do you see this issue?

**Comment by Pike** [comment]
my npm is version 3.6.0. That's the one that comes with homebrew's node, https://github.com/Homebrew/homebrew/blob/master/Library/Formula/node.rb.

**Comment by nightwing** [comment]
Looks like npm 3 broke support for bundledDependencies https://github.com/npm/npm/issues/10283 :(
I've published architect-build, so npm install works, but now it installs several unnecessary packages

**Comment by nightwing** [comment]
Published a new version that bundles all the dependencies and doesn't use node_modules folder to work around npm bug.
Let me know if it works for you.

**Comment by Pike** [comment]
totally, thanks.
