### ISSUE TITLE
Runaway memory use by webworker

### ISSUE THREAD

**Issue by georgir** [c9/core#269]
Recently I started seeing a weird behavior that would always crash my firefox by using up too much memory when I use a locally ran c9 ide. 
A report from Firefox's about:memory (attached,
[memory-report.json.gz](https://github.com/c9/core/files/168748/memory-report.json.gz)) shows the memory is used by some webworker and not the main window. What kind of webworker jobs does c9 use? 

Some experimentation shows it is reliably reproducable just by opening a certain file in my project and clicking through the code, without even changing anything.
The code of the file in question is not that unusual. It is around 400 lines and has an approximately 200 line method that is all a single statement, due to chaining of a large number of Promise.then() calls.
The code is not exactly secret, though I'd still prefer not putting it out as publicly as in the issue report here. If anyone from c9.io wants it I could send it over.

**Comment by georgir** [comment]
Some more experimentation - starting a c9 ide server with an empty workspace directory, opening a new file tab in it and pasting the source, selecting javascript in the view/syntax menu and clicking through also triggers the issue.
Doing the same on a workspace on the online live version of c9.io does not trigger the issue though.

**Comment by georgir** [comment]
I was at revision 737d032 btw.
I now did a git pull to see if the issue remains, it updeted to 827a851 and now the ide does not load at all (I guess that deserves a separate report, but it seems big enough that you probably noticed yourselves and there is no need...)

**Comment by nightwing** [comment]
did you run ./scripts/install-sdk.sh or just git pull? install-sdk.sh is needed to update plugins too

**Comment by georgir** [comment]
I edited my previous post before seeing your reply. But now I'm also adding another reply because I guess edits and notifications don't mix well.
You are right, I missed that step. And I can not reproduce the issue with the newest version, so once again apologies for wasting your time.

**Comment by nightwing** [comment]
This was most likely related to https://github.com/ternjs/tern/issues/725, 
We have disabled angular plugin in the current version, but having another example that causes large memory use will be helpful for debugging.
Could you try removing, most of the code but keeping the long chain of promises.
You can use https://preview.c9users.io/nightwing/tern/doc/demo/index.html#requirejs for testing, but it may crash the browser.

**Comment by georgir** [comment]
Yes, pasting just the return statement (still 200+ lines) in that textfield causes my browser to hang. The hang is different than in the c9 ide, I assume because this test does not use a webworker. It's not from a high memory use but from what I assume is long-running javascript. Memory use shown in my system process list seems to grow much slower.

**Comment by georgir** [comment]
When I paste the complete source and not just the return statement, I get the quickly rising memory use.
So I guess the definitions of the functions I were using in my then chain were important for the reproduction of the bug.

**Comment by nightwing** [comment]
Could you send me the complete source (see email in the profile)? Having another code snippet causing high memory use will be helpful in debugging the issue.
