### ISSUE TITLE
How to activate menu "git add" in terminal ?

### ISSUE THREAD

**Issue by ludoo0d0a** [c9/core#27]
Could you tell me how to activate the "git add" menu in terminal on a local installation of cloud9.

I saw feature is in plugin c9.ide.terminal/link_handler.js, which is not 'required' by my installation.

I failed to clearly understand how to add plugins.
Thanks for your help.

**Comment by javruben** [comment]
It should be there. It works by parsing the prompt. If the prompt doesn't contain a path it won't work.

**Comment by ludoo0d0a** [comment]
I debug deeper and found that 'ls' command failed too and hover link in general.
I found that findPrompt in aceterm/hover_linkjs failed on the regex

I have something like this
````js
//var m = promptRe.exec(line);
/([~\/](?:[^\\\s'"\(<]|\\.)*)[^$]*?\$/.exec("[user@ip-172-10-10-10 my_website]$ ls")
````

I'm not quite enough good in regex to clearly understand this one..

**Comment by nightwing** [comment]
hover_link needs to find working directory to be able to display links for ls and git.
The prompt you are using (`[user@ip-172-10-10-10 my_website]$` ) doesn't provide that information, It displays only the folder name.
You can set `PS1='\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '` in your bash config, to get a prompt similar to the one on c9.io.

**Comment by ludoo0d0a** [comment]
Perfect, thanks a lot :+1: 
I finally inspired me of nightwing PS1, .bashrc from c9.io and the git-prompt script to customize my prompt.

It would be great to put this thing into the doc.
