### ISSUE TITLE
debugger cannot show the object member values

### ISSUE THREAD

**Issue by narychen** [c9/core#273]
When debugging, put the mouse on a variable or just click the variable on the debugger sidebar, it often blocks and always spins for you to waiting the result. But the result never shows.
It happens most frequently when the variable is returned from a generator yield.

**Comment by nightwing** [comment]
could you give an example code for reproducing this problem. Also for which debugger does this happen nodejs or another one?

**Comment by narychen** [comment]
It's really hard to give an example code that could reproduce the problem.
So maybe we could only let it pass though.
