### ISSUE TITLE
Stuck On Loading Screen

### ISSUE THREAD

**Issue by pravsterrr** [c9/core#278]
I recently installed c9sdk on my Raspberry Pi 2 Model B running Raspbian (port of Debian). 
The installation was successful apart from a few modules (async and less). I later installed these from their GitHub pages and that was successful.
When i try to run the server.js script. It works and i get output that the server is running. If i try to access the server by it's IP address from another machine that is on the same network, I get the loading screen. But i do not get any further than it. Does anyone know how to resolve this? Thanks

![image](https://cloud.githubusercontent.com/assets/16594062/14043355/48996fea-f27b-11e5-9a51-a39239ebdc67.png)
Image of the Browser. This what i end up with.
![image](https://cloud.githubusercontent.com/assets/16594062/14043346/32eb439e-f27b-11e5-932b-3fbfca0cda52.png)
Image of the Terminal output. Seems fine.

**Comment by nightwing** [comment]
there must be an error in browser console. please check that too.

**Comment by pravsterrr** [comment]
Issue Was Fixed With Reinstallation !
