### ISSUE TITLE
Auto-pair brackets, quotes, etc. not working (Python)

### ISSUE THREAD

**Issue by lisandro52** [c9/core#279]
I've been using C9 on my javascript projects and it's been fantastic to work with. 
I'm now trying to use it on a Python project, but the auto-pair feature isn't working at all (for JS, it autocompletes everything).
If someone could point me in the right direction, I could try to add the feature myself but I don't know where to look or what I should be looking for.

Sorry if the issue doesn't go here! I wasn't sure if the issue had to go here, on the core, or on the Python plugin repo.

**Comment by nightwing** [comment]
The code adding autopairing for javascript is at https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/javascript.js#L40 https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/behaviour/cstyle.js
should it behave in python exactly the same as in javascript?

**Comment by asdf23** [comment]
I would guess that Python's blocks would be so incredibly different that
this would be no small task. Especially since Python has some concept of
being forgiving about some whitespacing.

**Comment by nightwing** [comment]
Auto pair should work for all modes now.
Please let us know if you find any issues with it

**Comment by lisandro52** [comment]
Thanks @nightwing, it works just the way I wanted.
