### ISSUE TITLE
Collab has some issues

### ISSUE THREAD

**Issue by portokallidis** [c9/core#28]
When i enable --collab it seems that it tries to connect to api.c9.dev  (cool domain!) and it fails with the  below console output :  

Failed to load resource: net::ERR_CONNECTION_CLOSED
https://api.c9.dev/collab/0/access_info?access_token=token Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
default.js:16397 Collab not connected - SKIPPING  Object
default.js:16397 Collab not connected - SKIPPING  Object
default.js:16313 [OT] Collab connect timed out ! - retrying ...
default.js:16304 Collab connecting
default.js:16320 COLLAB CONNECT ERR Object
default.js:151130 GET https://api.c9.dev/collab/0/access_info?access_token=token net::ERR_SSL_PROTOCOL_ERROR
default.js:151130 GET https://api.c9.dev/collab/0/access_info?access_token=token net::ERR_CONNECTION_CLOSED
default.js:151130 GET https://api.c9.dev/collab/0/access_info?access_token=token net::ERR_SSL_PROTOCOL_ERROR

The --collab feature also interferes with the file save process and slows it down severely.
When start it without --collab it runs smoothly with no console errors

**Comment by nightwing** [comment]
Some files were missing. This should be fixed by https://github.com/c9/core/commit/82b56224baaa2c47519c9ddd568848ce7e99d253.

**Comment by romanman** [comment]
@nightwing : it still works that way on my SDK (latest)
