### ISSUE TITLE
Run cloud9Ide from Upstart

### ISSUE THREAD

**Issue by riccardoroasio** [c9/core#287]
Hi,

I found an issue running cloud9 ide from Upstart, at startup server.js give this error:

```
Starting standalone

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
```

I found that the problem is that Upstart set a PWD env variable while the c9 ide in standalone.js check for a HOME variable at line 22:

```
if (process.env.HOME === undefined)
            process.env.HOME = process.env.HOMEDRIVE + process.env.HOMEPATH;
```

I found a solution adding these lines:

```
        if (process.env.HOME === undefined)
            process.env.HOME = process.env.PWD;
```

just after the previous if statement

Am I right or I'm doing somthing wrong?

Riccardo

**Comment by nightwing** [comment]
you can define HOME variable in upstart script to not have to modify standalone.js
