### ISSUE TITLE
How can I minimize traffic?

### ISSUE THREAD

**Issue by fatihky** [c9/core#289]
Hi! I want to minimize consumed traffic. Because I am using c9 with 3g and prices are high now.

- How can I serve compiled versions of css and js files?
- How can I serve all static files from one server? I am using multiple c9 instances. I want to all instances get  static files from the same url.

**Comment by nightwing** [comment]
This is not fully possible. see https://github.com/c9/core/issues/302 for details

**Comment by fatihky** [comment]
Thank you for information. This information enough for me. Can I close this issue?

**Comment by Youtubrer** [comment]
yes, once your issue is solved, you can close it.

**Comment by fatihky** [comment]
`--packed` helped to me
