### ISSUE TITLE
Language worker problem

### ISSUE THREAD

**Issue by portokallidis** [c9/core#29]
I have a c9 installed on a raspberry pi 2 with an ubuntu 14.04 image , all is working except for the language worker problem.

The console output is :
Language worker could not be loaded; some language features have been disabled

Tried to solve with :  
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

But with no hope

**Comment by nightwing** [comment]
This is most likely caused by collab not working https://github.com/c9/core/issues/28.
Please reopen if you are seeing it without `--collab`, or with the latest version.
