### ISSUE TITLE
Code folding menus and keyboard shortcuts only work with braces/brackets/comments

### ISSUE THREAD

**Issue by octachrome** [c9/core#291]
If a custom Ace mode defines a folding mode (as described at https://cloud9-sdk.readme.io/docs/code-folding), the Edit..Code Folding menus and related keyboard shortcuts do not work.

To reproduce, try creating a Python script with some foldable control flow:

    x = 4
    while x > 0:
        print x
        x -= 1

Note the folding widget in the gutter on line 2. Place the cursor at the start (or end) of the while line and press Ctrl-F1 to fold - nothing happens.

The menus and keyboard shortcuts only work in JavaScript because `toggleFold` in `folding.js` specifically handles brace matching, bracket matching, and comment matching, and those are the only things that can be folded in JavaScript anyway.

**Comment by nightwing** [comment]
Fold menu uses deprecated foldSelection command, i'll update it to use toggleFold Instead which is bound to `F2`

**Comment by octachrome** [comment]
You're right - F2 works fine. Sounds like a simple fix, which is great news.

Thanks @nightwing

**Comment by nightwing** [comment]
should be fixed by https://github.com/c9/core/commit/8ccb5ec236cdc87a502253ba933400acf6079371
