### ISSUE TITLE
Create workspace when loaded?

### ISSUE THREAD

**Issue by XtremePlayzCODE** [c9/core#298]
Can there be a feature where upon loading you can make a workspace in the directory of the SDK?
Or can you set where the SDK loads files in the editor so I can set it to load a folder in the SDK directory?

(P.S. Sorry for bad english, its 3:00 am)

**Comment by nightwing** [comment]
use `-w /path/to/directory` option for server.js

**Comment by XtremePlayzCODE** [comment]
thanks
