### ISSUE TITLE
Problem with sqlite3 in installation

### ISSUE THREAD

**Issue by kazelsama** [c9/core#30]
<pre>
> sqlite3@2.1.18 install /home/home/.c9/node_modules/sqlite3
> node build.js

[sqlite3]: Checking for http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v11-linux-arm.tar.gz
[sqlite3]: http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v11-linux-arm.tar.gz not found, falling back to source compile (Error: Server returned 404)
</pre>

Sorry for short Issue i speak little english ( but i love this project <3 )

**Comment by nightwing** [comment]
@kazelsama What did you run to get this error?
Looks like prebuilt versions of sqlite3 for node 0.11 are missing. but the install-sdk.sh script is supposed to use node v0.10 not 0.11
