### ISSUE TITLE
Nginx Proxy not working with Websockets

### ISSUE THREAD

**Issue by Egoscio** [c9/core#301]
Hello, I have a local install of c9, and I'm using Nginx as my proxy and encryption with letsencrypt. Everything works perfectly fine, except for the fact that Websockets don't work. I noticed that whenever I do something in c9, ajax requests are sent, which are visible through the networking tab of the chrome web inspector. Here is my configuration:

```
server {
	include /etc/nginx/includes/letsencrypt;
	server_name c9.website.com;

	location / {
		proxy_pass http://localhost:1337;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Client-Verify SUCCESS;
		proxy_read_timeout 1800;
		proxy_connect_timeout 1800;
	}
}

server {
	listen 80;
	server_name c9.website.com;
	return 301 https://$host$request_uri;
}
```

Any help would be much appreciated. I'd be happy to provide more details if needed.

**Comment by imperian** [comment]
You need HTTP 1.1 and the upgrade options.  I use the following

`        proxy_pass http://c9sdk:3131;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_redirect default;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';`

**Comment by Egoscio** [comment]
@imperian Thank you! It's working just fine now.
