### ISSUE TITLE
Connect desktop (aka local/standalone?) version to remote c9 instance

### ISSUE THREAD

**Issue by Egoscio** [c9/core#302]
Hello, I've installed a remote instance of c9 on my VPS. It runs fine, however, every time I connect to it, it has to download ~10mb of web assets for the client side. This is very slow and consumes too much mobile data when I'm not working on Wifi (Google chrome doesn't like to cache it). I followed [this guide](https://cloud9-sdk.readme.io/v0.1/docs/running-cloud9-desktop) on how to install it locally, but the resulting app doesn't give me an option to connect to a custom server. I would appreciate some light to be shed on my seemingly lost trajectory.

**Comment by nightwing** [comment]
there is no existing way to do this.
It may be possible to pass vfs url to https://github.com/c9/core/blob/master/plugins/c9.vfs.client/endpoint.js#L26, and change vfs server to set access control headers, but that is not implemented

**Comment by nightwing** [comment]
You can use ?packed=1 to load packed version or use experimental `--useBrowserCache` [flag](https://github.com/c9/core/blob/09bf053920e28291b3d6c0921b3ab97561d37d8b/configs/standalone.js#L44) to save files in the `window.caches`.
With the last method only the files changed since the last time will be downloaded.

**Comment by Egoscio** [comment]
Okay, thank you. I think I'll go with the latter until I feel comfortable enough playing with the codebase. Would be a nice feature for the future though, but I'm not sure if many will encounter a similar situation as mine.
