### ISSUE TITLE
Blocked Account

### ISSUE THREAD

**Issue by Lukkez** [c9/core#303]
Hey, some days ago my account was blocked, and when i tried to log in the page freeze and say, 401 box, and i can't delete my account to make another, my username is ``playogar`` and how it happen? i was on a team, and most of my friends got the account blocked at same time, that's a error?

**Comment by nightwing** [comment]
It's not an error, using cloud9 for running bots is not allowed, see https://community.c9.io/t/can-i-run-a-chat-agar-slack-bot-with-cloud9/5536

**Comment by Lukkez** [comment]
But we can't delete the WHOLE workspaces and start again? i never used them for a long time, i was just used some times, :S i lost my team and all.... ok ._.
And they don't give any warning, i never saw that

**Comment by Lukkez** [comment]
And... i can't delete my account

**Comment by Lukkez** [comment]
@nightwing You can't delete my acc without removing the team? or delete all workspaces, i was looking to start all again and now make another things i was planning
