### ISSUE TITLE
Delete blocked acc or restart account

### ISSUE THREAD

**Issue by Lukkez** [c9/core#304]
The title says all but i was looking to restart ALL the whole workspaces and maybe account but without removing the team? please, i'm looking to still with the account, or maybe just delete the whole account and i ask to put on the team again... :cry:

**Comment by XtremePlayzCODE** [comment]
I feel your pain. Your LKZ agar site... well, C9.io dosen't allow website hosting. It is a development service and with all the people on LKZ c9 removed your account.I didn't host a website but I hosted agar.io bots and um... I got banned. Just use the local version instead ;)

**Comment by Lukkez** [comment]
Yes and i was going to develop a real website, localhost i can't, my pc lag much and give blue screen, i just made another account but the support for c9 is 0/10 for me, i e-mail them like 20 times and i got 0 answers

**Comment by timjrobinson** [comment]
@Lukkez You were banned for DDOS'ing, running Minecraft servers and running Agar clients and servers all of which are against our ToS and for DDOS'ing especially you should know better. Wasting our time by sending tickets through every source possible isn't going to help your case and your account will remain blocked.

**Comment by XtremePlayzCODE** [comment]
@timjrobinson Then how the fuck was I banned? I just hosted bots that connected to a game (agar.io) and fed you... I didn't host a website and I got fucking banned.
