### ISSUE TITLE
No cmd+p files found unless they're opened first

### ISSUE THREAD

**Issue by benlowry** [c9/core#307]
Using the hosted version at c9 when I try to open files using cmd+p or cmd+e the only files that are indexed are the ones I have opened that session.

![screen shot 2016-05-30 at 3 38 44 pm](https://cloud.githubusercontent.com/assets/2373805/15658678/8ef5186a-267c-11e6-8e77-2f47043b76d8.png)

vs expected:

![screen shot 2016-05-30 at 3 38 52 pm](https://cloud.githubusercontent.com/assets/2373805/15658683/9e22e7c2-267c-11e6-9720-1a9e789ebdf0.png)

**Comment by nightwing** [comment]
check if you have scope navigate to favorites turned on 
![image](https://cloud.githubusercontent.com/assets/341801/15664235/22a9ad1e-2713-11e6-83d5-95515d8ab7bb.png)

**Comment by benlowry** [comment]
The setting was already on.

**Comment by benlowry** [comment]
Toggling it off-then-on got it working.

**Comment by nightwing** [comment]
if you want files from outside of favorites, setting needs to be off, as shown in the image.
