### ISSUE TITLE
Not Working :/

### ISSUE THREAD

**Issue by systemroot** [c9/core#308]
Hello, 

Just i install this on my VPS, looks good from my terminal, no errors, 
<pre>
root@theraw:~/c9sdk# sudo node server.js
Starting standalone
Connect server listening at http://127.0.0.1:8181
CDN: version standalone initialized /root/c9sdk/build
Started '/root/c9sdk/configs/standalone' with config 'standalone'!
Cloud9 is up and running
</pre>

But when i open my VPS public ip in my browser is offline :confused: 
**This site can’t be reached**
I'm trying to to add  --listen <PUBLIC_IP> but is not working :/ 
This is only for localhost or is any problem ?!

**Comment by nightwing** [comment]
pass `-a :` to listen on 0.0.0.0

**Comment by k0nsl** [comment]
@nightwing: passing `-a :` does not make it listen on all interfaces, that's at least not true for my case: it just binds to "127.0.0.1" and nothing else.
But when I pass `--listen` followed a external IP address associated to the server it actually does bind to that IP and will go so far as to serving some content -- although it isn't actually working, but at least it does something.

If I understood correctly, passing `-a :` disregards basic authentication.

Best wishes,
-k0nsl

**Comment by nightwing** [comment]
It doesn't bind to external ip without `-a` see https://github.com/c9/core/blob/7543940fbdb23ddcebe16a8057b6274f15c3d24b/configs/standalone.js#L93

>  although it isn't actually working

that's caused by an error during the installation

**Comment by mateothegreat** [comment]
@systemroot I had the same problem .. ultimately it is because c9 will not listen to any ip other than localhost IF authentication isn't enabled.

Without auth:
```
[root@instance-1 c9sdk]# node server.js -w /home/lenixx/workspace -p 8181 -l 0.0.0.0 -a
Starting standalone
Authentication is required when not running on localhost.
If you would like to expose this service to other hosts or the Internet
at large, please specify -a user:pass to set a username and password
(or use -a : to force no login).
Use --listen localhost to only listen on the localhost interface and
and suppress this message.
Warning: running Cloud9 without using HTTP authentication.
Run using --listen localhost instead to only expose Cloud9 to localhost,
or use -a username:password to setup HTTP authentication
Connect server listening at http://127.0.0.1:8181
CDN: version standalone initialized /home/lenixx/c9sdk/build
Started '/home/lenixx/c9sdk/configs/standalone' with config 'standalone'!
Cloud9 is up and running
```

WITH AUTH:
```
[root@instance-1 c9sdk]# node server.js -w /home/lenixx/workspace -p 8181 -l 0.0.0.0 --auth test:test
Starting standalone
Connect server listening at http://10.128.0.2:8181
Using basic authentication
CDN: version standalone initialized /home/lenixx/c9sdk/build
Started '/home/lenixx/c9sdk/configs/standalone' with config 'standalone'!
Cloud9 is up and running
```

So it was my fault for not paying attention :)
and the fact that the c9 guys have this as a security feature is a +1

**Comment by systemroot** [comment]
@mateothegreat  that's really perfectly :+1:

**Comment by sunny-g** [comment]
I'm having a weird issue with this same configuration c9:

I'm always automatically logged in, even after clicking "Log Out" and removing all personal data stemming from the public-facing IP I'm using to access by c9. No matter what I do, I can't seem to do anything to get it to prompt me to log in with my username and password (even after shutting it down, and changing the username and password passed in on the command line).

Any thoughts?
