### ISSUE TITLE
'plugins' directories not created

### ISSUE THREAD

**Issue by briansrepo** [c9/core#332]
I get the following message when starting c9

> 26941: Error: ENOENT: no such file or directory, stat '/home/brian/.c9/plugins/'
>     at Error (native)
> 26941: Error: ENOENT: no such file or directory, stat '/home/brian/.c9/managed/plugins/'
>     at Error (native)
> 26941: Error: ENOENT: no such file or directory, stat '/home/brian/.c9/dev/plugins/'
>     at Error (native)
> 26941: Error: ENOENT: no such file or directory, stat '/home/brian/.c9/plugins/'
>     at Error (native)
> 26941: Error: ENOENT: no such file or directory, stat '/home/brian/.c9/plugins/'
>     at Error (native)
> 26941: Error: ENOENT: no such file or directory, stat '/home/brian/.c9/plugins/'
>     at Error (native)
> 26941: Error: ENOENT: no such file or directory, stat '/home/brian/.c9/plugins/'
>     at Error (native)
> 26941: Error: ENOENT: no such file or directory, stat '/home/brian/.c9/plugins/'
>     at Error (native)

It was easily fixed by manually creating those directories, but that seems like something that should happen automatically from the install script.

**Comment by nightwing** [comment]
This can be caused by an error in install script, try running install-sdk.sh script again
