### ISSUE TITLE
cursor position is incorrect  in tab(\t) indent file

### ISSUE THREAD

**Issue by chanble** [c9/core#34]
When the file indent use tab, cursor position can't focus end of line.  In fact the cursor is focused end of line, because the last char is delete when press BackSpace key.

**Comment by nightwing** [comment]
On which browser/os does this happen?
Is showinvisibles enabled?

**Comment by chanble** [comment]
os:ubuntu 14.04
browser: firefox 36
yes, show invisibles.

**Comment by chanble** [comment]
It's ok by showinvisibles disable

**Comment by nightwing** [comment]
This was fixed by https://github.com/c9/core/commit/499c8976b9397ae605d583ac55e27107582b5165, please reopen if it isn't, and the issue still happens after the update.
