### ISSUE TITLE
Leftover inaccessible terminal sessions

### ISSUE THREAD

**Issue by georgir** [c9/core#343]
Hello,

I work with a locally installed c9 instance.
When I open some terminal tabs, they get remembered and even if I close my browser and later reopen it, the programs in the terminals are still running. This is quite an awesome feature, but is also a bit of a double-edged sword.
If I open c9 in two browsers (i.e. at home and at work), both see the previously open terminals. But newly opened terminals in each browser are not shared in the same way, and only the ones in the browser that is closed last are saved and remain accessible in future c9 sessions. The terminals that were opened in the other browser are "lost" and no longer accessible, though looking at process list they seem to still be running.

Can I list such leftover terminal sessions and reconnect to them or at least close them?

(Alternatively, is it possible to make c9 state between different browsers stay in sync? I.e. when I open some tabs at home, to have them also open on the browser I left running at my office? Then the issue would not arise in the first place)

**Comment by nightwing** [comment]
![image](https://user-images.githubusercontent.com/341801/34670999-0cae1f92-f492-11e7-9a1e-477a56ebafa3.png)
It is now possible to see the list of other terminal sessions using context menu.
Keeping state in sync is a bit harder since there are cases when one wants to keep them separate.
