### ISSUE TITLE
[Question] [SDK] Enable "resources" widget?

### ISSUE THREAD

**Issue by eslachance** [c9/core#344]
So, I have the C9 SDK running on my VPS, which is awesome to use (off-topic: you're losing $4-5 a month because you don't have a single hot workbench plan, guys). 

However, when using the C9 SDK, at the top-right of the screen there is no "resources" widget - the place where it shows CPU, Memory and Space useage in real time. I know what it displays is actually the workbench stats (and also lets you resize if you're paying), but actually having that widget even on my VPS would be great help in seeing what's happening on my machine. 

If there's a way to enable it (`c9 install resource-monitor` ? something like that?), I'd love to hear it. Otherwise, I guess this might be a feature request, I guess, for the SDK.

**Comment by nightwing** [comment]
resources widget is not included in the sdk since it uses server side api which depends on the docker container manager used in the hosted environment.
