### ISSUE TITLE
Error: Cannot find module '../plugins/c9.ide.run/runners_list' and Error: Cannot find module '../plugins/c9.ide.run/runners_list'

### ISSUE THREAD

**Issue by ghost** [c9/core#349]

**Comment by reubenscratton** [comment]
c9.ide.run appears to be in a separate repo...

**Comment by reubenscratton** [comment]
Yep, got it working by doing this from the core dir:

cd plugins
git clone https://github.com/c9/c9.ide.run
git clone https://github.com/c9/c9.ide.run.build
cd ..
node server.js

**Comment by nightwing** [comment]
With https://github.com/c9/core/commit/bfbdaa7529fb91e65a288f3f1f67a0e7706a304a install-sdk.sh won't silently fail if installing one of plugins fails
