### ISSUE TITLE
PTY is not supported. Error!

### ISSUE THREAD

**Issue by prataksha** [c9/core#350]
After installing c9 in my private server then I launched cloud9 ide and then console was outputting **PTY is not supported**

Also after launching, the terminals in the ide don't work.

**Comment by nightwing** [comment]
were there any errors while running the installer? try rerunning the installer from https://github.com/c9/install

**Comment by prataksha** [comment]
First time running the installer gave "**PTY.js not found error**".
But now when I re-ran the installer it solved the **PTY.js** issue.

Thanks :)

**Comment by ido4pro** [comment]
install-sdk.sh + curl -L https://raw.githubusercontent.com/c9/install/master/install.sh | bash fix the issue
