### ISSUE TITLE
Language worker not working

### ISSUE THREAD

**Issue by namirsab** [c9/core#354]
OS: Linux 16.04 64 bits
Browser: Version 52.0.2743.116 (64-bit)

Error:
Language worker could not be loaded; some language features have been disabled

It disables all intelisense and autocomplete :(

**Comment by nightwing** [comment]
I am really sorry we weren't able to reply to this in a timely fashion.
Were you able to resolve this issue, if no please comment.

**Comment by namirsab** [comment]
It seems it was related to some extensions in chrome. I've solved it by disabling them all and then add them one by one.
