### ISSUE TITLE
Asciidoctor syntax

### ISSUE THREAD

**Issue by Fale** [c9/core#36]
Please add a syntax highlight for asciidoc files :)

**Comment by javruben** [comment]
Did you know you can add this yourself? http://ace.c9.io/#higlighter=&nav=higlighter

**Comment by nightwing** [comment]
We already have a highlighter for asciiDoc files, see attached screenshot
![asciiDoc](https://cloud.githubusercontent.com/assets/341801/6719693/d51f9d48-cdd5-11e4-80ef-f362d60beeb1.png)

**Comment by Fale** [comment]
That's true :). Thanks a lot.

I think it should auto-recognise asciidoc files based on the ".adoc" extention.

**Comment by Pike** [comment]
@javruben the doc still talks about patching modelist. Is there a way to "monkeypatch" that for a c9 plugin?

**Comment by nightwing** [comment]
@Fale added it in https://github.com/ajaxorg/ace/commit/5e872cca4bcb69387835dfc5ead7a7ed14f1e1f4, (there was no commonly used extension for asciidoc in 2012)

@Pike we can add api like
```js
ace = imports.ace
ace.registerSyntax({
    caption: "MyNewMode",
    aceMode: "path/to/ace/mode" | AceModeObject,
    extensions: "^Filename|ext1|ext2"
})
```

**Comment by Pike** [comment]
That'd be great.

**Comment by Fale** [comment]
Thanks :)
