### ISSUE TITLE
Collab Fails: SQLITE_BUSY

### ISSUE THREAD

**Issue by jaredallard** [c9/core#361]
I've setup c9 core, and collab seems to fail to work (when enabled with `--collab`) with:

```js
Object {
stack: "248: 284: Error: SQLITE_BUSY: database is locked↵    at Error (native)", code: "SQLITE_BUSY", message: "SQLITE_BUSY: database is locked"}
code: "SQLITE_BUSY"
message: "SQLITE_BUSY: database is locked"
stack: "248: 284: Error: SQLITE_BUSY: database is locked↵    at Error (native)"
}
```

I invoke c9 like such: `pm2 start --no-daemon --name cloud9 server.js -- -p 80 -l 0.0.0.0 -a : -w "/workspace" --collab`

**Comment by nightwing** [comment]
maybe there is another cloud9 process trying to access same sqlite db?

**Comment by jaredallard** [comment]
@nightwing Could be that, where is the SQLITE db located?

**Comment by jaredallard** [comment]
Yes that's it, collab works when linking the DB to a non nfs drive. Is their anyway to configure .c9 in the workspace directory, like where it goes.

**Comment by nightwing** [comment]
there is no good way to configure it, but it is defined in https://github.com/c9/c9.ide.collab/blob/master/server/collab-server.js#L146

**Comment by jaredallard** [comment]
@nightwing Would it be useful for me to implement the ability to specify it via PR?

**Comment by nightwing** [comment]
yes, i think, that would be useful
