### ISSUE TITLE
Uncaught TypeError: eio is not a function

### ISSUE THREAD

**Issue by rimmartin** [c9/core#362]
I cloned a fresh install today and ran the ./scripts/install_sdk.sh and the ./scripts/setup-local-dev.sh.  Then launched it with node server.js -p 8182 -l 0.0.0.0 -a :

Get an Error with both firefox and chrome developer tools saying:

```
Uncaught TypeError: eio is not a function    static/plugins/c9.vfs.client/vfs_client.js:105 Uncaught TypeError: eio is not a function
```

Otherwise spins the wheel of infinity

**Comment by nightwing** [comment]
looks like npm install didn't work. try running `npm install` command

**Comment by rimmartin** [comment]
I bumped the engine.io  from "1.6.9" to "1.6.11" and ran ./scripts/install_sdk.sh again.  Stood it up and it started working

maybe a rerun of  ./scripts/install_sdk.sh would have done it. @nightwing if you want the info I can set the version back and run another install sdk test?

**Comment by rimmartin** [comment]
I did that before seeing your reply
