### ISSUE TITLE
Feature request: dotnet

### ISSUE THREAD

**Issue by tristandostaler** [c9/core#363]
Hey!

Sorry if someone already made that request. I looked for and didn't find it.

I was thinking it would be nice tu support dotnet core: 
https://www.microsoft.com/net/core#ubuntu

The runner would be easy to implement (something simple like "dotnet restore && dotnet run") and c# is already supported in the available languages.

Thanks!

**Comment by rogersachan** [comment]
https://github.com/codenvy/dockerfiles/tree/master/dotnet_core
