### ISSUE TITLE
Navigation between panes

### ISSUE THREAD

**Issue by codeHatcher** [c9/core#366]
is there a shortcut for navigating to the left, right, top, bottom panes like in vim, emacs, atom, etc. It's the one of the few things stopping me from using c9 with a dedicated server I have setup

**Comment by nightwing** [comment]
https://github.com/c9/c9.ide.behaviors/compare/db32109ebc24e7348bf0bd40ad3b699b0a35007a...6fe68dea3b74910ffed9673ba4b0221fc0957cb0 added commands but without default keybindings (they can be configured from preferences panel).
Do you know what other editors use for these commands?
