### ISSUE TITLE
Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by lordloh** [c9/core#368]
```
$ git commit
Couldn't get a file descriptor referring to the console
error: There was a problem with the editor '`which c9` open --wait'.
Please supply the message using either -m or -F option.
```

Why do I get this error? I can type `nano` and get an editor.

**Comment by nightwing** [comment]
Most likely this means `Terminal>use loud9 as default editor` option is activated but c9 in not installed globally. run `npm i -g c9` or if you are using sdk link bin/c9 to ~/bin or /usr/local/bin

**Comment by lordloh** [comment]
Thanks. I created a symbolic link of `/home/bharath/c9sdk/bin/c9` -> `/usr/local/bin/c9`. Now git commit opens an editor tab instead of nano :-)
