### ISSUE TITLE
Installation fails, repository changed?

### ISSUE THREAD

**Issue by raginrob** [c9/core#370]
I've just tried to install the Cloud9 IDE by the basic steps, but the installation fails because the repository mentioned in the error seems to have changed:

```
npm ERR! Command failed: git clone --template=/home/root/.npm/_git-remotes/_templates --mirror git://github.com/lennartcl/tern.git /home/root/.npm/_git-remotes/git-github-com-lennartcl-tern-git-ae5567e9
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Connection timed out
```

**Comment by nightwing** [comment]
Sounds like you are trying to install an old version. Latest package.json doesn't have a reference to that repository https://github.com/c9/core/blob/master/package.json#L35

**Comment by ricky0221** [comment]
I had the same problem and changed "/c9sdk/node_modules/tern_from_ts/package.json"
changed "tern": "git://github.com/lennartcl/te...............
to 
"tern": "git**+https**://github.com/lennartcl/te....................

**Comment by raginrob** [comment]
I wanted to install it again yesterday and tried to recursively sed search/replace every occurance of github.com/lennartcl with github.com/cloud9ide, but there still are errors. I'm not experienced enough to know where I need to make the right changes... maybe someone can look at this issue? You only need to freshly clone the core and then run the install script to run into the errors.

**Comment by ricky0221** [comment]
You could try this on your console' s command line

`git config --global url."https://".insteadOf git://`

ref:
https://github.com/c9/core/issues/311#issuecomment-224652682

**Comment by nightwing** [comment]
https://github.com/c9/core/blob/master/package.json#L36 doens't have references to `github.com/lennartcl` so it shouldn't happen on freshly cloned core.
> You only need to freshly clone the core and then run the install script to run into the errors.

it doesn't show errors on most systems. Please tell us which os do you use, and show the errors it prints.
Thanks!
