### ISSUE TITLE
"Don't pause on exceptions" button's position is wrong (for retina pc's)

### ISSUE THREAD

**Issue by ozcanovunc** [c9/core#371]
- As I attached the screenshot, the icon's position is misplaced.

![image-2016-10-18-10-55-21-253](https://cloud.githubusercontent.com/assets/13097409/19521179/6b24c318-961b-11e6-8815-7689e431e9ff.png)

**Comment by ozcanovunc** [comment]
Any updates?

**Comment by ozcanovunc** [comment]
Any updates?

**Comment by ozcanovunc** [comment]
Any updates?

**Comment by alperozisik** [comment]
@nonken ?

**Comment by nightwing** [comment]
The icon itself was misaligned. We have merged an alternative pr fixing the icon instead.
Thanks for helping to fix the issue.
