### ISSUE TITLE
"Deactivate all breakpoints" disappears (for retina pc's)

### ISSUE THREAD

**Issue by ozcanovunc** [c9/core#372]
- When you click on it, it disappears.

![image-2016-10-18-10-56-39-576](https://cloud.githubusercontent.com/assets/13097409/19521294/c17dcf66-961b-11e6-84ac-199c44bc7181.png)

**Comment by ozcanovunc** [comment]
Any updates?

**Comment by ozcanovunc** [comment]
Any updates?

**Comment by ozcanovunc** [comment]
Any updates?

**Comment by alperozisik** [comment]
@nonken

**Comment by nightwing** [comment]
There were many icons missing in retina mode https://github.com/c9/newclient/commit/ab63c6bc619c06629a4479bbcec7a7bb8a0a525a added code to check for the issues like this during the build step of css files.
