### ISSUE TITLE
console syntax highlighting in terminal

### ISSUE THREAD

**Issue by ludoo0d0a** [c9/core#38]
Is it possible to change color of console output in the terminal based on the level (console.warn, console.error, console.log...) ?

**Comment by nightwing** [comment]
This is only possible to do from inside your application.
Something like https://coderwall.com/p/yphywg/printing-colorful-text-in-terminal-when-run-node-js-script#comment_18334

**Comment by ludoo0d0a** [comment]
Thanks for the link.
This is a good idea.
