### ISSUE TITLE
help I messed up trying to uninstall npm!!

### ISSUE THREAD

**Issue by euphoricdog** [c9/core#381]
I was trying to uninstall nodejs to installa newer version and I messed up while uninstalling npm:

`
49 error tar.unpack untar error /home/ubuntu/.npm/bitcore/4.1.0/package.tgz
50 verbose unlock done using /home/ubuntu/.npm/_locks/bitcore-b089c130d04557fc.lock for /nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/bitcore
51 verbose fstream_path /nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/bitcore
52 verbose fstream_type Directory
53 verbose fstream_class DirWriter
54 verbose stack Error: EROFS: read-only file system, mkdir '/nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/bitcore'
54 verbose stack     at Error (native)
55 verbose fstream_stack /nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25
55 verbose fstream_stack /nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53
55 verbose fstream_stack FSReqWrap.oncomplete (fs.js:82:15)
56 verbose cwd /home/ubuntu/workspace/nicolascage_projects/bcoin_tests
57 error Linux 4.2.0-c9
58 error argv "/nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/bin/node" "/mnt/shared/sbin/npm" "install" "bitcore" "-g"
59 error node v4.3.1
60 error npm  v2.14.12
61 error path /nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/bitcore
62 error code EROFS
63 error errno -30
64 error syscall mkdir
65 error rofs EROFS: read-only file system, mkdir '/nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/bitcore'
65 error rofs This is most likely not a problem with npm itself
65 error rofs and is related to the file system being read-only.
65 error rofs
65 error rofs Often virtualized file systems, or other file systems
65 error rofs that don't support symlinks, give this error.
66 verbose exit [ -30, true ]
67 verbose unbuild lib/node_modules/bitcore
68 silly gentlyRm /nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/bitcore is being purged from base /nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1
69 verbose gentlyRm don't care about contents; nuking /nix/store/ajr6i77s89gjfjm59aazc16b5rvb39n7-nodejs-4.3.1/lib/node_modules/bitcore
`

**Comment by nightwing** [comment]
Is this related to cloud9?
Try using nvm which is simpler to install https://github.com/creationix/nvm#install-script
