### ISSUE TITLE
Update ace to reflect Jade name change

### ISSUE THREAD

**Issue by controversial** [c9/core#390]
Due to trademark issues, [the Jade language has been renamed to `pug`](https://github.com/pugjs/pug/issues/2184), and the `.jade` ending changed to `.pug` along with this. Cloud9 should highlight `.pug` files with the Jade syntax by default in light of this change.

**Comment by controversial** [comment]
Looks like this change has already been merged into [ace](https://github.com/ajaxorg/ace), so the latest Ace just needs to be used.

See: https://github.com/ajaxorg/ace/pull/3155

**Comment by nightwing** [comment]
fixed by https://github.com/c9/core/commit/9762b5ea441527c1ad0a1164f695d29a004b1ee6

**Comment by controversial** [comment]
Really? That diff doesn't seem to show anything related to the `jade` mode, it looks like only the definitions for `HTML` and `Haskell_Cabal` were changed.

**Comment by nightwing** [comment]
this time it is fixed for real https://github.com/c9/core/blob/ee77c2aa8558c1f09ee130997baf5686dad83b88/node_modules/ace/lib/ace/ext/modelist.js#L100 :)
