### ISSUE TITLE
Auth argument not working

### ISSUE THREAD

**Issue by zhillb** [c9/core#391]
I'm running my server like: 
" nodejs ./server.js -p 3000 -a usr:pass "

And the page will be blank. If I run it without the authentication it starts just fine. The only thing I changed in the code was to change 127.0.0.1 to 0.0.0.0 because I am running this remotely.

Hopefully there isn't something obvious I'm missing. Cheers!

**Comment by nightwing** [comment]
do you get the same issue when passing -l 0.0.0.0 instead of changing the code?

**Comment by zhillb** [comment]
Nope that fixes it... I didn't realize I could do that. Thank you
