### ISSUE TITLE
Error when c9 Desktop is launched : define is not defined

### ISSUE THREAD

**Issue by sr229** [c9/core#395]
Seems RequireJS defines are not defined somehow

![image](https://cloud.githubusercontent.com/assets/14976516/23063495/da380ce0-f545-11e6-8e9b-1133b2a04fc4.png)

**Comment by khusamov** [comment]
I also have the same problem. I can not start the IDE. On OS Windows 10.

**Comment by nightwing** [comment]
Thanks for reporting the issue, we have a fix in a pull request, which should be merged later today, you can also add `require("amd-loader");` to https://github.com/c9/core/blob/master/local/server.js#L1 until that is done
