### ISSUE TITLE
working with express on c9sdk

### ISSUE THREAD

**Issue by abubakaralsadiq** [c9/core#398]
hlo, every i really need some help i have install express on c9sdk using npm install and every thing was ok but the problem was i have no idea how run the server i tried using 

var express = require("express");
var app = express();

app.get("/", function(req,res){
    res.send("Hi there from Abubakar");
});

app.listen(3000,function(){
    console.log("server has been starter");
});

it return server has been starter but when i visit localhost 3000 it  gives me an error . i didn't know how to fix it  ,pls help i really need it

**Comment by nightwing** [comment]
Hi, this issue tracker is for questions about c9 sdk itself,  the code above doesn't look related to cloud9.

**Comment by abubakaralsadiq** [comment]
yah ,hw can you work express on the sdk
