### ISSUE TITLE
codeintel_server failed, not responding, or not installed yet

### ISSUE THREAD

**Issue by jcloutz** [c9/core#410]
I am receiving the following errors for PHP code intel after following the instructions to install `c9.ide.language.codeintel` plugin.

```
Error: [codeintel_worker] Daemon failed: !!Not installed

    at codeintel_worker.js:239
    at Array.<anonymous> (worker_util.js:167)
    at Sender.EventEmitter._signal (event_emitter.js:76)
    at window.onmessage (worker.js:200)
```

```
193: 212: Error: Command failed: curl -H Expect: -s --data-binary @- localhost:10881?mode=completions&row=65&column=12&language=PHP&path=app%2FHttp%2FControllers%2FApiUserController.php&dirs=/Users/jeremycloutier/laravel/project/.,/Users/jeremycloutier/laravel/project/./vendor
```

In a file when i type `$` start typing a variable name I get with the following message even after virtuelenv is installed. So I think there is something else happening that is preventing it from being installed but I'm not sure how to find out what it is.

```
Code completion is available for the language you are currently working with.

To install it on your own host, please follow our installation guide. Would you like to open the guide now?
```

I also posted an issue on the `c9.ide.language.codeintel` repo: https://github.com/c9/c9.ide.language.codeintel/issues/6

**Comment by nightwing** [comment]
closing, posting the issue in one of the repositories is enough
