### ISSUE TITLE
Regression: ./build/build-standalone.sh broken

### ISSUE THREAD

**Issue by RobertCNelson** [c9/core#411]
@nightwing 
From git:
```
./scripts/install-sdk.sh
./scripts/makestandalone.sh --compress

./build/build-standalone.sh
cp: cannot stat 'configs/client-default.js': No such file or directory
```

looks like it was nuked in:

https://github.com/c9/core/commit/eb3a574f963cde77825e7d419c09cc4fb705d6bb

Regards,

**Comment by nightwing** [comment]
should be fixed by https://github.com/c9/core/commit/d54e4f8f709f06348d51353c939ba4a2a0f21354, please check.
