### ISSUE TITLE
Reproduction Questions

### ISSUE THREAD

**Issue by ConProgramming** [c9/core#412]
More of a question than an issue (and yes I have read the license I'm just still confused), can I edit and then reproduce this software as a chrome web app? I would link back to here of course in my credits, but can i make a bunch of changes and then reproduce?

And does whether or not its open source change this in any way?

**Comment by nightwing** [comment]
What kind of chrome extensionare are you asking about? Will it connect to c9.io or be for editing  local files on a chromebook?

Being open source is not required by the sdk licence, but being non-commercial is.

**Comment by ConProgramming** [comment]
My chrome app would be for editing files from a chromebook, and it would of course be non commercial. 

And I don't think it would compete with the cloud9 chrome extension, because my app would be focused on self hosted people who would like to use something based off of the great cloud 9 platform

**Comment by nightwing** [comment]
Sorry for the delay with the reply. We were checking with legal department if this is allowed.

The license allows to distribute code of the plugin ([LICENSE#L45](https://github.com/c9/core/blob/master/LICENSE#L45)), but unfortunately it doesn't say anything about including sdk files with it.
Maybe you can load the workspace file from a cdn? That would also help users to always have the latest version of cloud9.

From the technical point of view i think you need to use an approach similar to https://github.com/c9/core/blob/master/plugins/c9.vfs.standalone/www/ide.offline.html#L44, which provides custom vfs implementation that can save small files in  localStorage and works without any server http://c9.github.io/core/build/standalonebuild/ide.offline.html

**Comment by nightwing** [comment]
Closing, but please let us know if using the cdn works for you, or you need the license to be changed.
