### ISSUE TITLE
Error: Failed to load resource - lib_apf.js

### ISSUE THREAD

**Issue by Sanzhar-Danybayev-Excelsior** [c9/core#413]
Hello! 
I keep getting the following error - "Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING - lib_apf.js" 
Has anyone faced the same problem?

**Comment by nightwing** [comment]
it appears this can be caused by the antivirus http://thisinterestsme.com/err_incomplete_chunked_encoding/

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@nightwing thanks for your answer! Unfortunatelly the given article does not solve my problem. Morever I don't have any antiviruses installed on my PC.

**Comment by nightwing** [comment]
Are other scripts loading? Which browsers did you try? did you try running with different port? Is sdk running on the same PC?

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@nightwing I tried other browsers as well. These are Opera and Firefox, they also can't load that script. All scripts but this one load without any errors. No, SDK is running on my VPS. 3 months ago I was using Cloud9 the same way I try using it right now, but I didn't have any errors back then. 
I didn't try to use different port yet, I'll try it now, but I suppose it won't solve the problem.

**Comment by nightwing** [comment]
It could solve the problem if it was caused by cache
Also try opening the ide with ?packed=1

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
![image](https://cloud.githubusercontent.com/assets/13291424/24895928/89c0b788-1eb4-11e7-82de-3660607b4cca.png)
Unfortunately none of it helped. 
As you can see on the image this lib fails to be loaded

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@nightwing here's the error itself 
![image](https://cloud.githubusercontent.com/assets/13291424/24895993/c88db4a2-1eb4-11e7-9006-7939c3de09fe.png)

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@nightwing if we go to mini_require.js  then we'll see where error occurs 
![image](https://cloud.githubusercontent.com/assets/13291424/24896026/ed831f9a-1eb4-11e7-9b86-569907dcbaf0.png)

**Comment by nightwing** [comment]
Did you try `?packed=1` it should load different files

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@nightwing yes, I tried but it gives the same error

**Comment by nightwing** [comment]
Same error but for the different file? Is cloud9 running behind a proxy? Seems like a network related issue not something caused by cloud9. (btw it is good to set password for cloud9)

**Comment by Sanzhar-Danybayev-Excelsior** [comment]
@nightwing Finally solved it! You were right, it was network related issue.  I tried to  change port again and fix some directives in my nginx.conf file. Thank you man for your attention and help!
