### ISSUE TITLE
c9 open <file> gives ENOENT could not open error - please help!

### ISSUE THREAD

**Issue by DJPinchoff** [c9/core#414]
```
connect ENOENT /home/ubuntu/workspace/.c9/bridge.socket
Could not open  [ { path: '~/intro_to_programming_book/Methods/say.rb',
    type: 'file' } ]
```

I'm trying to install c9 into the Terminal on cloud9.  It seems like it was installed into the directory from which I ran `npm install c9`.  (It happens to be inside of a repo I made, so I'd like to figure out how to move that installation somewhere else and get this to work.)

Any help will be GREATLY appreciated!!

**Comment by nightwing** [comment]
use `npm install -g` to install globally

**Comment by DJPinchoff** [comment]
Thanks for trying to help.. Just tried that and received:

/home/ubuntu/.nvm/versions/node/v4.7.3/bin/c9 ->
/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/c9/bin/c9
c9@3.1.3534 /home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/c9

Then tried c9 README.md, but still received the ENOENT error.  :-(

**Comment by nightwing** [comment]
Are you asking about c9.io workspace or your installed version of sdk?
What does `ls -la ~/.c9` output?

**Comment by DJPinchoff** [comment]
I'm asking about a workspace on c9.io!

ls -la ~/.c9 gave me back this:

total 40
drwxr-xr-x  7 ubuntu ubuntu 4096 Apr 14 03:46 ./
drwxr-xr-x 22 ubuntu ubuntu 4096 Apr 14 18:20 ../
-rw-r--r--  1 ubuntu ubuntu  116 Apr  6 12:27 .nakignore
drwxr-xr-x  2 ubuntu ubuntu 4096 Apr 14 03:46 bin/
-rw-r--r--  1 ubuntu ubuntu    2 Apr 14 03:46 installed
drwxr-xr-x  3 ubuntu ubuntu 4096 Apr 14 03:46 lib/
drwxr-xr-x  5 ubuntu ubuntu 4096 Apr 14 04:13 metadata/
drwxr-xr-x  7 ubuntu ubuntu 4096 Apr 14 03:46 node/
drwxr-xr-x  7 ubuntu ubuntu 4096 Apr 14 03:46 node_modules/
-rw-r--r--  1 ubuntu ubuntu 2273 Apr 14 16:41 project.settings

**Comment by nightwing** [comment]
That's strange, please write to support@c9.io, referencing this issue, and telling the url of your workspace.

**Comment by DJPinchoff** [comment]
Will do. thanks again!

**Comment by nightwing** [comment]
this was happening because HOME directory was modified in bashrc, so the ide and the cli couldn't find each other.
