### ISSUE TITLE
Stuck on "Loading Your Workspace" splash screen

### ISSUE THREAD

**Issue by jhershkowitz** [c9/core#42]
I have the core installed on a Fedora server. The app runs, and I can bring up the website - however it just sits on the "Loading your workspace" splash screen. There are no errors on the console. Any suggestions, or is there a log somewhere I can take a look at to see what it is hanging on?

- Using node v0.10.37
- node /usr/share/c9sdk/server.js -a user:password -p 3131

**Comment by nightwing** [comment]
This can happen if some of the plugins were not installed correctly, and there must be some errors in the browser console. 
Did `./scripts/install-sdk.sh` print any errors?

**Comment by jhershkowitz** [comment]
I dont recall ...  I just re-ran ./scripts/install-sdk.sh - and it came back with:
configure: error: "curses not found"

**Comment by nightwing** [comment]
There seems to be an error while installing tmux.
https://github.com/c9/install/blob/master/install.sh#L271

Try to install it with apt-get and then run install-sdk again

**Comment by jhershkowitz** [comment]
Bingo! Installing TMux allowed the install-sdk to run to success.. Its all up and working now.
