### ISSUE TITLE
Workspace reloads endlessly with --collab and Nginx

### ISSUE THREAD

**Issue by dinvlad** [c9/core#421]
Hi all,

I've set up a workspace to go through Nginx and it's working well. However, when I run it with `--collab` and open _any_ file, the workspace starts to 'reconnect' in an endless loop. I also get a lot of `WebSocket is already in CLOSING or CLOSED state` and `GET http://localhost:8079/vfs/1/xxxxx?access_token=token 499 (unknown)` errors in the browser console (Chrome 58).

I'm starting it with
```
node server.js -p 8079 --collab -w /home/c9/workspace
```
and my Nginx config is
```
worker_processes auto;

events {
  worker_connections 200;
}

http {
  map $server_port $port {
    '~^9(?<p>[\d]{3})$' $p;
  }

  server {
    listen 9079;
    listen 9080;
    listen 9081;
    listen 9082;

    location / {
      proxy_pass http://127.0.0.1:8$port;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection upgrade;
    }
  }
}
```
As you can see, there's an entry to 'upgrade' http:// to ws:// as suggested in other threads. But it doesn't seem to work for `/vfs/` endpoints associated with `--collab`.

EDIT: I've also played around with other options, including keepalive, timeouts, etc. to no avail.

Thanks

**Comment by nightwing** [comment]
that's strange collab uses same websocket as non collab mode, did you check if it works without nginx proxy?

**Comment by nightwing** [comment]
this most likely was casued by a bug from https://github.com/c9/core/commit/2795ef0379f040e9b3216b2ef93d184bdee2f271#diff-4f31e5755ccce46cf0a919c4de2f60f2R1944, it is fixed in https://github.com/c9/core/commit/6103223b2ca2fb2868868bed0e1db71d9a6dc58c

**Comment by dinvlad** [comment]
You're right, thanks! It's working without reloads now.
