### ISSUE TITLE
Outline panel tree elements beyond two levels

### ISSUE THREAD

**Issue by BigChief45** [c9/core#426]
When displaying a Markdown file's outline using the Outline panel at the right-hand side, headings are only displayed and indented up to two levels.

For example:

```markdown
# Level 1 heading

## Level 2 heading

## Level 3 heading
```

Produces:

![image](https://cloud.githubusercontent.com/assets/6859247/26195376/2f322408-3bee-11e7-8dd8-d0538ad25950.png)

I am aware that the plugin (Although not sure which plugin it is) that is in charge of this probably works in a generic way to handle all file types.

I would be willing to provide a PR, but some guidance on where the source code behind this is would be appreciated.

**Comment by nightwing** [comment]
this is handled in https://github.com/c9/core/blob/master/plugins/c9.ide.language.jsonalyzer/worker/handlers/jsonalyzer_md.js#L14, but i am not sure why does it use ctagsUtil, it seems like searching with one regex would be simpler and work better

**Comment by BigChief45** [comment]
I don't really know what ctagsUtil is.

In any case, should the fix be made in that file or in the [c9.ide.language.jsonalyzer](https://github.com/c9/c9.ide.language.jsonalyzer) repository?

**Comment by BigChief45** [comment]
@nightwing Bump.

**Comment by nightwing** [comment]
I meant doing iteration over lines ourselves, so that indentation level would be found by the number of `#`s.
But I am not 100% sure if that's the best way. @lennartcl do you know if there is a better approach?

**Comment by lennartcl** [comment]
In principle this could be solved with some more logic in JavaScript, as @nightwing suggests. As you can see in the lines @nightwing linked above, we now only have regexes for 1 and 2-level headings. It might be a bit more complex, so I'm not entirely sure it's worth adding more logic over adding more regexes for deeper level headings.

> In any case, should the fix be made in that file or in the c9.ide.language.jsonalyzer repository?

The change could be made in either repository.
