### ISSUE TITLE
File history dies when file name changes?

### ISSUE THREAD

**Issue by EricBalingit** [c9/core#429]
I recently realized that when I change the name of a file - given that it represents the same information as the file of the former name - the history goes blank and I can no longer revert.

Any way to recover that history and apply it to the newly named file?

I made this mistake in the process of duplicating, renaming and trying to revert manually.

Is there a way ( internally, within a workspace, but not on git ) for example to branch a file or multiple files?

**Comment by nightwing** [comment]
you can create a file with old name, the history will show changes before renaming too

**Comment by EricBalingit** [comment]
Okay I'll try that. Thank you @nightwing.

If I have any more trouble I'll comment here again.
