### ISSUE TITLE
Installation error #caused by npm v5.0

### ISSUE THREAD

**Issue by tomitheninja** [c9/core#430]
When i tried to install Cloud9 offline npm had problem with these packages:
jade rename to pub
fs-promise
mz
uuid
ace_tree
minimatch
typescript
when i started server.js its required amd-loader then i copied manually the package to my installation folder
then same with architect [I set 777 permissions for c9sdk/node_modules]
then i got an error for c9/urls, i commented that in server.js but i got another with other c9/* package.
I tried to reinstall npm,node redownload&install c9sdk as and without superuser, but same every time.
I've got a fresh ubuntu 17.04 install, but it was working before with same programs.
Also after ./scripts/install-sdk and it said installation successful.

**Comment by nightwing** [comment]
Which version of npm do you use?
It looks like some of changes in npm5 are breaking cloud9.

**Comment by tomitheninja** [comment]
Thank you tha npm update caused to errors, however it looks npm 4.6 runs slower (2-3 times) than it used to me, but at least its working.

**Comment by CyberiumShadow** [comment]
just run the install script
then do `git reset HEAD --hard`

That fixes it and it should work after that

**Comment by CyberiumShadow** [comment]
@jankeromnes Just note, that I've seen a few issues with doing my "fix". At best its a bandaid, but I've noticed in error logs stuff about collab.sock being unable to be accessed etc, and multiple reconnecting... attempts in the IDE itself before it "stablises"

**Comment by nightwing** [comment]
https://github.com/c9/core/commit/0f337beaf5ac04746ede7ff215b31cc1da16e544 fixes the issue of scripts/install-sdk.sh not working with new npm. Please let us know if you still see errors.

Note that you may need to run `git fetch origin; git reset origin/master --hard` first, if working tree has 
 changes from previous installs.
