### ISSUE TITLE
node error (amd-loader)

### ISSUE THREAD

**Issue by herohamp** [c9/core#432]
root@-snip-:/var/www/c9sdk# node server.js --listen 0.0.0.0 --auth -snip-:-snip- -w /var/www 
module.js:487
    throw err;
    ^

Error: Cannot find module 'amd-loader'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/c9sdk/server.js:4:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by nightwing** [comment]
run `git reset --hard` after  `npm install`, the npm5 started deleting files in node_modules directory, which breaks cloud9.

**Comment by keith24** [comment]
After the reset, I get `Error: Cannot find module 'engine.io-client/engine.io.js'`

**Comment by keith24** [comment]
All I could do to get it to work was use npm v4.6: 

```
sudo npm i -g npm@4.6.1
sudo scripts/install-sdk.sh
git reset HEAD --hard
sudo npm i -g npm
```

Using v4.6 might work without the reset, but whatever.

**Comment by nightwing** [comment]
https://github.com/c9/core/commit/0f337beaf5ac04746ede7ff215b31cc1da16e544 fixes the issue of scripts/install-sdk.sh not working with new npm. Please let us know if you still see errors.

Note that you may need to run `git fetch origin; git reset origin/master --hard` first, if working tree has 
 changes from previous installs.

**Comment by yennycheung** [comment]
@nightwing Thank you for the fix!

**Comment by ronaldroe** [comment]
Still seeing these errors with latest version of c9. Nothing suggested works. I've tried with latest npm, The suggestion @keith24 posted doesn't help. I've tried wiping out my current copy of c9 and starting over, everything. Can't get it to work.

**Comment by rudolfolah** [comment]
@ronaldroe also having this issue; I wonder if Cloud9 development has shifted to whatever AWS is doing internally...
