### ISSUE TITLE
[Vulnerability] Password shows in $(ps aux)

### ISSUE THREAD

**Issue by regalstreak** [c9/core#435]
Could you devs implement something so that the node server doesn't show it? I do not have root and work on a shared server.

**Comment by nightwing** [comment]
I think whatever we do, someone with root access to the workspace can find the password, e.g. by attaching a debugger to the node process and inspecting local variables.

**Comment by regalstreak** [comment]
Well, that's just okay. I do not want other users to access it. The one with root access will always be able to take it and won't do lame stuff at least. Is there any way out?

**Comment by attritionorg** [comment]
Accepted that root can access. The issue with $(ps aux) is that any unprivileged user on the system can see the password. Many projects have dealt with this and there are workarounds.

**Comment by regalstreak** [comment]
Could you please show me one? If the owners ain't working on it, we will have to do something. As this is damn serious.

**Comment by attritionorg** [comment]
I wish I could, but sincerely, this is so common in projects most of us catalog the vuln and move on. I think the solution is you read the password from a file with proper permissions. Then the process listing shows the file as an argument, not the password. Some will argue a plaintext password in a file is bad, and sure, it is generally... but as long as the perms/ownership are correct, it is NOT an issue.

**Comment by regalstreak** [comment]
Has to be done on the nodejs part. I've tried editing some of the bash but it doesn't just work. We need to figure that out. I'm not proficient in nodejs hence can't do much about that

**Comment by attritionorg** [comment]
For bash, it is about using an argument to read input from a file. I'm just way too rusty on day-to-day shell script stuff to provide real advice. For nodejs, absolutely no clue. That is a foreign language to me. =)

**Comment by nightwing** [comment]
You can use a js file to pass arguments to server.js without passing them as arguments visible to ps
create a myserver.js file (in the same directory with server.js) with
```js
#!/usr/bin/env node
require("./server.js")(["-a", "x:y"]) // add any other arguments here
```

and use it instead of server.js

**Comment by regalstreak** [comment]
That's great. Will try as soon as I'm home

**Comment by regalstreak** [comment]
It works. But how do i pass multiple args @nightwing ?
I'm doing rubish like this:
```
#!/usr/bin/env node
require("./server.js")(["-a", "x:y"]["-l", "0.0.0.0"]["-w", "$HOME"]["-p", "8085"])
```

As I said, im completely new to nodejs.

**Comment by nightwing** [comment]
```js
#!/usr/bin/env node
require("./server.js")(["-a", "x:y", "-l", "0.0.0.0", "-w", process.env.HOME, "-p", "8085"])
```

**Comment by regalstreak** [comment]
Brilliant. Thanks a lot, man. You are the best!
