### ISSUE TITLE
TypeError: grunt.registerHelper is not a function

### ISSUE THREAD

**Issue by dabiiid** [c9/core#437]
Hi Good day,

I'm really new to grunt and having a lot of issues installing on it. first it when i type grunt less:

`vagrant@m2:/mnt/www/m2-fe-workshop$ grunt less:themedavid
Loading "less.js" tasks...ERROR
>> TypeError: grunt.registerHelper is not a function

Running "less:themedavid" (less) task
Warning: Cannot read property 'src' of undefined Use --force to continue.

Aborted due to warnings.

Execution Time (2017-07-03 11:01:37 UTC+2)
loading tasks       449ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 85%
loading grunt-less   68ms  ▇▇▇▇▇▇▇ 13%
less:themedavid       9ms  ▇ 2%
Total 528ms`

and if grunt exec:

`vagrant@m2:/mnt/www/m2-fe-workshop$ grunt exec:themedavid
Running "exec:themedavid" (exec) task
Running "clean:themedavid" (clean) task
>> 267 paths cleaned.

Done, without errors.

Execution Time (2017-07-03 11:01:42 UTC+2)
loading tasks     328ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 51%
clean:themedavid  311ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 48%
Total 645ms

Processed Area: frontend, Locale: en_US, Theme: vendordavid/themedavid, File type: less.
>> [InvalidArgumentException]
>>   Verify entered values of the argument and options. Unable to resolve the source file for 'frontend/vendordavid/themedavid/en_US/css/styles-m.less'
>>
>>
>>
>> dev:source-theme:deploy [--type="..."] [--locale="..."] [--area="..."] [--theme="..."] [file1] ... [fileN]
>> Exited with code: 1.
Warning: Task "exec:themedavid" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2017-07-03 11:01:41 UTC+2)
loading tasks    337ms  ▇▇ 4%
exec:themedavid   8.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 96%
Total 9.1s`

how can i fix it or what command to i need to do to work this properly?

Thank you in advance for answering this.
it will a big help for me.

Thanks :)

**Comment by nightwing** [comment]
hi,
seems like you have reported this on wrong issue tracker, cloud9 sdk is not related to grunt

**Comment by dabiiid** [comment]
sorry, im new to git also. should i delete this thread?

**Comment by dabiiid** [comment]
sorry wrong threat
