### ISSUE TITLE
c9sdk not loading anymore until complete system reboot

### ISSUE THREAD

**Issue by eslachance** [c9/core#438]
Hi! I have gotten this issue multiple times in the last year or so using c9. Essentially, attempting to open the IDE leaves it stuck on the loading screen, with the c9 logo and "random loading line". 

- There is no message in the browser's console
- There is no message output in the server console (using pm2)
- Shutting down c9 and restarting it does not resolve the issue
- The only way to fix it is to *completely* shut down the whole server and restart it. 

![image](https://user-images.githubusercontent.com/643344/27874040-24122b82-617c-11e7-8593-e8061693f333.png)

That's all I get. Is there any internal logs (not console.log) that I could look at that might reveal what's happening?

**Comment by nightwing** [comment]
There are only browser console, and server logs, nothing else.
But network tab in browser can be useful too, does it try to connect to /vfs and the websocket?

**Comment by eslachance** [comment]
In reference to #439 , updating to the latest version available in GIT does not resolve the issue. 

@nightwing literally all I get from the Network: 
![image](https://user-images.githubusercontent.com/643344/27880279-65d7e2d0-6192-11e7-871a-297cdcea27a7.png)

**Comment by eslachance** [comment]
I see a lot of JS being loaded by mini_require.js but there is nothing in the "WS" tab. I see no loading error, nothing that looks odd.

**Comment by eslachance** [comment]
![image](https://user-images.githubusercontent.com/643344/27880467-100e261a-6193-11e7-987f-eb8f4d5e6241.png)

**Comment by eslachance** [comment]
Ok there's definitely *some* sort of loading issue here. The file `static/engine.io/engine.io.js` is not correctly loading. Seems to be the only file with the issue, it stops loading here: 
![image](https://user-images.githubusercontent.com/643344/27881132-8ec3828c-6195-11e7-90c6-aa55c369e3b3.png)

As I mentioned, reloading the server does nothing, reinstalling from scratch on the new version did nothing. I'm not going to reboot the server as I know this will temporarily resolve it and I wouldn't be able to troubleshoot. As the rest of my stuff on this server (including wordpress and 3 bots) are working great, it really does seem to be a specific issue with c9sdk.

**Comment by eslachance** [comment]
Welp. I was wrong. Rebooting the system did not resolve the issue anymore. I am straight-up unable to use c9sdk on my VPS Server for the reason stated above.

**Comment by eslachance** [comment]
@nightwing I've tried to completely remove both the c9sdk and `.c9` folder on my system, rebooted, installed again, and I get nothing. Installing on a VM with the same OS (Ubuntu 16.04) works fine, however. 

I'm not sure how to proceed. I don't want to have to format my system because c9 refuses to load a single file.

**Comment by nightwing** [comment]
Does this happen when installing with npm 5 or with an older version?
Try adding console.log(eioClient) at
https://github.com/c9/core/blob/111819fc208428efb9009acdbb3251e84333ed32/plugins/c9.vfs.server/statics.js#L30
and see if the file path for which is logged, exists.
Another possible issue is that npm have cached a broken version of engine.io module.
Try running `npm cache clear` and then `npm install` again

**Comment by eslachance** [comment]
I don't believe it's an issue with the NPM version as, in my VM, I updated to the exact same version of node and npm and that worked. I did `npm cache clear --force` (because npm 5 claims that it self-heals from corruption). That still didn't work - no change in behaviour. 

So, I went "screw it" and downgraded to npm 3.10.10, rm -rf'ed the whole c9sdk directory, cleaned the npm cache, and am running everything from scratch again. 

Welp. It still does not work. I'm thoroughly confused, and annoyed. 

`console.log(eioClient)` returns: `/root/c9sdk/node_modules/engine.io-client/engine.io.js` which *does* exist on the system, and is complete according to a perusal with nano.

**Comment by nightwing** [comment]
Could you try running the ide with a different port, or opening in incognito window, in case there is an issue with browser cache?
Unfortunately I don't know of any thing that could cause content length to be wrong for only that one file.

**Comment by eslachance** [comment]
Ok. this is ridiculous. After a format it worked for a week or so, and now it's failing again, with no reason whatsoever.

**Comment by nightwing** [comment]
Does it still fail when loading engine.io?
Try opening with `?packed=1` in the url

**Comment by eslachance** [comment]
packed=1 gives me this: 
![image](https://user-images.githubusercontent.com/643344/28534984-c8656ac0-7070-11e7-9677-1dd8e1bbf3c6.png)

**Comment by eslachance** [comment]
If I let it go long enough, though, without packed=1 I get: 

![image](https://user-images.githubusercontent.com/643344/28541441-07d88c30-7087-11e7-807a-6c99e0f8b00c.png)

**Comment by nightwing** [comment]
This does not look like an issue with cloud9 sdk code. It is either something on your server or the network connection throttling large requests.

**Comment by eslachance** [comment]
Yeaaaaaaaaaaaaaaaaaaaaah funny story. Colleague comes up to me about 10 minutes ago, going "this JS file from our internal server is being truncated" (it was jQuery). It's half-loading and it keeps spinning instead of loading the whole thing. I show him my issue, he goes "yep. same thing. IT fucked up again, I need to go scream at them". 

To which I responded, "God fucking dammit. I have a github issue to close, and an apology to make"

My apology for the disturbance. I will go scream at IT with him.

**Comment by dangkiena3** [comment]
I have same problem and resolve it by turn off Adblock Plus Chrome extension.
