### ISSUE TITLE
Unable to load on NPM 5

### ISSUE THREAD

**Issue by eslachance** [c9/core#439]
NPM version 5 (released with node 8) has completely changed the way that dependencies function. Unfortunately, c9sdk is now completely nonfunctional in this version. I just learned this the hard way attempting to re-install from scratch because of #438 . 

The install itself seems to completely without errors, but attempting to start the server (or run `node servers.js --help`) will complain about modules not being found. Modules which are probably subdependencies, which are no longer directly useable if not part of the specific package.json that a module uses. So basically, `amd-loader` and `architect` are called from the main app but are sub-dependencies of something else, so they need to be reinstalled. 

I would have continued to install them however I hit a wall being told `Error: Cannot find module 'c9/urls'` which I don't know how to go around. 

To reproduce this, simply install nodejs version 8.1.3 , then run `npm i -g npm` to get the latest npm version. Then follow the instructions on how to install c9sdk as usual (git clone, install.sh). 

I fully understand that Node 8 is Current and not LTS. However, there's no denying that it's an issue that should be resolved as soon as possible. Right now, I am completely unable to use c9 at all which is a massive bummer.

**Comment by nightwing** [comment]
run `git checkout HEAD -- node_modules` after npm install

**Comment by eslachance** [comment]
Hmm. That's interesting. It did function. Perhaps this should be added to the install guide?

**Comment by eslachance** [comment]
Resolved with Nightwing's comment (though I'm not sure why)

**Comment by nightwing** [comment]
Sorry i didn't write more detailed explaination yesterday.
The issue happens because npm5 deletes all folders in node_modules that it didn't create,  so the dependencies which cloud9 has in git are deleted after npm install.
