### ISSUE TITLE
$HOME/.c9/node/bin/node: not found

### ISSUE THREAD

**Issue by seokbeomKim** [c9/core#441]
I'm trying to install cloud9 on a NAS which is armv7l architecture.
I've tried on opkg and debian chroot environment, but none of them can't install c9 with the install-sdk.sh script.
The error message prints out when the script downloads node.tar.gz from nodejs server and execute the binary(node). 

```
root@NAS4SBK:/home/root/Downloads/c9sdk# uname -a
Linux NAS4SBK 3.10.39 #10 SMP Wed Jun 21 10:48:02 KST 2017 armv7l GNU/Linux

...

Installing base packages. Use --help for more options
:Installing Node v4.4.6
--2017-07-07 08:12:24--  https://nodejs.org/dist/v4.4.6/node-v4.4.6-linux-armv7l.tar.gz
Resolving nodejs.org (nodejs.org)... 104.20.23.46, 104.20.22.46, 2400:cb00:2048:1::6814:162e, ...
Connecting to nodejs.org (nodejs.org)|104.20.23.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11495296 (11M) [application/gzip]
Saving to: ‘node.tar.gz’

node.tar.gz                   100%[===================================================>]  10.96M  3.05MB/s   in 3.6s

2017-07-07 08:12:29 (3.05 MB/s) - ‘node.tar.gz’ saved [11495296/11495296]

/home/root//.c9/node/bin/npm: 2: exec: /home/root//.c9/node/bin/node: not found
root@NAS4SBK:/home/root/Downloads/c9sdk# ls ~/.c9/node/bin/node  -l
-rwxr-xr-x 1 1000 1000 22260900 Jun 23  2016 /home/root//.c9/node/bin/node

root@NAS4SBK:/home/root/Downloads/c9sdk#
```

p.s.
Is there any way to install cloud9 manually without using the install script? And why it needs to download node binary without checking whether it is installed on global path like /usr/bin/{node, npm}?

**Comment by nightwing** [comment]
It downloads it's own version of node, because in the past many people complained, that when they update their global version of node cloud9 stopped working because pty.js in ~/.c9 was compiled with a different node version.

You can use the https://github.com/c9/install/blob/master/link.sh script before running install-sdk.sh, to manually install all required dependencies

**Comment by seokbeomKim** [comment]
Finally it's able to run without any problems. :D 
Thanks a lot!
