### ISSUE TITLE
on premises license?

### ISSUE THREAD

**Issue by jamesearlywine** [c9/core#442]
I like using cloud9 ide.  We currently host it on our own dev server (instead of cloud9-hosted), to satisfy concerns from security team.  I don't see a way to signup and pay for an on-premises per-seat license.  We really enjoy cloud9 for collaboration between our team-of-two-developers.  How can I pay you for that?

**Comment by nightwing** [comment]
Unfortunately we do not have an easy way to get on premise license, but according to the license you can use the sdk for free, so you are not required to pay.

If you want to help anyway, you can buy premium on c9.io.

**Comment by jamesearlywine** [comment]
well, I saw the commercial license indicated that we pay per seat, accommodate requests to verify seats etc.  

I'd like it better if the company I work for could pay instead of me, I'll see if they'll buy me and my co-worker premium accounts.  Thanks. :)
