### ISSUE TITLE
 [update sdk] Cannot find module 'c9/urls'

### ISSUE THREAD

**Issue by ximing** [c9/core#443]
nodejs v8.2.1
npm v5.3.0
after run scripts/install-sdk.sh ,get error message.
![image](https://user-images.githubusercontent.com/4659887/28535736-0a26b088-70d8-11e7-8c8d-7a4b539ad015.png)

**Comment by nightwing** [comment]
this happens because npm 5 deletes all untracked folders in node_modules.
Run `git checkout -- node_modules` to restore files deleted by npm

**Comment by ximing** [comment]
@nightwing it works for me, thx
