### ISSUE TITLE
Problem with installation "Error: Cannot find module 'c9/urls'"

### ISSUE THREAD

**Issue by MagicMonti** [c9/core#445]
I got some errors while installing cloud9 per shell script (some node packages are not found) so i decided to run server.js to look what happens, it throws some errors that some node modules are not installed yet, so I installed, but get en error when installing c9/urls

//when running the installation script
`--- Running npm install --------------------------------------------
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated node-uuid@1.4.3: Use uuid module instead
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/cloud9ide/emmet-core.git /root/.npm/_cacache/tmp/git-clone-b5dec830
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-b5dec830': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-02T18_34_17_407Z-debug.log
acorn
+ acorn@2.7.0
updated 1 package in 6.703s
amd-loader
+ amd-loader@0.0.8
updated 1 package in 5.971s
architect
+ architect@0.1.13
updated 1 package in 5.963s
async
+ async@0.9.2
updated 1 package in 5.951s
base64id
+ base64id@0.1.0
updated 1 package in 5.859s
chai
+ chai@1.5.0
added 1 package in 5.67s
connect
+ connect@2.30.2
added 70 packages, removed 4 packages and updated 14 packages in 15.728s
debug
+ debug@0.7.4
updated 1 package in 7.523s
ejs
+ ejs@1.0.0
updated 1 package in 8.279s
emmet
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/cloud9ide/emmet-core.git /root/.npm/_cacache/tmp/git-clone-153f70f9
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-153f70f9': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-02T18_36_03_593Z-debug.log`

//running server.js
`module.js:487
    throw err;
    ^

Error: Cannot find module 'c9/urls'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Desktop/c9sdk/server.js:12:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

//installing this missing module
`npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/c9/urls.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-02T18_30_40_344Z-debug.log`

**Comment by nightwing** [comment]
this is caused by braking changes introduced in npm v5, please use older version of npm, or do `git reset --hard` after npm install

**Comment by MagicMonti** [comment]
great it works

**Comment by sancarn** [comment]
@MagicMonti you should close the case

**Comment by askucher** [comment]
it does not

**Comment by nightwing** [comment]
https://github.com/c9/core/commit/0f337beaf5ac04746ede7ff215b31cc1da16e544 fixes the issue of scripts/install-sdk.sh not working with new npm. Please let us know if you still see errors.

Note that you may need to run `git fetch origin; git reset origin/master --hard` first, if working tree has 
 changes from previous installs.
