### ISSUE TITLE
HTML in Window > Tabs submenu

### ISSUE THREAD

**Issue by kzidane** [c9/core#446]
![](https://user-images.githubusercontent.com/788678/28842747-cbaa3294-76cc-11e7-907e-1cca174e09c6.png)

https://github.com/c9/core/blob/master/plugins/c9.ide.behaviors/tabs.js#L259

**Comment by Pike** [comment]
Same here. @nightwing, this seems to be a regression from 7ee0dbdbe467c9ff747a8576db8eecae3451d127 ?

**Comment by nightwing** [comment]
Fixed by https://github.com/c9/core/commit/cdde0b56c22126eb54812302c76edb410918069f, thanks for reporting!
