### ISSUE TITLE
The number of lines of the Output and Terminal panes are not configurable

### ISSUE THREAD

**Issue by benoitperrin-wr** [c9/core#45]
I am unable to find a configuration setting to define the number of lines defines for the Output and terminal panes,
As of today, it seems to be limited around 500 lines. Is there an hidden configuration for that, or is it missing?
Anyway, a user should be able to modify the amount of lines in those panes.

**Comment by nightwing** [comment]
There is a `Scrollback` setting in `Terminal` section of preferences tab.

**Comment by benoitperrin-wr** [comment]
Thanks nightwing, I just find it too, looking into the code. I was not used of the term 'Scrollback' to cover the history size.
The issue can be closed.
