### ISSUE TITLE
Failed to install SDK in mac

### ISSUE THREAD

**Issue by cwtuan** [c9/core#451]
Here is my environment:
- node v6.11.0
- mac OS X: 10.11.6 
- npm 3.10.10
How could I fix it?

```
$ scripts/install-sdk.sh
node.tar.gz                   100%[================================================>]   9.73M  11.5KB/s   in 15m 15ss

2017-08-31 19:56:53 (10.9 KB/s) - 'node.tar.gz' saved [10203634/10203634]


real	15m19.968s
user	0m1.919s
sys	0m1.695s
:Installing TMUX
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:371:in `open'
	from /usr/local/Library/Homebrew/utils.rb:401:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:429:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:164:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:160:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:203:in `dump'
	from /usr/local/Library/brew.rb:167:in `rescue in <main>'
	from /usr/local/Library/brew.rb:65:in `<main>'
```

**Comment by nightwing** [comment]
try installing tmux, before installing cloud9

**Comment by LoganDark** [comment]
This is designed to be run under Linux, not macOS

**Comment by nightwing** [comment]
@LoganDark this is designed to be crossplatform, so Windows, macOS, Linux, and BSD are supported.
@cwtuan did you manage to install tmux separately? Closing the issue, but please let us know if you still have any questions.

**Comment by mayanbhadage** [comment]
Not working for me either

From https://github.com/c9/core
 * [new branch]        c9         -> c9/c9
 * [new branch]        gh-pages   -> c9/gh-pages
 * [new branch]        master     -> c9/master
 * [new branch]        smf-sdk    -> c9/smf-sdk
Already up to date.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11769  100 11769    0     0  32966      0 --:--:-- --:--:-- --:--:-- 32966
Installing base packages. Use --help for more options
:Installing Node v6.3.1

real	0m4.431s
user	0m1.290s
sys	0m0.927s
:Installing TMUX
Warning: tmux 2.8 is already installed and up-to-date
To reinstall 2.8, run `brew reinstall tmux`
Installed tmux does not appear to work:

**Comment by sirgatez** [comment]
I have this same issue, TMux is installed and up to date.

**Comment by mayanbhadage** [comment]
I found one solution to it Some file checks the version 2.2 but now they got 2.8.. 
You have to edit that .. sorry I don't remember the name of file
