### ISSUE TITLE
html entity in user's menu

### ISSUE THREAD

**Issue by kzidane** [c9/core#452]
![screen shot 2017-09-05 at 5 49 38 pm](https://user-images.githubusercontent.com/7230211/30133770-0448627a-9323-11e7-9118-3418cefe6e0b.png)

**Comment by nightwing** [comment]
Fixed in https://github.com/c9/core/commit/672a730a7d4e5aba45e9befb92bc4b10a02d6773

**Comment by kzidane** [comment]
Thank you!
