### ISSUE TITLE
bash can access directories other than workspace

### ISSUE THREAD

**Issue by abhilash1in** [c9/core#459]
Starting c9 with `-w` option to specify a workspace will still allow bash in the IDE to access directories other than the workspace directories. Is this intended behaviour? This will essentially give the user access to see all files on the system.

**Comment by nightwing** [comment]
-w option is for setting workspace directory, there is no way to limit user access to some files

**Comment by tomitheninja** [comment]
try to create a new user w/ limited rights and run c9 there
