### ISSUE TITLE
Async/await doesn't seem to be supported in Cloud9 editor

### ISSUE THREAD

**Issue by jankeromnes** [c9/core#462]
When typing the following code into Cloud9's editor:

```js
async function random() { return 4; }

async function other() {
  return await random(); // ESLint says "random is not defined"
}
```

The editor's linter (ESLint I believe) will report the call to `random()` as referencing an undefined symbol, whereas it's clearly defined just above.

Here is a screenshot showing this problem:

![async-await-problem](https://user-images.githubusercontent.com/599268/31942960-6678f6a2-b8c7-11e7-9d5f-929270d64879.png)

**Comment by michaelmitchell** [comment]
Take a look at this replacement plugin I wrote which replaces the default linter, it supports custom parsers so you can use babel-eslint to support async/await.

https://github.com/michaelmitchell/c9.ide.language.javascript.eslintd

**Comment by nightwing** [comment]
the built-in version of eslint have been updated in https://github.com/c9/core/commit/413d628c801021fa7de938d8defdd30c6fcb9336

**Comment by thinkloop** [comment]
This doesn't seem to work:

```
const auth = await dynamicImportAuth;
```
