### ISSUE TITLE
closing terminal tab doesn't kill tmux session?

### ISSUE THREAD

**Issue by kzidane** [c9/core#465]
We've noticed that closing terminal tabs doesn't kill the associated `tmux` session and doesn't warn about killing child processes anymore. Is that intentional? 

In the screenshot below, the student only has one terminal tab open, and yet there are 3 `tmux` sessions:

![workspace](https://user-images.githubusercontent.com/7230211/32614413-3339d182-c53b-11e7-803b-bd3c0c0efac8.jpg)

![tmux-session](https://user-images.githubusercontent.com/7230211/32614326-02702f4c-c53b-11e7-9797-c39db1f970bf.png)

**Comment by nightwing** [comment]
Closing tab kills tmux session, but when using multiple windows it is possible to leave some sessions unattached by:
- opening second window, 
- opening new terminal tabs in the first window
- closing the first window
- switching tabs in the second window to make it save its state and override the state of the first window.

Does this cause problems for students?

We have `tmux>other sessions` menu in terminal context menu, but maybe there is a better way to display it.

**Comment by kzidane** [comment]
Thanks for elaborating, @nightwing! Sometimes a student spawns a server listening on `p`, and then  maybe do what you described, effectively getting the `tmux` session detached, and then trying to spawn a server that listens on `p` in another terminal tab which fails of course because `p` is in use.

We'll get around this by killing any process listening on `p` before starting the server. Was just double-checking that this is the expected behavior. Thanks again!
