### ISSUE TITLE
Cannot install: bufferevent not compiling

### ISSUE THREAD

**Issue by mwswindle** [c9/core#466]
UPDATE: Seems that install tmux fixed it for me. I'm running ArchLinux on this server, which also installed the libevent package when installing tmux.

I'm having the following issue running install-sdk.sh

bufferevent_openssl.c: In function 'bio_bufferevent_new':
**bufferevent_openssl.c:106:3: error: dereferencing pointer to incomplete type 'BIO {aka struct bio_st}'
  b->init = 0;**
   ^~
bufferevent_openssl.c: At top level:
**bufferevent_openssl.c:228:1: error: variable 'methods_bufferevent' has initializer but incomplete type
 static BIO_METHOD methods_bufferevent = {**
 ^~~~~~
bufferevent_openssl.c:79:27: warning: excess elements in struct initializer
 #define BIO_TYPE_LIBEVENT 57
                           ^
bufferevent_openssl.c:229:2: note: in expansion of macro 'BIO_TYPE_LIBEVENT'
  BIO_TYPE_LIBEVENT, "bufferevent",
  ^~~~~~~~~~~~~~~~~
bufferevent_openssl.c:79:27: note: (near initialization for 'methods_bufferevent')
 #define BIO_TYPE_LIBEVENT 57
                           ^
bufferevent_openssl.c:229:2: note: in expansion of macro 'BIO_TYPE_LIBEVENT'
  BIO_TYPE_LIBEVENT, "bufferevent",
  ^~~~~~~~~~~~~~~~~
bufferevent_openssl.c:229:21: warning: excess elements in struct initializer
  BIO_TYPE_LIBEVENT, "bufferevent",
                     ^~~~~~~~~~~~~
bufferevent_openssl.c:229:21: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:230:2: warning: excess elements in struct initializer
  bio_bufferevent_write,
  ^~~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:230:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:231:2: warning: excess elements in struct initializer
  bio_bufferevent_read,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:231:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:232:2: warning: excess elements in struct initializer
  bio_bufferevent_puts,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:232:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:233:2: warning: excess elements in struct initializer
  NULL /* bio_bufferevent_gets */,
  ^~~~
bufferevent_openssl.c:233:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:234:2: warning: excess elements in struct initializer
  bio_bufferevent_ctrl,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:234:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:235:2: warning: excess elements in struct initializer
  bio_bufferevent_new,
  ^~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:235:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:236:2: warning: excess elements in struct initializer
  bio_bufferevent_free,
  ^~~~~~~~~~~~~~~~~~~~
bufferevent_openssl.c:236:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:237:2: warning: excess elements in struct initializer
  NULL /* callback_ctrl */,
  ^~~~
bufferevent_openssl.c:237:2: note: (near initialization for 'methods_bufferevent')
__bufferevent_openssl.c:228:19: error: storage size of 'methods_bufferevent' isn't known
 static BIO_METHOD methods_bufferevent = {__
                   ^~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:793: bufferevent_openssl.lo] Error 1
make[2]: Leaving directory '/home/mac/.c9/libevent-2.0.21-stable'
make[1]: *** [Makefile:857: all-recursive] Error 1
make[1]: Leaving directory '/home/mac/.c9/libevent-2.0.21-stable'
make: *** [Makefile:592: all] Error 2

**Comment by nightwing** [comment]
Does this break the ide? bufferevent should be an optional requirement.

**Comment by mwswindle** [comment]
actually probably not. I was getting a second error (amd-something not found, caused by npm5) but thought it was related to this issue. I did solve it by installing TMUX first, which also installed libevent with it.

**Comment by hgw77** [comment]
Hi I think that problem still exist. I got the same error when installed cloud9 on debian stretch (tmux was already installed).  I digged a little deeper and it seems the tmux version in debian stretch is to new? The install script is checking for tmux Version 1.9.X  and if there is a different version it is trying to compile tmux 1.9 and than it breaks with the same error reported here.

With Debian jessie installation is working fine because the correct tmux version is available.

**Comment by nightwing** [comment]
@hgw77 what does `tmux -V` print for you? the code at https://github.com/c9/install/blob/master/install.sh#L330 is supposed to check for tmux newer than 1.7

**Comment by hgw77** [comment]
Ok found the problem, something was wrong with my locale settings so tmux complained `tmux: need UTF-8 locale (LC_CTYPE) but have ANSI_X3.4-1968` and that brokes the version check

**Comment by drmrbrewer** [comment]
@hgw77 I have that exact same `tmux` error about locale.  How did you fix it?

**Comment by hgw77** [comment]
@drmrbrewer this is some time ago but I found the related commit in my Dockerfile

````
RUN echo 'locales locales/default_environment_locale select de_DE.UTF-8' | debconf-set-selections && \
    echo 'locales locales/locales_to_be_generated multiselect de_DE.UTF-8 UTF-8' | debconf-set-selections && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y locales

ENV LC_ALL=de_DE.UTF-8 
ENV LANG=de_DE.UTF-8 
ENV LANGUAGE=de_DE.UTF-8
```` 

this fixed the problem for me. Hopefully that helps :-)

**Comment by drmrbrewer** [comment]
@hgw77 thanks so much!  I'm using a variant of your suggestion, which has solved the problem... thanks!
