### ISSUE TITLE
IDE Terminal Monitor failed to start: require(...) Is not a function

### ISSUE THREAD

**Issue by sr229** [c9/core#471]
![image](https://user-images.githubusercontent.com/14976516/33697709-3bb19dea-db43-11e7-8daf-7d5aa5be8acf.png)

While testing it on a GCP Devshell, I encountered this

**Comment by nightwing** [comment]
Sounds like plugins/c9.ide.terminal.monitor/message_matchers.js is either changed in your installation, or some add blocker or a proxy is modifying it.

Try opening the file in browser and comparing it with the version from github https://github.com/c9/core/blob/master/plugins/c9.ide.terminal.monitor/message_matchers.js

**Comment by sr229** [comment]
@nightwing don't think so, I did a hard git reset and problem persists

**Comment by sr229** [comment]
Seems to be a proxy issue, will close
