### ISSUE TITLE
Error trying to customize IDE

### ISSUE THREAD

**Issue by marcoarruda** [c9/core#474]
Hello, I'm following this page (https://cloud9-sdk.readme.io/docs/custom-ide-configuration) to customize the IDE for my needs, but I got into this error:

Uncaught TypeError: Cannot read property 'on' of undefined

Basically, I'm just want to remove some plugins I don't need

My custom configuration file is like below:

```
"use strict";

module.exports = function(options) {
    
    var config = require("./default-local")(options);
    
    var includes = [
    ];
    
    var excludes = {
        "plugins/c9.ide.terminal": true,
        "plugins/c9.ide.terminal/link_handler": true,
        "plugins/c9.ide.terminal/opentermhere": true,
        "plugins/c9.ide.terminal/predict_echo": true,
        "plugins/c9.ide.terminal/terminal": true,
        "plugins/c9.ide.terminal.monitor": true,
        "plugins/c9.ide.terminal.monitor/message_view": true,
        "plugins/c9.ide.terminal.monitor/monitor": true,
        "plugins/c9.ide.run/output": true,
    };
    
    config = config.concat(includes).map(function(p) {
        if (typeof p == "string")
            p = { packagePath: p };
        return p;
    }).filter(function (p) {
        if (p.packagePath == "plugins/c9.ide.layout.classic/preload") {
            p.defaultTheme = "flat-light"; // set flat theme as default
        }
        else if (p.packagePath == "plugins/c9.core/settings") {
            if (p.settings)
                p.settings.user = {}; // reset user settings
        }
        return !excludes[p.packagePath];
    });
    
    return config;
};
```

Does anybody succeed trying to customize it?

Thanks

**Comment by nightwing** [comment]
Do you use desktop version or the standalone? For standalone you need to use `var config = require("./default")(options);` instead of `default-local`.
Also where do you get the `Uncaught TypeError: Cannot read property 'on' of undefined` in node console or in browser?

**Comment by marcoarruda** [comment]
It was in the web client console and also an alert message.

But I've changed from `default-local` to `default` and it worked.

It's solved, many thanks!
