### ISSUE TITLE
Strange copy file path

### ISSUE THREAD

**Issue by xczh** [c9/core#486]
Hi
I installed my version of c9/core. It works fine, but I wonder why the "copy file path" function does not work.

As shown in the figure, the actual path is "/workspace/c9/Dockerfile-ubuntu-lts" BUT in "Nevigate" it's "/c9/Dockerfile-ubuntu-lts", also in "copy file path".

So how to fix it? Thanks a lot. 

@nightwing 

![1](https://user-images.githubusercontent.com/12578552/37588920-9f7bc700-2b9e-11e8-9f3c-de42b2c2cc77.PNG)
![2](https://user-images.githubusercontent.com/12578552/37588921-9fa994d2-2b9e-11e8-843a-d74967306afa.PNG)
![3](https://user-images.githubusercontent.com/12578552/37588922-9fd3f8bc-2b9e-11e8-8905-2b6e30d43c6a.PNG)

**Comment by nightwing** [comment]
It copies file path relative to the workspace root

**Comment by xczh** [comment]
So it's not a bug ... I thought it should be an absolute path ... anyway, thanks!
