### ISSUE TITLE
Sync issues between computers

### ISSUE THREAD

**Issue by KyleCulp** [c9/core#489]
I use cloud9 to sync between computers, but I am coming across problems where a project I work on on Computer #1, and then work for days on Computer #2, that when I come back to Computer #1 the old code is still there and is not updating. I have done hard refreshes and all. I am using chrome, and the latest version of c9 sdk.

**Comment by nightwing** [comment]
> I use cloud9 to sync between computers

cloud9 does not have a feature of syncing between computers, use git to sync code, or run cloud9 on a server
