### ISSUE TITLE
Workspace -> Rename File

### ISSUE THREAD

**Issue by cycl0ne** [c9/core#498]
Renaming a file in Workspace : Cursor is not clearly on the name and changing the name can clobber the name since its wrong positioned.
![image](https://user-images.githubusercontent.com/1959048/40721386-a5f0e292-6419-11e8-8064-ae120a9036a1.png)
From the picture you would guess that pressing backspace would delete the m from lowlemel.. but you delete the e: lowlmel

**Comment by dntq83** [comment]
I have same problem

**Comment by bmatusiak** [comment]
yes this is a problem

**Comment by bmatusiak** [comment]
I also see this in other spots... so its not just file tree..   the other spot i found is the ENV dropdown for a runner,,   so it seems it a problem with ace not detecting spacing properly with a small input area. ie: file tree rename and ENV editing

**Comment by cycl0ne** [comment]
hmm, from the repo. does somebody still develop something here? or has amazon closed this code?

**Comment by bmatusiak** [comment]
@cycl0ne @dntq83  i just recently did a reinstall.. and it look like the issue is fixed.. please check

**Comment by nerdybreed** [comment]
yes! I can also confirm this intimidating issue is gone now after a fresh update & install

**Comment by cycl0ne** [comment]
Yes can confirm it. a new install fixes the problem. MAybe a short script to clear cache would help not to reinstall it.
