### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by etopian** [c9/core#5]
It's obvious you guys have abandoned the GPLv3 license. Are you sure there is no code from v2 that was contributed by developers outside of your company under GPLv3. If so, then that would void your license, would it not?

**Comment by javruben** [comment]
I understand where you are coming from. However I am 100% certain this is not the case. The main reason is that Cloud9 v3 is a complete rewrite-from-scratch. We started this over 2 years ago (Feb 2013).

Also note that all (non-trivial) contributions to Cloud9 v2 where made under the [contributor license agreement](https://docs.google.com/a/c9.io/forms/d/1MfmfrxqD_PNlNsuK0lC2KSelRLxGLGfh_wEcG0ijVvo/viewform).

Have you read our document on licensing and the reasoning behind it?
http://cloud9-sdk.readme.io/v0.1/docs/the-licenses-for-cloud9-sdk-and-packages

I hope this helps.

**Comment by etopian** [comment]
Thanks for the response and for releasing this to  the public.
