### ISSUE TITLE
how can i merge js files request?

### ISSUE THREAD

**Issue by 6api** [c9/core#50]
when i open cloud9 in browser
627 requests 257kb transferred 51.11s

**Comment by nightwing** [comment]
You can pass `--packed` argument to `server.js` or open ide with `?packed=1` in the browser
Only downside of this is that file changes are not detected automatically and you will need to manually remove cached files from build/standalone folder in order for them to be recreated.

**Comment by nightwing** [comment]
Please reopen if suggested solution didn't work for you
