### ISSUE TITLE
VFS Exception in function 'tmux'

### ISSUE THREAD

**Issue by nashlai20** [c9/core#52]
hi, I installed c9 core, but I got some undefined exception like below after I started it. 

```
VFS Exception in function 'tmux':
undefined
Scheduling process exit
Exiting after uncaught exception in 'tmux':
undefined
destroying because of error undefined
VFS connection does not exist
```
I don't know what the problem mean. It seems to be some problem for the ”tmux“? 

thanks

**Comment by nightwing** [comment]
Do you see this error in the browser console or command line?
This can happen if either tmux or pty.js was not properly installed.
You can try installing tmux from your package manager (e.g. apt-get)
and running install-sdk.sh script again.

**Comment by nightwing** [comment]
Closing since there is not enough information to fix this issue, please comment if you still see it.

**Comment by aceport** [comment]
+1

**Comment by nightwing** [comment]
@aceport if you see this error, could you please answer question from https://github.com/c9/core/issues/52#issuecomment-89249864?
