### ISSUE TITLE
Nothing happens when lauching install-sdk.sh

### ISSUE THREAD

**Issue by fpalamour** [c9/core#54]
Hello, 

When I launch install-sdk.sh, nothing happens. I tried to see where the script is hanging, and it's on the line "git fetch c9". 
 EDIT : I tried to wait for a long time, and here it is : 

error: Failed connect to github.com:443; Connection timed out while accessing https://github.com/c9/core/info/refs
fatal: c9/master - not something we can merge
Couldn't automatically update sdk core

**Comment by nightwing** [comment]
Hi
How did you clone core repo, and does `git fetch origin ` do anything?

**Comment by fpalamour** [comment]
Hi, thanks for answering, 

I cloned the repo as mentioned in the installation instructions, with :+1: 
git clone git@github.com:c9/core.git c9sdk
The clone command works fine. 

git fetch origin gives me this 
http://puu.sh/gWBLq/b1b7af856a.png

**Comment by nightwing** [comment]
hmm looks like cloning via https urls doesn't work on your machine could you change both instances of `https://github.com/` at https://github.com/c9/core/blob/master/scripts/install-sdk.sh#L35 to ` git://github.com/`

**Comment by fpalamour** [comment]
Same thing. Same error. Connection timed out while accessing https://github.com/c9/core/info/refs

Doesn't cloning the repository use https too ? That's weird. Plus the fact that git fetch origin works.

**Comment by fpalamour** [comment]
I found it, my firewall was just blocking both http(443) and git protocols. 
But now I got a new error. I'm closing this issue, and working on my new issue. Thank you for your time !
