### ISSUE TITLE
Errors while loading workspace

### ISSUE THREAD

**Issue by fpalamour** [c9/core#58]
I think i'm pretty close now from runnning cloud ide. Here is my last error : 

http://puu.sh/gY4mi/266c7cd1ac.png

The web client : http://puu.sh/gY4e2/c68eb72a19.png

Has anyone already experienced this ?

**Comment by nightwing** [comment]
looks like less module is missing, try running `npm install` or `npm install less`

**Comment by fpalamour** [comment]
It seems to work now, thank you again.
