### ISSUE TITLE
How to setup workspaces navigation?

### ISSUE THREAD

**Issue by jdarling** [c9/core#59]
Love the C9 hosted solution and wanted to try using it with some of our private VPC servers.  Installed the local version and was up and running for anything on my drive by launching the editor for the proper workspace.

Now though, I'd like to use the ssh option to mount into our remote servers (private cloud, so no public access that I can use :( ) and can't figure it out.

Also, would be nice to not have to restart C9 from the command line every time to switch projects.  I'm sure this can be done since projects like the BeagleBone Black are using C9, but not finding it.

Any pointers?  Did I miss the docs someplace?

**Comment by javruben** [comment]
You didn't miss anything. The Cloud9 SDK runs standalone. We are working on an on-premise version that has all the features you are looking for. For more information, please email support@c9.io - you might be able to join the beta program.
