### ISSUE TITLE
Clicking the 'Run' button doesn't work. Typing node server.js does

### ISSUE THREAD

**Issue by fpalamour** [c9/core#60]
I wrote a simple server.js. Clicking the run button seems to work, but I couldn't reach my server. 
I tried typing node server.js in the console, and it worked that way.

**Comment by nightwing** [comment]
Do you see any errors in the console? What output is shown in the output tab which is opened when clicking run button

**Comment by fpalamour** [comment]
I just have this from the ide : http://puu.sh/h6vis/98903417b4.png
and this from the terminal : http://puu.sh/h6vkU/56a6268f45.png

**Comment by nightwing** [comment]
It can not work with tmux 1.6, update tmux to version 1.9

**Comment by fpalamour** [comment]
Ok i'll do that. Thanks. By the way, how are we supposed to update the ide ? git pull, then launch install-sdk.sh ?
Cause i've been doing that, and the ide is blocking "Loading my workspace" .

**Comment by nightwing** [comment]
launching install-sdk.sh is enough since it does git pull too.
> and the ide is blocking "Loading my workspace" .

what error messages do you see in browser console?

**Comment by fpalamour** [comment]
There are a lot of css errors, but I don't think that's the real problem. 
There is this though : http://puu.sh/h9GDC/4a3c14f39c.png

**Comment by fpalamour** [comment]
Ok it's working again after i ran the install-dsk script. I'm checking for the 'run button'.

**Comment by fpalamour** [comment]
Well, I no longer have the "tmux 1.6 error" since I managed to install tmux 1.9. When I type tmux -V, it gives me 'tmux 1.9a'. But the terminals on the ide don't work anymore. 

http://puu.sh/h9J3Y/58618cda17.png

No error on the server side : http://puu.sh/h9J5k/3a05669223.png

**Comment by fpalamour** [comment]
http://puu.sh/h9Pwv/d2b18c3580.png

**Comment by fpalamour** [comment]
Solved it. We're good. Thank you for everything.
