### ISSUE TITLE
Custom language syntax is not detected after page reload

### ISSUE THREAD

**Issue by asinyagin** [c9/core#61]
Hi,

I'm working on a plugin with custom language mode.
```javascript
        ace.defineSyntax({
            id: 'solidity',
            name: 'solidity',
            caption: 'Solidity',
            extensions: 'sol'
        });
```
It works fine. But when I open some Solidity file and reload the page, it sets language mode to text. If I'm not mistaken, it happens because my plugin is loaded after the file in editor. Is there any way to make editor to re-detect file syntax?

**Comment by nightwing** [comment]
We could add extensions for syntaxes added with defineSyntax to user/ace/custom-types setting and also iterate over all tabs and call getSyntaxForPath

**Comment by asinyagin** [comment]
@nightwing if I understand correctly, I can't call getSyntaxForPath() from a plugin. Therefore, I have to change ace plugin (defineSyntax() for example), right?

**Comment by Pike** [comment]
I suspect that c6e27314e946cb85d243a837fba6705481a1c270 fixes this.

**Comment by asinyagin** [comment]
@Pike looks like it does. I'll check it. Thanks!

**Comment by nightwing** [comment]
c6e2731 had a bug which is fixed in   https://github.com/c9/core/commit/0cf55559e29f9ef29a1d2c26ad52c52ca189d4c8

**Comment by asinyagin** [comment]
Yes, that helps. Thanks!
