### ISSUE TITLE
Cloud9 IDE [C9 Server Exception 2] undefined

### ISSUE THREAD

**Issue by socialdnalabs** [c9/core#62]
We have installed cloud9 ide locally on ubuntu 12.04LTS 32bit server. Installation steps followed from the url http://ubuntuforums.org/showthread.php?t=1813076
Cloud9 IDE is running and able to see home page ( http://162.243.92.230:3131/ )
When we try to run php or python file, on the console window it shows a message "[C9 Server Exception 2] undefined" 

and also a request to http://162.243.92.230:3131/debug throws "404 Not Found" 
post params are as below,
{"agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0","type":"C9 SERVER
 EXCEPTION","message":{"type":"error","message":"File does not exist: root/local/bin/node","code":2,"data"
:{"command":"Run","file":"root/local/bin/node","runner":"node","args":[""],"env":{"C9_SELECTED_FILE"
:""}}}}

How to fix this issue?

**Comment by nightwing** [comment]
Installations steps in http://ubuntuforums.org/showthread.php?t=1813076 are for older version. To install v3 see https://github.com/c9/core#installation.
