### ISSUE TITLE
[New feature] Reopen last closed tab

### ISSUE THREAD

**Issue by ludoo0d0a** [c9/core#66]
Re-open last closed tab (chrome-like) would be great !

**Comment by nightwing** [comment]
It is already available with alt-shift-t shortcut, try ctrl-. reopen to see it in command pallete
We probably need to add it somewhere in the menu too.

**Comment by ludoo0d0a** [comment]
Great, I missed it ! And yes, in the right menu of the tab it would be a good place too :)
