### ISSUE TITLE
Installation problem on Mac

### ISSUE THREAD

**Issue by bardu** [c9/core#67]
While I had no issues installing the sdk on Ubuntu I have some problems on my new iMac. 
Prior installing the sdk I have installed NodeJS via homebrew.

The c9sdk installation ends with OK, but along the way there are quite some error messages, here is the [npm-debug.log] (https://gist.github.com/bardu/d7fe207048719c892f92)

When running the server I get:
Error: Cannot find module 'amd-loader'

Any clarification would be much appreciated.

**Comment by javruben** [comment]
Could you paste the log from install-sdk.sh?

**Comment by bardu** [comment]
Please find [here.] (https://gist.github.com/bardu/dfcc7a9ba27327fe764f)

**Comment by javruben** [comment]
It seems that your `npm` requires sudo somehow. Perhaps this is something you can fix?

If not, then I suggest to change `install-sdk.sh` to use the npm from `~/.c9/node/bin/npm`. You should then probably also change `server.js` to use `~/.c9/node/bin/node`

**Comment by bardu** [comment]
@javruben: Thanks for your suggestion. Coming from Linux I'm quite new to OSX. Just wondering, homebrew doesn't use sudo to install packages, so if npm requires sudo all nodejs installations with homebrew should have this issue, right?

**Comment by bardu** [comment]
This seems to fix the npm issue:

https://gist.github.com/DanHerbert/9520689
