### ISSUE TITLE
running testing dependency 

### ISSUE THREAD

**Issue by romanman** [c9/core#74]
```
$ ~/c9/c9sdk/plugins/c9.ide.collab/ot# mocha apply_test.js
module.js:338
    throw err;
          ^
Error: Cannot find module '../../../test/setup_paths'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/c9/c9sdk/plugins/c9.ide.collab/ot/apply_test.js:5:5)
    at Module._compile (module.js:
```

I am getting this error for testing try , 
should I install anything else to 
run the test suite ?

Thanks in advance.

**Comment by nightwing** [comment]
Indeed this test depends on some files that are not included in sdk yet.
However tests for user plugins will not need them. How are you intending to use cloud9 test suite?

**Comment by romanman** [comment]
Hey @nightwing , we are developing cool plug-in for
blockchain decentralized application , and in some point
in time we want to have it work with all collaboration tools 
you have on the c9 already , so I am looking for a good way 
to integrate with the whole architecture without breaking 
your policy , if we could have some hangout I can show 
it what have we done so far.

**Comment by javruben** [comment]
@romanman, in which timezone are you? Please send me an email to discuss. ruben@c9.io.

**Comment by romanman** [comment]
@javruben : sent
