### ISSUE TITLE
Support Raspberry Pi-2

### ISSUE THREAD

**Issue by gergely-marko** [c9/core#8]
Your beautiful IDE runs now on my Pi-2. Building it needed some little modifications in the installer scripts, because Pi-2 comes with ArmV7 and the scripts only support armv6.

**Comment by javruben** [comment]
That's great news!

We'd love to receive a PR for your changes. Either to this repo or the one for the install script, here: https://github.com/c9/install.

**Comment by gergely-marko** [comment]
Ok, now it seems to be ok.
Building process takes about one hour on rPI-2.
FYI: I have built node.js v0.12.0 on the PI, configured to build with armv7.
Following the execution of configure, I changed the value of "arm_version" from '6' to '7' in the file "config.gpy".

**Comment by javruben** [comment]
Great, so it runs with 0.12?

What is the full path of config.gpy?

**Comment by gergely-marko** [comment]
Yes it does.
Run configure, which generates config.gpyi.
In config.gpyi replace '6' to '7' at arm_version
make -j 4
... wait ... wait ... wait ...
sudo make install

**Comment by javruben** [comment]
Ok, great to have that here as reference for others. I'll close this ticket now.

**Comment by chintanp** [comment]
I was able to build cloud9 v3 on RPi and got the final message as success. 

Then, when I run "node server.js", it says starting standalone, connect server listening at 127.0.0.1:8181 ... 

Now, I am trying to connect to this instance of server from my laptop, connected on the same LAN. So, I am trying to open the link 192.168.1.5:8181 on my laptop browser (where the IP: 192.168.1.5 is the IP of my RPi on my local LAN), but I get nothing. Anything I am doing wrong ?

**Comment by javruben** [comment]
Try to start it with:

./server.js -l 0.0.0.0

Best,
Ruben

**Comment by chintanp** [comment]
Great it works!!, lovely, just had to get node v0.10, now just have to figure out how to use it well ;) . Thanks.

**Comment by chintanp** [comment]
Summarized my experience here https://medium.com/@chintanp/using-cloud9-3-0-ide-on-raspberry-pi-954cf2d6ab8e and got it working with 

./server.js -l 0.0.0.0 -a : 

which is without authentication.
