### ISSUE TITLE
terminal  input  or show  no-english(like chinese) error!

### ISSUE THREAD

**Issue by bsbrother** [c9/core#81]
maybe unicode not support correct?
when you input chinese, enter 
$ aa暗暗
when you delete 暗暗, show
$ aa

**Comment by nightwing** [comment]
You are write https://github.com/c9/core/blob/master/plugins/c9.ide.terminal/aceterm/libterm.js doesn't support double width characters correctly yet.

**Comment by nightwing** [comment]
This should be fixed by https://github.com/c9/core/commit/b862cf750,  please comment if you still see the issue.

**Comment by goldcome** [comment]
Did the bug really fix it? There are still problems。I want to input chinese 测试, But display `cceces测试`
![image](https://cloud.githubusercontent.com/assets/2740261/13110944/f52cb99a-d5bd-11e5-8af9-7ffcc589346e.png)
