### ISSUE TITLE
Hitting "Yes" in "Files have changed.  Reload?" doesn't reload

### ISSUE THREAD

**Issue by JensenPaul** [c9/core#82]
When I switch git branches and my source files change cloud9 surfaces the "Files have changed.  Reload?" dialog box.  I always hit "Yes" to reload them, but most of the time they don't reload.  I generally have to instead select File->Revert All To Saved, which always works.

**Comment by nightwing** [comment]
This was a regression in undomanager which is fixed now. Please comment if you still see this issue.
