### ISSUE TITLE
node-v0.12.0-linux-arm-pi.tar.gz "Error 404: Not Found"

### ISSUE THREAD

**Issue by joel-putnam** [c9/core#84]
When attempting to install the latest c9sdk I am receiving the 404 not found error for the Pi version of nodejs. It appears to not be available for this version.

**Comment by nightwing** [comment]
https://github.com/c9/install/pull/47 should fix this issue
Could you please try running

```
curl -L https://raw.githubusercontent.com/c9/install/arm-pi/install.sh | bash
```

before install-sdk.sh to test if that works

**Comment by joel-putnam** [comment]
Yes this works. It takes several hours to compile but in the end everything is up and running.

**Comment by nightwing** [comment]
perhaps compiling tmux is the slow part https://github.com/c9/install/blob/master/install.sh#L252
Did it create ~/.c9/tmux folder?

**Comment by SeriousM** [comment]
> perhaps compiling tmux is the slow part https://github.com/c9/install/blob/master/install.sh#L252
> Did it create ~/.c9/tmux folder?

I used the trick from #53 (https://github.com/c9/core/issues/53#issuecomment-88240961)
> `ln -sf $(which tmux) ~/.c9/bin/tmux`

That way it just skips the creation of tmux :+1:
