### ISSUE TITLE
http plugin doesn't parse response with content type "application/json;charset=UTF-8"

### ISSUE THREAD

**Issue by asinyagin** [c9/core#87]
Hi,

Plugin http has following lines:
```javascript
    switch (options.overrideMimeType || res.headers["content-type"]) {
        case "application/json":
            try {
                data = JSON.parse(xhr.responseText);
            } catch (e) {
                return done(e); 
            }
            break;
        default:
            data = xhr.responseText;

    }
```
So, if you set charset in Content-type header, http doesn't parse a response.

**Comment by asinyagin** [comment]
Oh, sorry. It's fixed in the master.

**Comment by asinyagin** [comment]
No, it's not fixed. It checks content type correctly in body encoding, but not in response parsing.

**Comment by nightwing** [comment]
fixed in https://github.com/c9/core/commit/ab562977b5805657f479645c81098703813a13b7
