### ISSUE TITLE
git paths not actionable

### ISSUE THREAD

**Issue by maritz** [c9/core#88]
I don't know if this has ever been in v3 yet, but currently when I get git Output in a terminal the paths are not clickable for the git context menu. (no underline on hover either)

This still works on c9.io, but not on my local install.

Tested under CentOS with c9/core@ab562977b5805657f479645c81098703813a13b7 via Chrome ( 43.0.2357.65 m on a Windows machine in the same network) and Firefox (31.1.0 on the CentOS).

Am I just missing some plugin or something like that?

**Comment by nightwing** [comment]
terminal linkifier depends on terminal prompt for detecting working directory https://github.com/c9/core/blob/ab562977b5/plugins/c9.ide.terminal/aceterm/hover_link.js#L342 it probably it doesn't detect your prompt. try  `PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '`

**Comment by maritz** [comment]
That fixed it, thanks. :-)
