### ISSUE TITLE
scripts/install-sdk.sh fails to detect when curl is not installed

### ISSUE THREAD

**Issue by andrewfaulring** [c9/core#90]
The install-sdk.sh depends upon curl to download the dependency install script:

  https://github.com/c9/core/blob/master/scripts/install-sdk.sh#L120

If curl is not installed, that line fails and an error message is printed to the screen. The error message is surrounded by a lot of other output from the script and so can be easily missed by the user. The install-sdk.sh script fails to detect the error and continues running. If no other errors occur, it reports success despite having failed to install the dependencies. The user then would incorrectly believe that the installation completed successfully.

curl is not installed by default on Ubuntu 12.04 LTS, which is why I noticed this problem.

The script should be updated to detect this failure.

I also recommend mentioned the curl dependency in the "Running the SDK" documentation:

  http://cloud9-sdk.readme.io/v0.1/docs/running-the-sdk#section-installation

**Comment by nightwing** [comment]
@andrewfaulring is wget installed on  12.04 LTS?

**Comment by nightwing** [comment]
Should be fixed with https://github.com/c9/core/commit/3e29bc2d4edb324c29260d5b7d3c2beef35f59a2, please let us know if it isn't

**Comment by andrewfaulring** [comment]
@nightwing wget is installed on all my 12.04 LTS instances, but I cannot tell (or remember) if I manually installed wget since the install logs only go back 12 months.

The manifest file for the ubuntu 12.04 iso lists wget as a pre-installed package:

http://cdimage.ubuntu.com/releases/12.04.5/release/ubuntu-12.04.5-dvd-amd64.manifest

Though, I do not have a clean install to verify.

BTW, curl is not listed as a pre-installed package.

**Comment by andrewfaulring** [comment]
@nightwing The wget command just downloads install.sh without piping to stdout, so bash never executes the script. Adding "-O -" to wget will pipe it to stdout, but does not save the file to the local disk as the curl command version does.

https://github.com/c9/install

Not sure if saving a copy of install.sh is necessary. If it is, perhaps split the work in installGlobalDeps() into two commands: one to download, the second to execute via bash. That should work for both wget and curl. If not, the you can drop the -O option from curl.

**Comment by nightwing** [comment]
@andrewfaulring thanks for noticing this
Saving to file was indeed unnecessary. With https://github.com/c9/core/commit/281925be9e8b902c08b371b5f78e192ddee57b9b it must work better.

**Comment by andrewfaulring** [comment]
I tested with both wget and curl. 281925b works fine for both. Thanks for fixing this issue.
