### ISSUE TITLE
Breakpoints not activating in OSX (local)

### ISSUE THREAD

**Issue by ggoodman** [c9/core#91]
I've installed the latest c9sdk and created a local Application:

```
git pull
./scripts/install-sdk.sh
./scripts/setup-local-dev.sh
```

When running an application, I have two issues:

1. The full absolute path of the project's initial file needs to be specified regardless of what is indicated in the CWD setting.
2. Breakpoints will not be triggered during execution.

No errors or log messages appear during execution in the devtools windows.

**Comment by nightwing** [comment]
Is the script you are debugging in `~` directory?

**Comment by ggoodman** [comment]
It is in ~/Projects/appName/server.js

**Comment by ggoodman** [comment]
@javruben I've had to stop using c9 local because this still doesn't work for me. Not sure that this issue should be closed.

**Comment by javruben** [comment]
The bugfix was just merged - auto closing this issue. It will be in the core repo within 24 hours.

**Comment by nightwing** [comment]
@ggoodman this should be fixed by https://github.com/c9/c9.ide.run.debug/commit/f4d8c0e8d979d92282010f3782a4b7e07bddea8e, please let us know if it still doesn't work for you.

**Comment by ggoodman** [comment]
This is awesome. Thank you all for your hard work.
