### ISSUE TITLE
mean.io starter app

### ISSUE THREAD

**Issue by zwhitchcox** [c9/core#92]
Hey guys, I just started using cloud 9 IDE, and I absolutely love it! I was going to start building something similar to this for mean apps, but now it looks like I might not have to ;)

I'm on the [mean.io](https://github.com/linnovate) team, and I was wondering if there was any way you guys could feature us on your "starter app" page, maybe right alongside the meteor app.

We are extremely comparable, and I'm sure no one would have a problem reciprocating with a link/info about you guys in our documentation.

Also, I know many people prefer angular to meteor, and it would make things more convenient for those users.

Anyway, just a thought. Is this of any interest to you at all, or would we just need to fork the project?

**Comment by nonken** [comment]
Could you get in touch with me via email? nikolai@c9.io
