### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zwhitchcox** [c9/core#93]
I keep getting this error:
```
Resolving nodejs.org (nodejs.org)... 165.225.133.150
Connecting to nodejs.org (nodejs.org)|165.225.133.150|:443... failed: Connection refused.
```
when I try to install c9 core.

I know this isn't really your issue, but I was wondering if anyone had any tips

**Comment by Pike** [comment]
was down for all the world, says twitter (and for me), but it just resurfaced.

**Comment by zwhitchcox** [comment]
Ah. Thanks dude!
