### ISSUE TITLE
Node.js runner with debugger extremely unstable

### ISSUE THREAD

**Issue by maritz** [c9/core#94]
I'm trying to debug a relatively "large" project and just starting it with the debugger enabled usually causes the following con the console output of my c9sdk/server.js:

```
(null):0
(null)

RangeError: Maximum call stack size exceeded
destroying because of error undefined
VFS connection does not exist
```

Sometimes it just hangs after "Debugger listening on port 15454" in the IDE.

I've tried node v0.10.38 and v0.12.3. I've tried adding more and more maximum call stack size to seemingly absurd values (with both --stack-size and --max-stack-size, apparently one is for v0.10 and one for v0.12 even though v0.12 still claims the old one in the help)

OS: CentOS 4

Is there anything else I could try?

**Comment by nightwing** [comment]
This seems to be caused by pty.js 0.2.6.
Please try running `cd ~/.c9; npm install pty.js@0.2.7-1` to update it to the latest version.

**Comment by maritz** [comment]
Seems to work fine now. Thanks. :+1:

**Comment by 00christian00** [comment]
Hi,
As of today a fresh install still use pty.js 0.2.6 causing this error. The fix above patch the issue, but it wasn't easy to discover. 
Please change the installer, thanks.

**Comment by nightwing** [comment]
@00christian00 installer have been changed long ago see https://github.com/c9/install/blob/master/install.sh#L394

there must have been some other error. To debug it you can try
```sh
mv ~/.c9 ~/.c9-bak
curl -L https://raw.githubusercontent.com/c9/install/master/install.sh | bash
node -p "require('$HOME/.c9/node_modules/pty.js/package').version"
```

**Comment by 00christian00** [comment]
You are right, I tried again a fresh install and this time I see no errors.
Strange.
